### ISSUE TITLE
Community Fork Time!

### ISSUE THREAD

**Issue by MerreM** [zappa/Zappa#1]
## Context

It's been 4 months since this has seen any activity from a maintainer AFAIK, and I have multiple projects that depend on this.

I don't know about other users, but I think I'm getting to the point where I'd rather we made a community fork than just *wait* for the docs to come up again/some of the issues be resolved.

I say we, as I've never run an open source project and frankly don't have a clue what I'd be doing with it, but I can probably make some time to help out.

## Expected Behavior

The project should be maintained, docs should be available some communication between users and maintainers would also be good. AFAIK The slack is down, the blog is down and the project is increasingly "rotting on the vine".

## Actual Behavior

It's been dead since for ~ 4 months.

## Possible Fix

Members of the community make a fork - organise and get to work.

(I assume this is what you wanted? @jneves )

**Comment by jasonrhaas** [comment]
I agree -- this project is too big to fail.  Zappa has been an amazing project and I want to see it live on and prosper!

**Comment by bahoo** [comment]
Jazzband could be an option ( and/or a model to glean from ): https://jazzband.co/about/guidelines

**Comment by NinitoAS** [comment]
Zappa is amazing. Anyone know of any alternatives if this dies out?

**Comment by hortonew** [comment]
https://github.com/aws/chalice/ is one alternative, but hoping development continues on Zappa (i'll contribute).

**Comment by NinitoAS** [comment]
Yeah, I hope development will continue too. Our whole backend uses Zappa. I heard Chalice is not as good, especially when it comes to logging. Zappa's tail function is legendary, keeps me from having to manually go through Cloudwatch for logs.

Thank you for contributing!

**Comment by jasonrhaas** [comment]
The problem with chalice is that you can't take advantage of all the flask community and plugins.  Chalice is good for simple projects or ones where you need tight AWS integration.  Zappa is more powerful because you can take advantage of the flask community and plugins.

**Comment by zyd14** [comment]
I haven't really contributed to open-source much but would love to help support this, I have lots of projects that use this as a backbone and have started to dive deeper into the source code to better understand how it works.
[serverless](https://github.com/serverless/serverless) is an alternative that's been suggested to me, but I really can't imagine porting all my teams applications to another project at this point, and there are some pretty neat bells and whistles that zappa provides that I've started to use as building blocks for some cool patterns (looking at you remote async lambda invocation).

Anyway, hope this can be continued here and would totally be willing to work on some issues! Huge thanks to everyone who's kept it going this far!

**Comment by ebridges** [comment]
I was fortunate in that I was only a few months into using Zappa when I realized that the project had stalled. I was also concerned about the overall code quality and coherence.

These led me down a path to implement mostly equivalent functionality here:
https://github.com/ebridges/lgw

Would love to hear any feedback on that.

Cheers

**Comment by mattvonrocketstein** [comment]
So this was copied from the original issue at https://github.com/Miserlou/Zappa/issues/2173 , so I guess we now have a  community fork.  Who can merge/commit?  https://github.com/orgs/zappa/people shows no public members.  I have a small PR to contribute, wondering how best to proceed.

**Comment by hortonew** [comment]
@MerreM how do you want to proceed with management of this repository?

**Comment by MerreM** [comment]
@hortonew I don't know, I thtink I've managed to contribute maybe 2 lines  to open source software thus far over my career, but I'm eager to help out, if I can.

I didn't open this repo, but I believe @jneves did...

If there's still radio silence, we should make a fork and start divvying up the work.

Rehost the docs, organise pull requests, get a slack up and running  etc.

**Comment by pritamps** [comment]
I would be happy to contribute!

**Comment by mattvonrocketstein** [comment]
@jneves do you own this repository / are you able to coordinate anything here?  Can we get more clarity about whether this project IS the community fork?  It looks like people (myself included) are willing to donate effort here, but if we don't get clarity on how to move forward then eventually then interest will fade or we'll be discussing forking the fork..

Some of the work to do is clear, like slack/rehosting docs was mentioned, probably CI with github actions?  But if people start filling up this project with issue-descriptions and PRs, can they have the reasonable expectation that any of this is going to get traction?

**Comment by efimk-lu** [comment]
Hey, I'm organizing a webinar on Serverless frameworks and I want to have a special one on Zappa. I tried contacting @jneves and @Miserlou to no avail, it looks like everyone disappeared. Two questions:
* Any way of getting in touch with these people?
* Is there anyone here who wants to participate in the webinar, talking about Zappa --> sounds like a good chance to rally the developers in putting this wonderful framework back on its feet.

**Comment by Alex-Mackie** [comment]
I am in a similar position. I have several Django projects for which Zappa has been a perfect deployment solution. In my view it  uniquely serves a purpose that the the other frameworks discussed above (Chalice and Serverless) do not (and will not try to).

Similar to some other commenters here my technical competence in this area is a bit shallow but if there is anything I can do, I will.

**Comment by MerreM** [comment]
Right - I've started developing on https://github.com/MerreM/Zappa as and when I get the time.

Send me pull requests!

Message me on here for the link to the slack - I'm going to need help.

**Comment by MerreM** [comment]
https://join.slack.com/t/zappagroup/shared_invite/zt-ludx5h93-khGw664m9I5hlm1EXvhlEg

https://zappagroup.slack.com

AnyoneEveryone invited - please help!

**Comment by techdragon** [comment]
For anyone else who considers clicking the above slack links posted by @MerreM. They appear to be shut down.

**Comment by hellno** [comment]
Closing this, as a team of contributors is back to supporting the zappa project

**Comment by mattvonrocketstein** [comment]
@hellno so should we now assume that this repository/org is the canonical one for zappa, and that pull requests will be considered/merged? is it realistic to try and contribute changes now, or are the new maintainers finding their footing and busy handling the existing backlog of PRs (~30 at the time of this post)
