### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'add_description'

### ISSUE THREAD

**Issue by MayaraMacielMatos** [zappa/Zappa#1000]
Error deploy

 self.cf_template.add_description("Automatically generated with Zappa")
AttributeError: 'Template' object has no attribute 'add_description'

**Comment by mikedklein** [comment]
Troposphere updated `add_description` to`set_description` along with other previously deprecated template methods. https://github.com/cloudtools/troposphere/blob/23aafdce2a7780d0e1b24700648dddd6f8d2b04b/CHANGELOG.rst#300-20210705 

I think it would be as easy as updating this [line](https://github.com/zappa/Zappa/blob/1cdbd7f828b643b2a70c32fd334ec4f0662642de/zappa/core.py#L2417) to `set_description` once I get a workaround for the build I will try to put a PR in.

**Comment by mikedklein** [comment]
If you froze your requirements prior to the 3.0.0 troposphere release you should be fine. If not just add `troposphere==2.7.0` to your requirements.txt to make sure to lock the version in and that should solve the issue for now.

**Comment by mikedklein** [comment]
@MayaraMacielMatos I am not sure closing this is the best. If a user today decided to use Zappa this could happen when they install all their dependencies.

**Comment by MayaraMacielMatos** [comment]
I appreciate the help, I'll keep it open

**Comment by adosaa** [comment]
Same issue here using ci/cd aws code build...partially solved using hardcoded version of troposphere==2.7.1

**Comment by mikedklein** [comment]
Looks like there is a related [issue](https://github.com/zappa/Zappa/issues/998) and subsequent [PR](https://github.com/zappa/Zappa/pull/999) we can probably safely close this issue @MayaraMacielMatos

**Comment by mapattacker** [comment]
hope it can be resolved soon since this is a simple bug to fix. thanks for pointing the resolution @mikedklein

**Comment by FalconBFR** [comment]
+1

**Comment by FalconBFR** [comment]
Thanks for the prompt response and help. I changed the code to 'set_response' myself and everything is resolved.

**Comment by DPS0340** [comment]
For pipenv users, edit Pipfile like:
```
[packages]
troposphere = { version = "<3.0", ignore = ["zappa"] }
zappa = "*"
```

**Comment by ian-whitestone** [comment]
> What I don't understand is why the version isn't being locked per the generated requirements.txt file. It should be locked at 2.7.0.

I was also very confused by this @mikedklein , but it looks like the `setup.py` relies on the `requirements.in`, not the `requirements.txt`

https://github.com/zappa/Zappa/blob/master/setup.py#L10-L21

```python
import os
import sys
from setuptools import setup
from io import open
from zappa import __version__

with open('README.md') as readme_file:
    long_description = readme_file.read()

with open(os.path.join(os.path.dirname(__file__), 'requirements.in')) as f:
    required = f.read().splitlines()

with open(os.path.join(os.path.dirname(__file__), 'test_requirements.in')) as f:
    test_required = f.read().splitlines()

setup(
    name='zappa',
    version=__version__,
    packages=['zappa'],
    install_requires=required,
    tests_require=test_required,
    test_suite='nose.collector',
    include_package_data=True,
    license='MIT License',
    description='Server-less Python Web Services for AWS Lambda and API Gateway',
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://github.com/zappa/Zappa',
    author='Rich Jones',
    author_email='rich@openwatch.net',
    entry_points={
        'console_scripts': [
            'zappa=zappa.cli:handle',
            'z=zappa.cli:handle',
        ]
    },
```

And in `requirements.in` it doesn't specify a version for `troposphere`:

```
argcomplete
boto3>=1.17.28
durationpy
hjson
jmespath
kappa==0.6.0
pip>=9.0.1
python-dateutil
python-slugify
PyYAML
future
# previous version don't work with urllib3 1.24
requests>=2.20.0
six
toml
tqdm
troposphere
# See https://github.com/Miserlou/Zappa/issues/2036
Werkzeug<1.0
wheel
wsgi-request-logger
pip-tools
```


@jneves @mcrowson i wonder if there's an opportunity to get rid of the `requirements.txt` and just rely on `requirements.in` to avoid this confusion? Or alternatively update `setup.py` to rely on `requirements.txt` instead?

**Comment by luistm** [comment]
I tried the solutions above, but now I get
```
error in troposphere setup command: use_2to3 is invalid.
```

Anyone having the same problem?

**Comment by clown-0726** [comment]
@mikedklein If I lock troposphere  at 2.7.0, I will get another error which is `error in troposphere setup command: use_2to3 is invalid.`.

How did you git rid of this or you didn't run into this issue?

**Comment by vlayusuke** [comment]
@luistm Thank you for your advice. But still the same error reappears in my environment.

- macOS Big Sur 11.6
- Python: 3.8.10
- Flask: 1.1.4
- troposphere: 3.0.0
- zappa: 0.53.0

**Comment by hellno** [comment]
a new zappa version was released, including a fix for this: 
https://github.com/zappa/Zappa/releases/tag/0.54.0
