### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'add_description'

### ISSUE THREAD

**Issue by kazitanvirahsan** [zappa/Zappa#1002]
<img width="1138" alt="Screen Shot 2021-07-08 at 9 38 01 pm" src="https://user-images.githubusercontent.com/6487015/124915500-f481ca80-e034-11eb-9cb7-766e139327aa.png">

Continuously getting this error while deploying basic flask application to AWS. Any help would be much appreciated.

**Comment by pulsedemon** [comment]
I'm also getting this error on 0.52.0

**Comment by Raam124** [comment]
I'm also getting this error

**Comment by xncbf** [comment]
Same issue occurs. But update was done.

**Comment by kazitanvirahsan** [comment]
Hai Guys,
I was able to bypass these issues. It has something to do with the troposphere for AWS cloud formation. 
pip3 install "troposphere==2.7.0"
References: https://github.com/zappa/Zappa/issues/1000

**Comment by ochilab** [comment]
I also faced same issue, but avoided it due to kazitanvirahsan's solution.

**Comment by Puude** [comment]
Same

**Comment by ian-whitestone** [comment]
This is a duplicate of https://github.com/zappa/Zappa/issues/1000, can we close this one and keep discussion in there?

**Comment by monkut** [comment]
https://github.com/zappa/Zappa/issues/1000
duplicate, closing.
