### ISSUE TITLE
Manylinux wheels for packages like pandas and numpy cannot be replaced by zappa

### ISSUE THREAD

**Issue by faiyeah** [zappa/Zappa#1005]
I was trying to zappa deploy a python 3.8 function to AWS Lambda using MacOSX development environment. 
The python 3.8 function depends on numerous packages, including pandas. 
When I was doing development, and cross check the deployment package of zappa, i found that the pandas library in the package is still darwin's wheel, expected to be manylinux wheel. 

## Expected Behavior
Expect manylinux wheels for pandas and numpy will be replaced when calling zappa deploy / update.

## Actual Behavior
Pandas and numpy inside the virtualenv is still darwin package 

## Possible Fix
Change the line at https://github.com/zappa/Zappa/blob/1cdbd7f828b643b2a70c32fd334ec4f0662642de/zappa/core.py#L320
from:
f'^.*{self.manylinux_suffix_start}-manylinux({"|".join(manylinux_suffixes)})_x86_64.whl$'
to
f'^.*{self.manylinux_suffix_start}(.*?)(-|.)manylinux({"|".join(manylinux_suffixes)})_x86_64.whl$'

## Steps to Reproduce

1. write a python 3.8 lambda handler
2. create an environment with pip install the latest pandas
3. try zappa deploy in macos, with delete_local_zip = false
4. unzip the generated package, check the wheel tag for pandas
5. Find the wheel tag is cp38-cp38-macosx_10_9_x86_64, which is unexpected

## Your Environment

* Zappa version used: latest (0.53)
* Operating System and Python version: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 i386, Python 3.8.6
* The output of `pip freeze`: 
argcomplete==1.12.3
boto3==1.17.112
botocore==1.20.112
certifi==2021.5.30
cfn-flip==1.2.3
charset-normalizer==2.0.2
click==8.0.1
durationpy==0.5
future==0.18.2
hjson==3.0.2
idna==3.2
jmespath==0.10.0
kappa==0.6.0
numpy==1.21.0
pandas==1.3.0
pep517==0.10.0
pip-tools==6.2.0
placebo==0.9.0
python-dateutil==2.8.2
python-slugify==5.0.2
pytz==2021.1
PyYAML==5.4.1
requests==2.26.0
s3transfer==0.4.2
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.61.2
troposphere==3.0.1
urllib3==1.26.6
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.53.0
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by CaseGuide** [comment]
Same issue on Win 10, Python 3.7, zappa==0.53.0 with numpy. Verified wheel tag is `cp37-cp37m-win_amd64` in the zip file. 

I made change to the code you suggested however that caused no manylinux wheels to be installed. 

It looks like [this may be a relevant issue](https://github.com/numpy/numpy/issues/18988) on the numpy issue tracker. Based on that I downgraded to numpy 1.19.4.

**Downgrading to numpy==1.19.4 resolved the issue.**

When deployed it causes an error like:
`Original error was: No module named 'numpy.core._multiarray_umath'`

Logs:
```
[1628009634217] Instancing..
[1628009635324] [ERROR] ImportError: Unable to import required dependencies:
[1628009635324] numpy:
[1628009635324] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[1628009635324] Importing the numpy C-extensions failed. This error can happen for
[1628009635324] many reasons, often due to issues with your setup or how NumPy was
[1628009635324] installed.
[1628009635324] We have compiled some common reasons and troubleshooting tips at:
[1628009635324] https://numpy.org/devdocs/user/troubleshooting-importerror.html
[1628009635324] Please note and check the following:
[1628009635324] * The Python version is: Python3.7 from "/var/lang/bin/python3.7"
[1628009635324] * The NumPy version is: "1.21.1"
[1628009635324] and make sure that they are the versions you expect.
[1628009635324] Please carefully study the documentation linked above for further help.
[1628009635324] Original error was: No module named 'numpy.core._multiarray_umath'
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)e

```

**Comment by david-wallace-croft** [comment]
I am seeing something similar with psycopg2-binary.  It looks like psycopg2 switched to using PEP600:
https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-9

So now instead of having a filename like this:
psycopg2_binary-2.8.6-cp38-cp38-manylinux1_x86_64.whl

It now looks like this:
psycopg2_binary-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

It looks like the the manylinux_wheel_file_match regular expression almost finds the PEP600-formatted filename using the legacy suffix except that now there is a period before "manylinux" instead of a hyphen.  It looks like the possible fix recommended above could work.

**Comment by dpmccabe** [comment]
I was still having this issue with 0.54.0 and `pandas==0.25.2`. Getting macOS wheel tag (`cp39-cp39-macosx_10_15_x86_64`) in the generated package. This version of Zappa has the following regexes:

```py
        # AWS Lambda supports manylinux1/2010 and manylinux2014
        manylinux_suffixes = ("2014", "2010", "1")
        self.manylinux_wheel_file_match = re.compile(
            f'^.*{self.manylinux_suffix_start}-(manylinux_\d+_\d+_x86_64[.])?manylinux({"|".join(manylinux_suffixes)})_x86_64[.]whl$'
        )
        self.manylinux_wheel_abi3_file_match = re.compile(
            f'^.*cp3.-abi3-manylinux({"|".join(manylinux_suffixes)})_x86_64.whl$'
        )
```

Upgrading pandas to 1.3.4 fixed this, so it would seem as if the current regex is no longer backward-compatible with some older wheels. Not sure if it ever was.

However, I'm still unable to get the Linux wheel for `psycopg2==2.9.1`.

**Comment by dpmccabe** [comment]
Whoops, I didn't have psycopg2-binary in my dependencies. That fixed it.

**Comment by hellno** [comment]
Thanks for the update @dpmccabe - closing this issue as there are no more issues reported so far 👍🏽

**Comment by faiyeah** [comment]
Confirmed my original reported issue is gone. Thanks all.
