### ISSUE TITLE
django.db.utils.OperationalError: could not connect to server: Connection refused | Zappa

### ISSUE THREAD

**Issue by khixer** [zappa/Zappa#1010]
Hi,

I'm facing the following error on `zappa deploy or zappa update`. 
**Error:**
```
django.db.utils.OperationalError: could not connect to server: Connection refused
 Is the server running on host "localhost" (127.0.0.1) and accepting
 TCP/IP connections on port 5432?
```
My lambda is in the same VPC as RDS. Both share the same security groups as well.

**Potential Problem**
- Could be issues of security groups
- Lambda need internet access

**Tried**:
- Giving internet access to lambda as suggested [here](https://gist.github.com/reggi/dc5f2620b7b4f515e68e46255ac042a7) and [here](https://stackoverflow.com/questions/37135725/aws-lambda-connecting-to-internet)
- Also tried with no VPC and call external REST API deployed in EB.

Content of `zappa_settings.json` as follows:
```
{
  "staging": {
    "aws_region": "us-west-2",
    "django_settings": "xyz.settings.staging",
    "log_level": "DEBUG",
    "events": [{
      "function": "xyz.my_task",
      "expression": "rate(7 days)"
    }],
    "profile_name": "default",
    "project_name": "xyz",
    "runtime": "python3.8",
    "s3_bucket": "zappa-bgworker",
    "debug": true,
    "keep_warm": false,
    "slim_handler": true
  }
}
```
Any help would be appreciated.

**Comment by souravjamwal77** [comment]
Hi @khixer, I think you also need to update the DATABASES settings in your Django settings to set the correct **host, user, and password**. It looks like from the error that you're trying to connect with "localhost" which is not available on your lambda.

**Comment by monkut** [comment]
This is a configuration issue and not directly related to zappa.
Closing.
