### ISSUE TITLE
Question: Why does Zappa call unschedule/schedule when calling update?

### ISSUE THREAD

**Issue by suriya** [zappa/Zappa#1019]
I see that `zappa update` invokes `self.schedule()` https://github.com/zappa/Zappa/blob/bb5834fa2f7c31f56cdc39fa883b96f9a99408e3/zappa/cli.py#L1232  which in turn invokes `self.zappa.schedule_events()` https://github.com/zappa/Zappa/blob/bb5834fa2f7c31f56cdc39fa883b96f9a99408e3/zappa/cli.py#L1429 which calls `self.unschedule_events` https://github.com/zappa/Zappa/blob/bb5834fa2f7c31f56cdc39fa883b96f9a99408e3/zappa/core.py#L3002

It looks like that on every update, Zappa unschedules all event handlers, removes permissions and creates them again.

Could someone explain the reasoning behind this implementation choice?

Specifically, if I comment out the call to `schedule()` while doing an update, would there be any negative consequence? I prefer to explicitly control events with schedule and unschedule.

**Comment by faiyeah** [comment]
I guess this is a trick to make sure all periodic scheduled event ( rate xxxxxxx) are run once immediately.

**Comment by monkut** [comment]
I believe that currently there no way to detect a change in the schedule, so the schedule is re-created on each deployment.


closing.
