### ISSUE TITLE
Feature: Automatic gzipping of responses

### ISSUE THREAD

**Issue by john-parton** [zappa/Zappa#1027]
I had a few large pages which exceeded lamba's response size limits, so I patched Zappa to automatically compress responses with gzip.

## Context
My app is behind CloudFront, so I didn't do any checking for `Accept-Encoding` and always gzip the response if the base64 encoded gzip'd response is smaller than the non-compressed response.

HTML and JSON are _extremely_ compressible, so even with the overhead of base64 encoding, you often can squeeze a ton more data in.

**Comment by monkut** [comment]
This may be a good *option* to have in zappa, but currently external libraries, like [whitenoise](http://whitenoise.evans.io/en/latest/), can perform this for you.

**Comment by john-parton** [comment]
I'm not sure you're correct. Whitenoise is just for static files. 

My (closed) PR gzip'd every response, including those dynamically generated by your views.

I'm not a Zappa user anymore, so I probably will not be contributing any further changes.
