### ISSUE TITLE
DEPRECATED ???

### ISSUE THREAD

**Issue by illing2005** [zappa/Zappa#1043]
Just saw that the project got marked as deprecated :cry: 

Are there any plans to find new maintainers or move the project to an organization like [jazzband](https://jazzband.co/)?

**Comment by mdunc** [comment]
Yeah, kind of came out of nowhere. "Deprecated" is an odd term to use as I think many would interpret that as their being something newer that replaces Zappa. Would have been nice to have had some discussion or some sort of heads up instead of a quiet commit to master. I understand the maintainers worked on this in their spare time, but there's been a decent amount of community contributions (many seem to have gone unseen or ignored unfortunately) and I'm sure some would have volunteered to help review and merge these PRs and close issues had they been asked before it got to this point. 

Zappa has been wonderful to work with and I hope it can continue.

**Comment by klorophyl** [comment]
Yeah this comes as a shock. It's a weird way to announce the deprecation of such an impactful project. I mean just search for "django lambda" there is next to nothing else and even third-party tools have integration for it.

I really hope we find a solution to keep the project going, the community seems active enough. 
It would be a shame to see Zappa die, I know I'd be screwed ... just forked it but it's not a viable solution.

**Comment by illing2005** [comment]
@mcrowson , can you send me an invite to your slack?

And could you please merge this pr https://github.com/zappa/Zappa/pull/1042 as the last contribution?
Otherwise, zappa will be broken on Oct 1st

**Comment by mcrowson** [comment]
Link to slack channel is here: https://github.com/zappa/Zappa#contributing.

**Comment by illing2005** [comment]
Yes, I've seen that but I couldn't register anywhere :confused:

**Comment by mcrowson** [comment]
What's your email? I can invite you from slack then.

**Comment by emarty-maze** [comment]
@mcrowson please add me as well. erik@paxsolutions.io

**Comment by mcrowson** [comment]
For anyone else who wants in: https://join.slack.com/t/zappateam/shared_invite/zt-fu9usrrn-h4fZNYjppKOWqtycb34mXw

**Comment by suriya** [comment]
@mcrowson and other maintainers and contributors who have made Zappa great piece of software that we get to rely on. Thank you very much for your contribution.

I have started https://github.com/zappanext/Zappa Contributors welcome.

**Comment by mcrowson** [comment]
It sounds like multiple people may be interested in picking this up. I'm happy to share the current repo and org so we don't get unseeded competing forms. By all means fork and go forth if you want, but you may have an easier time with issue and PRs using the current project.

**Comment by illing2005** [comment]
Yes, it would be great if we can keep the zappa org and the current repo

**Comment by mcrowson** [comment]
There has been a lot of activity on slack. It looks like we will have people step up to maintain this going forward. I anticipate the project will be reactivated within the coming days. Thank you all so much for stepping up. 

🎆 🍾

**Comment by opqpop** [comment]
Amazing! Thank you to the community! Zappa is an amazing project for us to use and we look forward to continuing to use it for a long time
