### ISSUE TITLE
Will my data base get lots of connections If there are many requests happen

### ISSUE THREAD

**Issue by clown-0726** [zappa/Zappa#1053]
## Context
I love zappa very much as my team can run the flask application on aws lambda. We don't have to worry our application will be offline someday.

But we are also using SQLAlchemy to connect db in our application. With my understanding lambda will be started every time when a request comes. **Does it mean each application starting will create a new db connection right?** You know, there only few db connections can be consumed in an online database. BTW, if not, how zappa handle the db connection in this situation?

Thanks support team, looking forward your suggestions on this.

**Comment by monkut** [comment]
There are not plans at the moment to introduce any new feature to address this.

As APet99 mentions RDS Proxy is available to manage connections. 
At the moment this is outside of the scope of the zappa project.

closing.
