### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [zappa/Zappa#1061]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Zappa/lokal -name '*.py')
```

:crystal_ball: How will the development interests evolve further also according to update candidates in 31 lines of this software?

**Comment by hellno** [comment]
Hey! 
Happy to get a PR on specific changes. I'm not sure an automated solution in a CI/CD script is needed, yet

**Comment by elfring** [comment]
:thought_balloon: Would you dare to take another look at any generated change suggestions?

**Comment by hellno** [comment]
> 💭 Would you dare to take another look at any generated change suggestions?

Sorry, just tried the command - it doesn't return anything for me (but I'm also no perl expert :)

**Comment by elfring** [comment]
:thought_balloon: Did you adjust the specification “~/Projekte/Zappa/lokal” (from the command example) according to your software analysis and test environment?

**Comment by hellno** [comment]
yes

**Comment by hellno** [comment]
Can you explain the value of the results and maybe paste them here?

In any case I'd welcome you to open a pull request with potential changes 😊

**Comment by elfring** [comment]
:thought_balloon: You made me curious why no update candidates would be found in your test environment.
(How many Python files may be taken into account for a corresponding source code analysis in a selected directory?)

I am also looking for further possibilities to improve the mentioned transformation approach.

**Comment by hellno** [comment]
Happy to discuss this in dm or public channel on slack :) closing this issue for housekeeping

**Comment by elfring** [comment]
:thought_balloon: Can you follow [the rationale from the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)?
