### ISSUE TITLE
[Question] Is there a way to set the API Gateway stage on AWS different from the 'stage name' in the config?

### ISSUE THREAD

**Issue by dsmurrell** [zappa/Zappa#1062]
I have 3 stages... dev, staging, and prod. But I would like each of the three API Gateway endpoints to have a single API Gateway stage name of 'api' so that my app is accessible at '/api' on all three instead of '/dev', '/staging', and '/prod'.

I know about custom domains but this doesn't work for me because I share the domain with my front end client through a Cloudfront Distribution.

Is there a technical reason that there isn't configuration (that I can see) for this?

**Comment by dickermoshe** [comment]
I don't understand.
How would it be possible to have have 3 different stages with the same URL ?

**Comment by dsmurrell** [comment]
Ah, the  cloud environments are on three different URLs. Currently my setup is:

```
dev.domain.tld/dev
staging.domain.tld/staging
domain.tld/prod
```

for the api routes. I would like it to be:

```
dev.domain.tld/api
staging.domain.tld/api
domain.tld/api
```

currently it looks like I'm forced to have the `/x` part of the URL match the stage name. I was wondering if I could set it different from the stage name to achieve the above.

**Comment by monkut** [comment]
If you are using custom domains, I don't think the staging prefix will interfere given a custom domain configuration.
