### ISSUE TITLE
Can't run Zappa 0.54 and Flask 2

### ISSUE THREAD

**Issue by juandelperal** [zappa/Zappa#1066]
## Context

Hi! Thanks for the latest updates :) 
I would like to update to the latest version using flask 2 but I can't, due to `Werkzeug`
```
The conflict is caused by:
    flask[async] 2.0.1 depends on Werkzeug>=2.0
    zappa 0.54.0 depends on Werkzeug<1.0
```

## Expected Behavior

I need to run Zappa **0.54** with flask 2

## Actual Behavior

If I use flask 2, I can only run Zappa **0.50**

## Steps to Reproduce

1. Set a new venv
2. Create requirements.txt
```
flask[async]>=2.0.1
zappa>=0.54.0
```
3.  pip install -r requirements.txt

## Your Environment

* Zappa version used: none 
* Operating System and Python version: Python 3.9 mac os 10.14.6 (18G9323)
* The output of `pip freeze`: None, I couldn't install
* Link to your project (optional):
* Your `zappa_settings.json`: Not relevant for this issue

**Comment by rafagan** [comment]
Any progress on that? Seems to me that Zappa doesn't have support anymore from community :/

**Comment by javulticat** [comment]
Resolved as of `v0.54.1` via #1067

**Comment by juandelperal** [comment]
Great! 
https://pypi.org/project/zappa/
is still pointing to 0.54.0

Will it be updated soon? Should we install with 
`pip install -e git://github.com/zappa/zappa.git@0.54.1#egg=zappa`
instead?

Thanks

**Comment by javulticat** [comment]
@juandelperal sorry I jumped the gun yesterday, `v0.54.1` is _now_ available in `pypi`
