### ISSUE TITLE
Use Route53 Alias DNS records rather than CNAME

### ISSUE THREAD

**Issue by yapret** [zappa/Zappa#1073]
## Context

When setting up a custom domain hosted on Route53, Zappa uses an Alias record when that custom domain is the apex of the Hosted Zone, and a CNAME record otherwise.

To me, CNAME records seem:
- Slower as the client needs to do two requests (one on the custom domain, then one on the CNAME target)
- More expensive as CNAME requests are billed where Alias ones aren't
- Problematic when needing to add other types of records for the same hostname (TXT for SPF, for example)

This behavior cannot be configured at the moment, and adds some complexity to the code.

Relevant part of the code:
https://github.com/zappa/Zappa/blob/679e98eb7c38913022a5cb0d0610e4529d4340d2/zappa/core.py#L2652-L2695

## Expected Behavior

Zappa should create Alias A/AAAA records when adding a custom domain.

## Actual Behavior

Zappa creates either a CNAME or Alias A record depending on whether the hostname is the apex of the Hosted Zone.
## Possible Fix

Make Alias A/AAAA records the standard for all kinds of hostnames.

## Steps to Reproduce
n/a

## Your Environment

* Zappa version used: 0.54.0

**Comment by javulticat** [comment]
Confusingly, `A`/`AAAA` records are "address" records, not "alias" records.  `CNAME` is the closet thing to an "alias" record in vanilla DNS.

But Route53 has a _custom_ "alias" concept which can apply to both types of records.  See: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html

This provides the benefits you listed, as well as the benefits of `CNAME` records (such as improved portability and geotargeting).

I think the best solution here would be to always make both types of records use a Route53 "alias".  I opened a PR for this here: #1079
