### ISSUE TITLE
Error returning a encoded sring of bytes on Zappa 0.54.1

### ISSUE THREAD

**Issue by MatheusDev20** [zappa/Zappa#1086]
Hello guys, hope y'all doing just fine

I'm trying to return a encode string of bytes from my lambda function and i'm getting the following error.

`"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 596, in handler\\n    zappa_returndict[\"body\"] = response.get_data(as_text=True)\\n', '  File \"/var/task/werkzeug/wrappers/response.py\", line 313, in get_data\\n    return rv.decode(self.charset)\\n', \"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\\n\"]}"`

i was able to return this content just fine using **zappa=0.50.0** version, but i had to update due the [aws state changes](https://github.com/zappa/Zappa/issues/1058l) #1058

is there some workaround that can be made to make this work on my current version **(0.54.1**)

**Comment by monkut** [comment]
Seems like a potential coding issue, closing.
