### ISSUE TITLE
Error in zappa tail - Unable to import module 'handler': No module named 'dataclasses'

### ISSUE THREAD

**Issue by synergiator** [zappa/Zappa#1087]
## Context
Redeploying existing app with Python 3.8 / 3.9 produces error seen in zappa tail:

```
Unable to import module 'handler': No module named 'dataclasses'
```
No reference to "handler"/"dataclasses" found in my code.

## Expected Behavior

Should not be there
## Actual Behavior

The error above
## Your Environment

* Zappa version used: latest
* Operating System and Python version: Python 3.8/3.9, Ubuntu Linux 20.04.
* The output of `pip freeze`:
```
aniso8601==9.0.1
argcomplete==1.12.3
boto3==1.20.14
botocore==1.23.14
certifi==2021.10.8
cfn-flip==1.3.0
charset-normalizer==2.0.8
click==8.0.3
durationpy==0.5
Flask==2.0.2
Flask-RESTful==0.3.9
future==0.18.2
hjson==3.0.2
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
jmespath==0.10.0
kappa==0.6.0
MarkupSafe==2.0.1
pep517==0.12.0
pip-tools==6.4.0
placebo==0.10.0
python-dateutil==2.8.2
python-dotenv==0.19.2
python-slugify==5.0.2
pytz==2021.3
PyYAML==6.0
requests==2.26.0
s3transfer==0.5.0
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tomli==1.2.2
tqdm==4.62.3
troposphere==3.1.1
urllib3==1.26.7
Werkzeug==2.0.2
wsgi-request-logger==0.4.6
zappa==0.54.1
```

**Comment by jeanlandim** [comment]
Same here.

**Comment by monkut** [comment]
The latest 0.55.0 release does not import dataclasses anywhere in the code.

Closing, if this reoccurs in 0.55.0, please open a new issue.
