### ISSUE TITLE
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code. When zappa deployed dev.

### ISSUE THREAD

**Issue by ma-okuda** [zappa/Zappa#1089]
## Context
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code. When zappa deployed dev.

Could not get a valid link such as https://**********.execute-api.us-west-2.amazonaws.com/dev, because of this issue.

$ python3 -m venv venv
$ source venv/bin/activate
(venv) % python --version
(venv) % 
Python 3.8.9

## Expected Behavior
Deployment complete!: https://**********.execute-api.us-west-2.amazonaws.com/dev

## Actual Behavior
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

## Steps to Reproduce
1. (venv) % pip install zappa
2. (venv) % zappa init
3. (venv) % dev
4. (venv) % default
5. (venv) % zappa-*********
6. (venv) % app.app
7. (venv) % n
8. (venv) % y
9. (venv) % zappa deploy dev

## Your Environment
* Zappa version used: 0.54.1
* Operating System and Python version: MacOS Monterey version 12.0.1, Python 3.8.9
* The output of `pip freeze`:
```
anyio==3.3.4
argcomplete==1.9.2
asgiref==3.4.1
async-generator==1.10
attrs==21.2.0
aws-wsgi==0.2.7
awscli==1.22.18
backports.entry-points-selectable==1.1.1
base58==0.2.4
beautifulsoup4==4.10.0
boto3==1.20.18
botocore==1.23.18
certifi==2021.10.8
cffi==1.15.0
cfn-flip==1.0.4
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.3
cryptography==35.0.0
distlib==0.3.3
docutils==0.15.2
dominate==2.6.0
durationpy==0.5
filelock==3.4.0
Flask==2.0.2
Flask-Bootstrap==3.3.7.1
Flask-JWT==0.3.2
Flask-SQLAlchemy==2.5.1
future==0.16.0
greenlet==1.1.2
h11==0.12.0
hjson==3.0.1
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.2
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
lambda-uploader==1.3.0
MarkupSafe==2.0.1
outcome==1.1.0
pep517==0.12.0
pip-tools==6.4.0
pipdeptree==2.2.0
pipenv==2021.11.15
placebo==0.10.0
platformdirs==2.4.0
pyasn1==0.4.8
pycparser==2.21
pydantic==1.8.2
PyJWT==1.4.2
pyOpenSSL==21.0.0
python-dateutil==2.6.1
python-lambda-local==0.1.12
python-slugify==1.2.4
pytz==2021.3
PyYAML==3.12
requests==2.26.0
rsa==4.7.2
s3transfer==0.5.0
selenium==4.0.0
six @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-103/six-1.15.0-py2.py3-none-any.whl
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3
SQLAlchemy==1.4.27
starlette==0.16.0
text-unidecode==1.3
toml==0.10.2
tomli==1.2.2
tqdm==4.19.1
trio==0.19.0
trio-websocket==0.9.2
troposphere==3.1.1
typing_extensions==4.0.0
Unidecode==1.3.2
urllib3==1.26.7
virtualenv==20.10.0
virtualenv-clone==0.5.7
visitor==0.1.3
Werkzeug==2.0.2
wsgi-request-logger==0.4.6
wsproto==1.0.0
zappa==0.54.1
```

* Link to your project (optional):
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "***************",
        "runtime": "python3.8",
        "s3_bucket": "zappa-*********"
    }
}
```

**Comment by dickermoshe** [comment]
Do you have ``
` ImproperlyConfigured: SQLite 3.9.0 or later is required (found 3.7.17).`
In your logs ?
I'm having this same issue

**Comment by ma-okuda** [comment]
SQLite is not included in this package.
It does not mention SQLite in my log.
After changing the authorized method of the API Gateway to AWS IAM, the deploymentwas successful.
However even if I send a get request that encodes the accessKey and secretKey, the connection fails.

**Comment by rjschave** [comment]
Werkzeug > 2.0 does not seem to work with AWS Lambda.

If this version is required by Flask 2.0, you may need to downgrade your Flask version.

I'm getting the error described in #1087 because a fresh install of Zappa installs Werkzeug==2.0.2.  Downgrading to Werkzeug==1.0.1 resolves my issue.

**Comment by ma-okuda** [comment]
Happy new year!
Thanks rjschave for your reply.
For this project, My company decided to use Amazon EC2 instead of AWS Lambda.
Anyway The next time we use AWS Lambda, will downgrade Werkzeug.

**Comment by duhaime** [comment]
hi all, can someone drop the requirements.txt file of a minimal zappa app? 

What are the Flask, jinja2, markupsafe, and werkzeug versions that won't throw a 502?

**Comment by duhaime** [comment]
I was able to get an update booted with:

```
argcomplete==2.0.0
boto3==1.25.4
botocore==1.28.4
certifi==2022.9.24
cfn-flip==1.3.0
charset-normalizer==2.1.1
click==8.1.3
durationpy==0.5
Flask==2.2.2
hjson==3.1.0
idna==3.4
importlib-metadata==5.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
kappa==0.6.0
MarkupSafe==2.1.1
placebo==0.9.0
python-dateutil==2.8.2
python-slugify==6.1.2
PyYAML==6.0
requests==2.28.1
s3transfer==0.6.0
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.64.1
troposphere==4.1.0
urllib3==1.26.12
Werkzeug==2.2.2
wsgi-request-logger==0.4.6
zappa==0.55.0
zipp==3.10.0
```

**Comment by ma-okuda** [comment]
hi duhaime,
We do no longer use zappa in our projects. But thanks for solving this issue.

**Comment by radmanon** [comment]
You should go to settings.py then make the DATABASES settings off by commenting(#).
then update it on console with command: zappa update dev

**Comment by radmanon** [comment]
You should go to settings.py then make the DATABASES settings off by commenting(#).
then update it on console with command: zappa update dev
I just commented for dickermoshe.
