### ISSUE TITLE
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

### ISSUE THREAD

**Issue by mathsmtnx** [zappa/Zappa#1094]
## Context
When im trying to deploy using _zappa update dev_ im getting this error:

Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

## Expected Behavior
Could not get a valid link such as https://**********.execute-api.us-west-2.amazonaws.com/dev such as this

## Actual Behavior
`{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):', ' File /var/task/handler.py, line 540, in handler with Response.from_app(self.wsgi_app, environ) as response:', ' File /var/task/werkzeug/wrappers/base_response.py, line 287, in from_app return cls(*_run_wsgi_app(app, environ, buffered))', ' File /var/task/werkzeug/wrappers/base_response.py, line 26, in _run_wsgi_app return _run_wsgi_app(*args)', ' File /var/task/werkzeug/test.py, line 1119, in run_wsgi_app app_rv = app(environ, start_response)', TypeError: 'NoneType' object is not callable]}`

when im trying to access any endpoint from my application

## Your Environment

* Zappa 0.54.1
* Python version 3.7
* Zappa settings
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "***************",
        "runtime": "python3.7",
        "s3_bucket": "zappa-*********"
    }
}

**Comment by kulor** [comment]
@mathsmtnx what spits out your logs if you run `zappa tail dev --since 5m` (shortly after a failed deployment)?

**Comment by mathsmtnx** [comment]
Hello @kulor, thanks for the answer.
i was getting the following error
[1612507108211] Instancing..
[1612507108215] Failed to find library: libmysqlclient.so.18 ...right filename?

and thats weird cause i was able to deploy my flask app with the same virtual enviroment a couple days before facing this error.

**Comment by kulor** [comment]
@mathsmtnx  I faced similar issues with MySQL as I don't think the lib is bundled in the image any longer. I reluctantly resorted to using pymysql.

Switchover from `libmysqlclient` was fairly easy. Install `pip install pymysql` and add this to your `appname/__init__.py`:

```
import pymysql
pymysql.install_as_MySQLdb()
```

Let me know if this works as I have fought my fair share of MySQL related Zappa issues?

**Comment by dickermoshe** [comment]
Please close this issue as this is not something the Zappa Team can solve.
You're sadly limited to the binaries included on AWS Lambda.

**Comment by monkut** [comment]
closing issue.
