### ISSUE TITLE
[Suggestion] enable the discussions feature on github.

### ISSUE THREAD

**Issue by xncbf** [zappa/Zappa#1107]
The number of issues is too high and it is difficult to distinguish the real issue from the question. Enabling the discussions feature will help you categorize issues.

**Comment by VaZark** [comment]
I'd like to second this request. As someone who just discovered this library, I have a few questions on how to use it but raising an _Issue_ feels like polluting the tab. Moreover, discussions can be converted to issues.

**Comment by monkut** [comment]
Some new core members have just joined the project, and we're working through cleaning up the project.
At the moment for features or problems please continue to open and issue.

We may eventually move to discussions, but we don't have the bandwidth to manage that at the moment.

closing.
