### ISSUE TITLE
504 -> 302s - coping with Api Gateway Integration timeouts

### ISSUE THREAD

**Issue by leunga1000** [zappa/Zappa#1114]
## Context
Api Gateway integration times out after 29s. The Lambda executes in the background but is unable to convey the information back to the client.

## Expected Behaviour
Return result from Lambda however long it takes.

## Actual Behaviour
504 Via API Gateway (ALB can take as long as it likes, but currently has a 1MB payload limit)

## Possible Fix
API Gateway - Integration Responses - Detect the 502 (or 503, or 504) and turn this into a Redirect with the Request-Id returned to the client using troposphere.

handler() already works out how long the request has taken, so if this is longer than the API Gateway limit, and the config flag for this functionality is turned on, persist the data (e.g. to DynamoDB like the @task functionality), along with a specific header from the request (e.g. bearer-token), again configurable, which can be used to authenticate the subsequent fetch request. The Lambda completes, but in the meantime API Gateway has 50*'d to the client.

This 50* is converted to a 302 to the client, which duly redirects to another Zappa call. This may need to intercept a specific endpoint. Zappa looks for a response in DynamoDB (and authenticates if necessary) and returns if a result is present or delays/redirects, similar to the async task documentation. 

There probably needs to be a limit to how many times this can run. The lambda itself may also timeout.

Thoughts? Having all calls take under 30s is good practice but it may smooth the migration path for existing apps. I'm sure there's probably things I've missed.

**Comment by souravjamwal77** [comment]
Hi @leunga1000 You can use async decorator and invoke a seperate lambda by supplying the lambda name and region name. OR you can refer to this post by @scoates which explains a workaround api gateway timeout.

**Comment by leunga1000** [comment]
Thanks @souravjamwal77 , the post here: https://webadvent.org/blogs/api-gateway-timeout-workaround/ 

Yes this feature would be based heavily on that work, thanks @scoates! API Gateway can automatically turn 504s into redirects, with request-specific header information. So it wouldn't need to be a per-endpoint, per-application fix, no need for polling, and the site would function more or less as it would have before.

**Comment by scoates** [comment]
May I ask how you got that URL, @leunga1000? Old server config seems to be messed up there. (I see what's happening; I'm just curious where that's published like that.)

For others joining this thread, old post here: https://seancoates.com/blogs/api-gateway-timeout-workaround

**Comment by leunga1000** [comment]
Hey @scoates, it's the top result when doing a search for "sean coates api gateway workaround". The main blog's a good read, thank you

**Comment by leunga1000** [comment]
There's no need for this if Zappa can move to Function URLs, closing. #1121
