### ISSUE TITLE
Zappa Project Logo

### ISSUE THREAD

**Issue by jottenlips** [zappa/Zappa#1116]
Not a feature request, more of a proposal. I found a cool free font you could use for the organization's logo. 

![image](https://user-images.githubusercontent.com/14910912/158688907-b15f3d59-6f7a-46a5-bb36-b71dcd8ee492.png)
https://www.fontspace.com/thunder-titan-font-f32963

I have really enjoyed working with Zappa and I think this would look nice 😊

**Comment by benminer** [comment]
+1

**Comment by souravjamwal77** [comment]
+1

**Comment by jottenlips** [comment]
Happy to customize further or open a PR to change it over. Also, does anyone know how to get into the Zappa slack?

**Comment by souravjamwal77** [comment]
Hi @jottenlips you can use this link https://slackautoinviter.herokuapp.com/

**Comment by monkut** [comment]
Bring this to slack, or create a PR to move this a long.
Not a major priority.

Closing.
