### ISSUE TITLE
Unable to schedule SQS Batch Size of greater than 10

### ISSUE THREAD

**Issue by brucebeck95** [zappa/Zappa#1117]
## Context
Attempting to create an SQS trigger, through Zappa, that takes in 100 messages at a time.

## Expected Behavior
Should be able to add "batch_window" param to zappa_setting.json event and have it schedule.
Should schedule the trigger on SQS successfully.

## Actual Behavior
```botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: Maximum batch window in seconds must be greater than 0 if maximum batch size is greater than 10```

## Possible Fix
Allow zappa to take in a batch_window argument.

## Steps to Reproduce
Add to zappa_settings.json

"function": "function_name",
"event_source": {
             "arn":  "arn:aws:sqs:eu-central-1:180611847606:queue-name",
             "batch_size": 100,
             "functionResponseType": "ReportBatchItemFailures",
             "enabled": true
}

## Your Environment

* Zappa version used: 0.54.1
* Operating System and Python version: WSL2 20.04 and Python3.8

**Comment by monkut** [comment]
released in 0.56.0, closing.
