### ISSUE TITLE
support new ephemeral storage feature in zappa_settings.json

### ISSUE THREAD

**Issue by elip-OE** [zappa/Zappa#1120]
## Context
Few days ago AWS released new feature to support `/tmp` storage up to 10GB [link](https://aws.amazon.com/blogs/compute/using-larger-ephemeral-storage-for-aws-lambda/)
I wish there whould be an option to set it as part of the `zappa_settings.json` file

## Expected Behavior
```
{
    "stage": {
        ...
        "ephemeral_storage": 10240  # MBs
    }
}
```
would set my function to 10GB storage on `/tmp`

## Actual Behavior
N/A

## Possible Fix
N/A

## Steps to Reproduce
N/A

## Your Environment
N/A

**Comment by mdw123** [comment]
👍🏻

**Comment by souravjamwal77** [comment]
Hi @elip-OE and @mdw123,
 Does this setting work?

**Comment by souravjamwal77** [comment]
Thanks @mdw123 for your suggestion
However, I started using Docker for the same and it's better than using ephemeral storage.
If you want any help feel free to ping me

**Comment by elip-OE** [comment]
@souravjamwal77 docker image may not be an option. I've tested PR #1125 and it works fine.

**Comment by souravjamwal77** [comment]
Thanks @elip-OE
I will test that out and will ping @jneves for merging.

**Comment by elip-OE** [comment]
@souravjamwal77 can you share you docker based solution?

**Comment by souravjamwal77** [comment]
Yeah sure below is my Dockerfile code 
let me know if you need anything else

```
FROM amazon/aws-lambda-python:3.8




ARG FUNCTION_DIR="/var/task/"

COPY ./ ${FUNCTION_DIR}

RUN pip install wheel
RUN pip install -r requirements.txt

# Grab the zappa handler.py and put it in the working directory
RUN ZAPPA_HANDLER_PATH=$( \
    python -c "from zappa import handler; print (handler.__file__)" \
    ) \
    && echo $ZAPPA_HANDLER_PATH \
    && cp $ZAPPA_HANDLER_PATH ${FUNCTION_DIR}


CMD [ "handler.lambda_handler" ]
```

**Comment by elip-OE** [comment]
@souravjamwal77 thanks for your help. I have very similar Dockerfile, but I don't have a write permission to any directory. have you done anything to allow more storage?

**Comment by issamemari** [comment]
I'm interested in this feature

**Comment by souravjamwal77** [comment]
> @souravjamwal77 thanks for your help. I have very similar Dockerfile, but I don't have a write permission to any directory. have you done anything to allow more storage?

This issue has been marked as nest-release-candidate and will be added in the next release.
