### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by spirovskib** [zappa/Zappa#1122]
## Context
I want to ingest the zappa logs into an external log management service for easier debugging.
## Questions
1. where does Zappa store the logs it reads when we use `zappa tail`?
2. Any examples of transferring those logs into an external logging system - even Cloud Watch, but ideally an ELK instance.
3. How do I flush/empty the logs that are stored by zappa (so I don't get into compliance problems)

**Comment by monkut** [comment]
function logs should be logged to cloudwatch, you can get the logs from there using the cloudwatch logs api.

**Comment by monkut** [comment]
closing.
