### ISSUE TITLE
Stage name not allowing '-' character in zappa_settings.json

### ISSUE THREAD

**Issue by sridhar562345** [zappa/Zappa#1126]
Is there any specific reason for that? API gateways allows `-` character in stage name but the zappa regex does not allow this.

Any specific reason the regex is not updated yet?

**Comment by monkut** [comment]
The code seems to suggest that there was at some point a restriction on the stageName when createDeployment was run.
AWS may have removed the restriction now, but the expectation that a _stage name_ does not contain "-" may be used elsewhere in zappa's code.  

> stage_name_env_pattern = re.compile("^[a-zA-Z0-9_]+$")

https://github.com/zappa/Zappa/blob/master/zappa/cli.py#L1614-L1626

What is the error you are getting?
