### ISSUE TITLE
Handle optional space in x-forwarded-for header

### ISSUE THREAD

**Issue by naresh-uplight** [zappa/Zappa#1127]
https://github.com/zappa/Zappa/blob/a1e842cf95e5bd99a84e89d5eaaed42ff82f57eb/zappa/wsgi.py#L105

As per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax) the whitespace is optional and I have a case where the request errors because of that.

**Comment by monkut** [comment]
handled in pr #1127 closing.

**Comment by monkut** [comment]
released in 0.56.0, closing.
