### ISSUE TITLE
API response not given before calling call_on_close function

### ISSUE THREAD

**Issue by carlos-schwabe** [zappa/Zappa#1133]
I am using a @call_on_close() decorator to invoke an assyncronous job, since the gateway timeout is now enough for my job to execute, however it is not sending the API response before calling the function
## Context
I have the code as writen bellow

@blueprint_protests_pj.route('/protests', methods=['POST'])
def protests_pj():
<assign some request context to some variables here>
     @response.call_on_close
    def on_close():
        #Here we execute the job and log it in the database. No return is given
      
    return jsonigy ({'message':"Job Created"}), 201 # return a job created message

## Expected Behavior
On local machine, Flask returns the "Job created"message and then calls the on_close function, which is what it should do, according to the docs

## Actual Behavior
On zappa deployment, the api only returns the job created message after executing the on_close function

## Steps to Reproduce
- deploy any zappa api with an call _on_close decorator and compare executions locally and on aws

## Your Environment

* Zappa version used: 0.54.1
* Operating System and Python version: Python 3.8.13 on Mac OS Monterey
* The output of `pip freeze`:
* apispec==5.2.1
apispec-webframeworks==0.5.2
argcomplete==2.0.0
boto3==1.22.7
botocore==1.25.7
certifi==2021.10.8
cfn-flip==1.3.0
charset-normalizer==2.0.12
click==8.1.3
durationpy==0.5
Flask==2.1.2
flask-swagger-ui==3.36.0
future==0.18.2
hjson==3.0.2
idna==3.3
importlib-metadata==4.11.3
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.0
kappa==0.6.0
lxml==4.8.0
MarkupSafe==2.1.1
marshmallow==3.15.0
numpy==1.22.3
packaging==21.3
pandas==1.4.2
placebo==0.9.0
psycopg2-binary==2.9.3
pyparsing==3.0.8
python-dateutil==2.8.2
python-slugify==6.1.2
pytz==2022.1
PyYAML==6.0
requests==2.27.1
s3transfer==0.5.2
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.64.0
troposphere==4.0.1
urllib3==1.26.9
Werkzeug==2.1.2
wsgi-request-logger==0.4.6
zappa==0.54.1
zipp==3.8.0
* Your `zappa_settings.json`: 
    "dev": {
        "app_function": "entrypoint.app",
        "profile_name": null,
        "project_name": "--",
        "runtime": "python3.8",
        "s3_bucket": "--",
		"api_key_required":false,
		"timeout_seconds":150
    },
	"prod": {
        "app_function": "entrypoint.app",
        "profile_name": null,
        "project_name": "c--",
        "runtime": "python3.8",
        "s3_bucket": "--",
		"api_key_required":false,
		"timeout_seconds":150
	}

**Comment by thommor** [comment]
You can't call async functions in this way with Lambda, as Lambda was invoked by APIGW it terminates when the response is sent.

Take a look at the docs for asynchronous task executions: https://github.com/zappa/Zappa#asynchronous-task-execution
