### ISSUE TITLE
digitalocean function support

### ISSUE THREAD

**Issue by aurelpere** [zappa/Zappa#1134]
Hi,
I discovered digitalocean recently launched function, which is similar to aws lambda. 
I would be thrilled to use this instead of aws lambda, but i didnt find the support with zappa...
(I need this for a django website).
Is there any project to support digitalocean in zappa soon? 
thank you

**Comment by monkut** [comment]
Zappa is currently strongly integrated with aws lambda, I don't see other services being supported in the near future.
