### ISSUE TITLE
Update front page docs to include Python 3.9 support

### ISSUE THREAD

**Issue by nicholashughes** [zappa/Zappa#1137]
## Context
It appears Zappa supports [supports 3.9](https://github.com/zappa/Zappa/pull/1026) but front page doesn't mention that. This made me think twice about using this wonderful framework. Maybe I am wrong?

Also, when filing this Issue there is this statement in the issue generator itself:
"<!- Also, please make sure that you are running Zappa _from a virtual environment_ and are using Python 3.6/3.7/3.8  >"
and maybe that should include 3.9 as well.

## Expected Behavior
The front page docs should include `Python 3.6/3.7/3.8/3.9`

## Actual Behavior
The front page docs mention `Python 3.6/3.7/3.8/` but it looks like Zappa [supports 3.9](https://github.com/zappa/Zappa/pull/1026)

## Possible Fix
Change this sentence
`Before you begin, make sure you are running Python 3.6/3.7/3.8`
to
`Before you begin, make sure you are running Python 3.6/3.7/3.8/3.9`
as it now looks like Zappa [supports 3.9](https://github.com/zappa/Zappa/pull/1026)

**Comment by thommor** [comment]
This has now been resolved
