### ISSUE TITLE
template for azure-pipelines.yml 

### ISSUE THREAD

**Issue by thespamer** [zappa/Zappa#1139]
Hi all... I need some template for azure devops pipeline for AWS Lambda backend.

zappa==0.54.1, python 3.x with django, linux docker and my zappa_settings.json:

{
    "dev": {
        "aws_region": "eu-west-1",
        "django_settings": "core.settings",
        "profile_name": "dev_deploy",
        "project_name": "dialog-iot-api",
        "runtime": "python3.8",
        "s3_bucket": "dialog-api-dev-zappa"
    },

    "qa": {
        "aws_region": "eu-west-1",
        "django_settings": "core.settings",
        "profile_name": "qa_deploy",
        "project_name": "dialog-iot-api",
        "runtime": "python3.8",
        "s3_bucket": "dialog-api-test-zappa"
    }    
}

Thank you!
Juliano

**Comment by monkut** [comment]
Not sure what you're asking for here.
Are you looking for an example?

**Comment by monkut** [comment]
no response closing.
