### ISSUE TITLE
Words missing in Zappa init dialog

### ISSUE THREAD

**Issue by james-sullivan** [zappa/Zappa#1141]
## Context

I'm trying to setup zappa with an existing flask project. Python version is 3.8 and I am using a venv

## Expected Behavior

There should not be missing words in the zappa init dialog.

## Actual Behavior

There are missing words in the zappa init dialog. It looks like they are variables?

![image](https://user-images.githubusercontent.com/5818514/177441548-08d1d395-59da-4c3d-8799-98dab9be45a6.png)
![image](https://user-images.githubusercontent.com/5818514/177441740-01b292ab-c3b7-4026-bfab-122edbd7ca2e.png)

## Steps to Reproduce

1. Create a new Flask app
2. Run pip install zappa
3. Run zappa init

## Your Environment

* Zappa version used: 0.54.1
* Operating System and Python version: Windows 11 Python 3.8
* The output of `pip freeze`: N/A
* Link to your project (optional): N/A
* Your `zappa_settings.json`: N/A

**Comment by monkut** [comment]
It appears that you're using a black text on white background setting in your terminal.
Zappa uses color in the text and I suspect this is due to the text being 'white'.
