### ISSUE TITLE
Duration has increased between master and 0.54.2

### ISSUE THREAD

**Issue by xncbf** [zappa/Zappa#1157]
I changed it to the following yesterday

<img width="710" alt="image" src="https://user-images.githubusercontent.com/9462045/182116154-f38935f1-045e-454b-b42c-3e5d49382ffd.png">

Duration has increased.
No other code modifications.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/9462045/182115992-9ca2a4e4-3c30-40dd-8b8d-e35ad76fa7c7.png">

Previous Last release date is 7/24, one week ago

**Comment by xncbf** [comment]
I think it has something to do with this commit.

https://github.com/zappa/Zappa/commit/fff5ed8ad2ee071896a94133909adf220a8e47d9

**Comment by xncbf** [comment]
When I reverted to the previous commit (https://github.com/zappa/Zappa/commit/a1e842cf95e5bd99a84e89d5eaaed42ff82f57eb), it was back to normal.

**Comment by monkut** [comment]
If you want to compare you should compare to 0.54.1 and not master.
Master is for on going development.

0.55.0 was just released, that will be pretty much master. (depending on when you updated last)
