### ISSUE TITLE
Remove obsolete check for Django version < 1.7

### ISSUE THREAD

**Issue by carlkibler** [zappa/Zappa#1158]
There is a check for Django version being < 1.7, which triggers a now-unnecessary call to `django.setup()` 

## Context
Zappa supports Python 3.7-3.9 and Django only supports Python of 3.5 or greater since version 2.2. So anyway, can remove this check.

## Expected Behavior
No behavior changes, though Django<1.7 will no longer work, if it did in any case. 

## Actual Behavior
No change

## Possible Fix
Remove code

**Comment by monkut** [comment]
Yes, considering Django 1.7 is no longer supported by django I think it's fair to remove this unnecessary code.

**Comment by monkut** [comment]
released in 0.56.0, closing.
