### ISSUE TITLE
Stale code present in wsgi.py / HTTP API support

### ISSUE THREAD

**Issue by sridhar562345** [zappa/Zappa#1168]
https://github.com/zappa/Zappa/blob/882a4cd53f328ced9a1bc8c41e41408886d0fbe3/zappa/wsgi.py#L145-L146

As seen above, the value is not updated or assigned.

I was trying to test out API gateway HTTP APIs manually and modifying the line like below is working for HTTP APIs

```py
if path_info.startswith(script_name): 
     environ["PATH_INFO"] = environ["PATH_INFO"].replace(script_name, "", 1) 
```

I am also mentioning the request formats of REST and HTTP version 1 below for calling the same path, there are some differences

### Rest request format
```json
{
    "resource": "/",
    "path": "/",
    "httpMethod": "GET"
}
```

### HTTP request format
```json
{
    "version": "1.0",
    "resource": "/",
    "path": "/alpha/",
    "httpMethod": "GET"
}
```

If I am missing something, let me know.

**Comment by monkut** [comment]
Yes, it looks like the intention is to update the PATH_INFO in environ, but the updated value is not applied.

**Comment by sridhar562345** [comment]
@monkut do you want me to post a PR for this? 

Is there anything else to verify about this or the details I don't know?

**Comment by monkut** [comment]
Yes, if you can that would be great.  I don't think we have testcases in place for this so I'd like to get it covered.

What is your path and script_name in the case where this is an issue for you?

**Comment by sridhar562345** [comment]
@monkut 

So, I am trying to use HTTP API gateway manually instead of the default rest API created by Zappa. 


The HTTP API has some differences in the event format as you can see below. For example, when I invoke Rest API for the alpha stage it doesn't include the stage name in `path` but HTTP API does append the stage name at the start.

### Rest request format
```json
{
    "resource": "/",
    "path": "/",
    "httpMethod": "GET"
}
```

### HTTP request format
```json
{
    "version": "1.0",
    "resource": "/",
    "path": "/alpha/",
    "httpMethod": "GET"
}
```

**Comment by monkut** [comment]
Yes, I believe that the infrastructure stage created by zappa in the API Gateway will include the stage name as well, so this needs to be included here.

Is there a problem with including the stage name when you manually create the APIGW path?

**Comment by sridhar562345** [comment]
@monkut
 
Yes, the problem exists only for HTTP API deployments. There isn't any problem with actual REST API deployments.

When using HTTP API, the stage name will be included twice since the path already has stage name in it.

The issue is reproducible, try to attach HTTP API instead of REST API.
