### ISSUE TITLE
Cache installed deps?

### ISSUE THREAD

**Issue by maramizo** [zappa/Zappa#1170]
[Zappa downloads dependencies from manywheels and stores them... somewhere](https://github.com/zappa/Zappa/blob/19f61daacf01cce27929e9912e2066bbe5f81681/zappa/core.py#L909). How do we cache these dependencies on environments like CodeBuild to speed up deployment? I noticed that Zappa caches this locally, but since I'm assuming it doesn't use pip under the hood, pip doesn't cache them, and since pip doesn't cache them, they're not in /root/.cache/pip/ which is the CodeBuild cache dir. So, how does one go about caching these dependencies? Where are they installed?

**Comment by sridhar562345** [comment]
@maramizo they are downloaded in `/tmp/cached_wheels` and package details info is stored in `/tmp/cached_pypi_info`
