### ISSUE TITLE
Is it posible set a resource-based policy?

### ISSUE THREAD

**Issue by xncbf** [zappa/Zappa#1171]
I want to run an asynchronous task created in zappa in another lambda function.

<img width="1351" alt="스크린샷 2022-09-06 오전 10 36 51" src="https://user-images.githubusercontent.com/9462045/188528857-6fcc8250-f78a-4ef9-bf1d-f56f9aea57ff.png">

I can actually run it if I modify it as follows, but after zappa update, it returns to the original state.

Is it posible set a resource-based policy on zappa_settings.json or others?

**Comment by monkut** [comment]
So you want to call an async task defined in a zappa deployed lambda function from another function?

**Comment by xncbf** [comment]
yes

**Comment by xncbf** [comment]
example

zappa deployed lambda function 1 
```
from zappa.asynchronous import task

@task
def function1(data):
    print(data)
```

No zappa deployed lambda function 2
```
def function2():
    payload = {
        "command": "zappa.asynchronous.route_lambda_task",
        "task_path": "core.tasks.function1",
        "args": [],
        "kwargs": {
            "data": "DONE"
        },
    }
    client = boto3.client("lambda", region_name="ap-northeast-2")
    client.invoke(
        FunctionName="arn:aws:lambda:ap-northeast-2:494890851710:function:zappa-prod",
        InvocationType="Event",
        LogType="Tail",
        Payload=json.dumps(payload),
    )
```

**Comment by monkut** [comment]
You can give permissions to your `No zappa deployed lambda function 2` to execute the `zappa deployed lambda function 1`.

zappa has "extra_permissions" and "attach_policy" if you want to apply additional permissions to the zappa deployed lambda function.  So you may be able to write a resource-based policy document and apply it to your zappa deployed lambda function with the `attach_policy` configuration option.
