### ISSUE TITLE
Dependence with troposphere is broken

### ISSUE THREAD

**Issue by Uiuran** [zappa/Zappa#1172]
## Steps to Reproduce

1. pip install zappa==0.53.0
2. zappa deploy project

## Your Environment

* Zappa version used: 0.53.0
* Operating System and Python version: 3.8.0

Zappa is installing troposphere 4.1.0
but it returns an error of object Template being deprecated,

The solution is downgrading by hand troposphere version to 2.7.1

But this is annoying and this also breaks poetry envs by another reason inside poetry that shouldn't break. However clearly the problem is with Zappa not using clearly the right version of dependencies in its build.

Please fix this asap ... thank you.

**Comment by monkut** [comment]
Can you share the error message?

**Comment by sridhar562345** [comment]
#1016 

is this the issue you are facing @Uiuran? it's resolved in the latest version of Zappa.

**Comment by monkut** [comment]
Assuming problem is resolved in 0.55.0, closing.
