### ISSUE TITLE
Zappa certify not working. Incompatible ACME endpoints

### ISSUE THREAD

**Issue by dfleuriot** [zappa/Zappa#1173]
ACME v2 API no longer has `acme/new-reg` and `acme/new-authz` endpoints. Error 404 is being returned!
## Context
I followed the [guide](https://github.com/zappa/Zappa/blob/master/docs/domain_with_free_ssl_dns.md) to associate a Let's Encrypt SSL certificate and validating it using DNS validation but I keep getting 404 errors when registering.

The following functions 
`register_account()` 
https://github.com/zappa/Zappa/blob/bef5c5ae9f3551a4c2e0acfcc43f4a65906e8a61/zappa/letsencrypt.py#L230-L236
and 
`get_cert(...)`
https://github.com/zappa/Zappa/blob/bef5c5ae9f3551a4c2e0acfcc43f4a65906e8a61/zappa/letsencrypt.py#L265-L271

 make calls to two endpoints that are no longer compatible ([Reference](https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605)) and are therefore returning 404 errors and the process fails.

https://acme-v02.api.letsencrypt.org/directory shows what are the endpoints and neither `new-reg` nor `new-authz` are there.

## Expected Behavior
`zappa certify` should complete without errors and successfully certify the SSL certificate.

## Actual Behavior
When running `zappa certify`, the following error keeps popping up:
```
Error registering: 404 b'404 page not found\n'
Failed to generate or install certificate! :(`
```

## Possible Fix
Update [letsencrypt.py](https://github.com/zappa/Zappa/blob/master/zappa/letsencrypt.py) to use the correct ACME v2 endpoints. Possibly with the updates from [acme-tiny ](https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py)

## Steps to Reproduce

run `zappa certify`

## Your Environment

* Zappa version used: 0.55.0
* Operating System and Python version: Win 11 / Python 3.8.10
* The output of `pip freeze`:
```
argcomplete==1.12.3
boto3==1.18.11
botocore==1.21.11
certifi==2020.6.20
cffi==1.14.6
cfn-flip==1.2.3
charset-normalizer==2.0.4
click==8.0.1
colorama==0.4.4
ConfigArgParse==1.5.1
durationpy==0.5
Flask==2.2.2
Flask-BasicAuth==0.2.0
Flask-Caching==1.10.1
Flask-Cors==3.0.10
Flask-JWT-Extended==4.4.4
Flask-SQLAlchemy==2.5.1
future==0.18.2
gevent==21.1.2
geventhttpclient==1.4.4
greenlet==1.1.0
hjson==3.0.2
idna==3.2
importlib-metadata==4.12.0
itsdangerous==2.0.1
Jinja2==3.0.1
jmespath==0.10.0
kappa==0.6.0
locust==1.2.2
MarkupSafe==2.1.1
msgpack==1.0.2
pep517==0.11.0
pip-tools==6.2.0
placebo==0.9.0
psutil==5.8.0
pycparser==2.20
PyJWT==2.4.0
PyMySQL==1.0.2
python-dateutil==2.6.1
python-dotenv==0.19.0
python-slugify==5.0.2
pywin32==301
PyYAML==5.4.1
pyzmq==22.1.0
redis==3.5.3
requests==2.28.1
s3transfer==0.5.0
six==1.16.0
SQLAlchemy==1.4.22
swagger-ui-py==22.7.13
text-unidecode==1.3
toml==0.10.2
tomli==1.2.0
tqdm==4.62.0
troposphere==3.1.0
urllib3==1.26.6
Werkzeug==2.2.2
wincertstore==0.2
wsgi-request-logger==0.4.6
zappa==0.55.0
zipp==3.8.1
zope.event==4.5.0
zope.interface==5.4.0
```

**Comment by monkut** [comment]
Thanks for the notification, we'll look into support.
