### ISSUE TITLE
Is it possible to define the API Gateway you want to use in the zappa_settings.json file

### ISSUE THREAD

**Issue by Newlevel462** [zappa/Zappa#1174]
When deploying a Python Flask app to AWS Lambda using Zappa

I think you can already do this for your IAM role using "manage_roles", "role_name" and "role_arn" but would be good if you could do it for API Gateway as well, or define the API Gateway settings when you deploy

**Comment by monkut** [comment]
Please join the slack channel for questions

https://slackautoinviter.herokuapp.com

**Comment by monkut** [comment]
zappa expects to manage the stack when using zappa for deployment.

You can use zappa for packaging only and deploy the resulting package to an existing api gateway if desired.

**Comment by monkut** [comment]
inactive, closing
