### ISSUE TITLE
Error when deploying the app using zappa

### ISSUE THREAD

**Issue by dumitruPuggle** [zappa/Zappa#1175]
# Error botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetRestApi operation: Invalid API identifier specified 341536805644:qiozpnwvc3
## Context

I have no idea it started to crash at the final steps, earlier I had no issues related with deploying, now it started to crash. I think maybe it's because I aborted the deploying process while it was uploading due to my weak internet connection (because I'm in a different country at the moment)

I use venv and Python 3.9.
## Expected Behavior

Deploy the app and give me the link to the API Gateway where I can do all the requests to my lambda function
## Actual Behavior

It does deploy the function on AWS Lambda, but it doesn't work, it shows me this:
Traceback (most recent call last):
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/zappa/cli.py", line 3033, in handle
    sys.exit(cli.handle())
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/zappa/cli.py", line 517, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/zappa/cli.py", line 559, in dispatch_command
    self.deploy(self.vargs["zip"], self.vargs["docker_image_uri"])
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/zappa/cli.py", line 877, in deploy
    self.zappa.add_binary_support(api_id=api_id, cors=self.cors)
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/zappa/core.py", line 1954, in add_binary_support
    response = self.apigateway_client.get_rest_api(restApiId=api_id)
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dumitrucucu/Desktop/clients/Adrian Nicolaev/app/fluency-py/venv/lib/python3.9/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetRestApi operation: Invalid API identifier specified 341536805644:qiozpnwvc3

## Possible Fix

I have no idea how zappa works at a lower level, I suppose it uses some AWS Apis, and the error above demonstrates that there's some error when it tries to interact with the AWS Api on the final steps.
## Steps to Reproduce

1. zappa update dev

## Your Environment

* Zappa version used:
* 0.55.0
* Operating System and Python version:
* Mac OS Monterey 12.2 (21D49) and Python 3.9
* The output of `pip freeze`:
* aes==1.0.0
aniso8601==9.0.1
argcomplete==2.0.0
atomicwrites==1.4.1
attrs==22.1.0
boto3==1.24.59
botocore==1.27.59
CacheControl==0.12.10
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.1
cfn-flip==1.3.0
charset-normalizer==2.0.12
click==8.1.2
crypto==1.4.1
cryptocode==0.1
cryptography==38.0.1
Deprecated==1.2.13
dnspython==2.2.1
durationpy==0.5
email-validator==1.1.3
firebase-admin==5.2.0
Flask==2.0.2
Flask-Cors==3.0.10
Flask-JWT-Extended==4.3.1
Flask-RESTful==0.3.9
google-api-core==2.7.2
google-api-python-client==2.44.0
google-auth==2.6.5
google-auth-httplib2==0.1.0
google-cloud-core==2.3.0
google-cloud-firestore==2.4.0
google-cloud-storage==2.3.0
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos==1.56.0
grpcio==1.44.0
grpcio-status==1.44.0
hjson==3.1.0
httplib2==0.20.4
idna==3.3
iniconfig==1.1.1
itsdangerous==2.1.2
Jinja2==3.1.1
jmespath==1.0.1
kappa==0.6.0
MarkupSafe==2.1.1
more-itertools==8.14.0
msgpack==1.0.3
Naked==0.1.31
names==0.3.0
packaging==21.3
password-validator==1.0
placebo==0.9.0
pluggy==0.13.1
proto-plus==1.20.3
protobuf==3.20.0
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycrypto==2.6.1
pycryptodomex==3.14.1
pydash==5.1.0
PyJWT==2.3.0
pyparsing==3.0.8
pytest==4.6.11
pytest-requests==0.3.0
python-dateutil==2.8.2
python-dotenv==0.20.0
python-i18n==0.3.9
python-random-name-generator==0.0.6
python-slugify==6.1.2
pytz==2022.1
PyYAML==6.0
requests==2.27.1
rsa==4.8
s3transfer==0.6.0
shellescape==3.8.1
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tqdm==4.64.0
trafaret==2.1.1
troposphere==4.1.0
twilio==7.8.1
uritemplate==4.1.1
urllib3==1.26.9
vonage==3.0.0
wcwidth==0.2.5
Werkzeug==2.1.1
wrapt==1.14.1
wsgi-request-logger==0.4.6
zappa==0.55.0
* Link to your project (optional):
* - (private source)
* Your `zappa_settings.json`: 
{
    "dev": {
        "app_function": "app.app",
        "profile_name": "default",
        "project_name": "fluency-py",
        "runtime": "python3.9",
        "s3_bucket": "zappa-qms1bxy5b",
        "aws_region": "us-east-1"
    }
}

**Comment by dumitruPuggle** [comment]
Please any help will be highly appreciated! This task is time sensitive for me, and I already spent 2 days trying to figure out the problem, I've deleted everything from AWS Lambda, S3, API gateway, reinstalled zappa, and done an re init, maybe that's because I have some conflicting modules? Thanks

**Comment by sridhar562345** [comment]
@dumitruPuggle  delete cloudformattion stack and deployed lambda function manually and try to redeploy the function.

**Comment by dumitruPuggle** [comment]
Waiting for stack fluency-py-dev to create (this can take a bit)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:17<00:00,  4.30s/res]
Deploying API Gateway..
Waiting for lambda function [fluency-py-dev] to be updated...
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

**Comment by dumitruPuggle** [comment]
At least it didn't crash like it did before, but there is a new problem.

**Comment by dumitruPuggle** [comment]
<img width="1552" alt="Screenshot 2022-09-20 at 20 06 40" src="https://user-images.githubusercontent.com/46863241/191320953-239c8d5a-3847-4f36-8046-3632f51fd6b7.png">
<img width="1552" alt="Screenshot 2022-09-20 at 20 07 34" src="https://user-images.githubusercontent.com/46863241/191321048-bd8a9eac-b98b-40bd-832a-cf7efec22826.png">
zappa tail:
<img width="1552" alt="Screenshot 2022-09-20 at 20 09 06" src="https://user-images.githubusercontent.com/46863241/191321502-e7dc782b-a9cb-4396-bc56-8b6251f550b0.png">

**Comment by dumitruPuggle** [comment]
Okay, I get it. There's a problem with a conflicting module. Probably the cryptocode module was trying to connect with native OS bindings and stuff like that and eventually the lambda doesn't support that. A similar situation with Node.js bcrypt library.

**Comment by dumitruPuggle** [comment]
> Okay, I get it. There's a problem with a conflicting module. Probably the cryptocode module was trying to connect with native OS bindings and stuff like that and eventually the lambda doesn't support that. A similar situation with Node.js bcrypt library.

I will try to find an different module that does the same thing

**Comment by monkut** [comment]
Looks like a problem with the libraries used in your application.

Is it ok to close this issue?

**Comment by dumitruPuggle** [comment]
Here's one more strange thing. All these modules were working perfectly before with zappa. Suddenly, new bugs and errors started to appear. Right now, there's another conflicting module:
 ImportError: Failed to import the Cloud Firestore library for Python. Make sure to install the "google-cloud-firestore" module.

Again, all these modules were working perfectly earlier, and I was able to deploy them.

**Comment by dumitruPuggle** [comment]
Thanks for the help especially with Cloud Formation, I fixed my conflicting modules, now here's the result:
<img width="1419" alt="Screenshot 2022-09-21 at 09 16 54" src="https://user-images.githubusercontent.com/46863241/191428333-c6b704ce-656d-4544-aa29-4d9be6ca3ee3.png">

**Comment by dumitruPuggle** [comment]
Guys, is there an way to test the zappa locally?

**Comment by dumitruPuggle** [comment]
Thanks!
