### ISSUE TITLE
Deploying a Zappa project invoked using S3 events, reverts any EventBridge configuration for a given S3 bucket

### ISSUE THREAD

**Issue by Sam152** [zappa/Zappa#1176]
## Context

* I've deployed a zappa project which is invoked by an S3 event. When it's deployed, it creates a record under the "Event notifications" section of the S3 bucket.
* I've previously configured (via CDK) that the bucket should "Send notifications to Amazon EventBridge for all events in this bucket".

## Expected Behavior

* Deploying the project should retain the existing EventBridge configuration.

## Actual Behavior

* When the Zappa lambda is deployed, the EventBridge configuration is reverted to "Off". 

## Steps to Reproduce

1. Create a project with the following configuration:
```
    "events": [
      {
        "function": "function_name",
        "event_source": {
          "arn": "arn:aws:s3:::BUCKET-NAME",
          "events": [
            "s3:ObjectCreated:*"
          ],
        }
      }
    ]
```

2. Enable EventBridge integration for the bucket:

<img width="1125" alt="Screen Shot 2022-09-21 at 8 58 53 am" src="https://user-images.githubusercontent.com/820219/191390916-648064fb-2bff-45ee-a444-d454e0747923.png">

3. Deploy the Zappa project and observe the integration has been turned off.

**Comment by monkut** [comment]
Here's the related code where zappa schedules events:
https://github.com/zappa/Zappa/blob/master/zappa/core.py#L2775

Zappa does unschedule events before re-scheduling them.
This may trigger the notification flag.

I wonder if this is just a cosmetic issue on aws's side.  
(Internally the notifications may still be sent, but somehow the interaction with the events api is causing the console flag to be turned off.)

Do S3 notifications still work with the target bucket?

**Comment by Sam152** [comment]
Not in this case, no. Once the EventBridge integration reflects as "Off" in the UI, events are no longer delivered to EventBridge.

**Comment by Sam152** [comment]
Revisiting this, I haven't tested it, but I also wonder if other "Event notifications" would also be removed when deploying a zappa project.

**Comment by monkut** [comment]
The easiest workaround I can is is for zappa to provide a flag to ignore redeploying events.

**Comment by zilinskas** [comment]
This is still an issue
