### ISSUE TITLE
How to add regions to existing deployment?

### ISSUE THREAD

**Issue by davidgolden** [zappa/Zappa#1179]
I'd like to either add select regions to an existing deployment or switch to deploying globally. Ideally the former but I don't know if it's possible. I've seen many articles/docs referencing the option in the `init` function for deploying globally, but I haven't seen anywhere what the zappa settings file should look like or how to update an existing application to this. Can anyone point me in the right direction?

**Comment by sridhar562345** [comment]
@davidgolden did you deploy an application already using zappa?
Or are you talking about another deployment which is not deployed using zappa?

Provide more details about what you have done previously and what you want to do.

**Comment by monkut** [comment]
Sounds like you may be able to just add a separate "stage" to the zappa settings file to handle the desired region, and deploy that stage.

```
{ 
    "dev-region1": {"aws_region": "..", ...},
    "dev-region2": {"aws_region": "..", ...}
}
```

**Comment by monkut** [comment]
There is an apparently undocumented `global_deployment` option in zappa, that appears to do what you're requesting.

[global_deployment](https://github.com/zappa/Zappa/blob/master/zappa/cli.py#L1856-L1900)
