### ISSUE TITLE
Pypi lookup failed

### ISSUE THREAD

**Issue by rajkumarks7** [zappa/Zappa#1181]
## Expected Behavior
the project should deploy 

## Actual Behavior
ERROR: To modify pip, please run the following command:
D:\s7works\fangate-media-aggregation\fangate\env\Scripts\python.exe -m pip install --quiet --target D:\s7works\fangate-media-aggregation\fangate\handler_venv\Lib\site-packages cfn-flip==1.3.0 colorama==0.4.5 certifi==2022.9.24 urllib3==1.26.12 text-unidecode==1.3 wsgi-request-logger==0.4.6 PyYAML==6.0 tqdm==4.64.1 wheel==0.37.1 python-slugify==6.1.2 MarkupSafe==2.1.1 boto3==1.24.89 durationpy==0.5 botocore==1.27.89 Werkzeug==2.2.2 zappa==0.55.0 idna==3.4 toml==0.10.2 jmespath==1.0.1 troposphere==4.1.0 charset-normalizer==2.1.1 hjson==3.1.0 six==1.16.0 s3transfer==0.6.0 requests==2.28.1 kappa==0.6.0 python-dateutil==2.8.2 placebo==0.9.0 argcomplete==2.0.0 pip==22.2.2 click==8.0.4 setuptools
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\cli.py", line 3033, in handle
    sys.exit(cli.handle())
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\cli.py", line 517, in handle
    self.dispatch_command(self.command, stage)
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\cli.py", line 570, in dispatch_command
    self.update(
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\cli.py", line 978, in update
    self.create_package()
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\cli.py", line 2427, in create_package
    venv=self.zappa.create_handler_venv(use_zappa_release=use_zappa_release),
  File "c:\users\kottur\appdata\local\programs\python\python39\lib\site-packages\zappa\core.py", line 502, in create_handler_venv
    raise EnvironmentError("Pypi lookup failed")
OSError: Pypi lookup failed

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:0.55.0
* Operating System and Python version: windows10 ,3.9
* The output of `pip freeze`:
* beautifulsoup4==4.11.1
blis==0.7.8
build==0.8.0
catalogue==2.0.8
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.0.4
colorama==0.4.5
cssselect==1.1.0
cymem==2.0.6
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl
feedfinder2==0.0.4
feedparser==6.0.8
filelock==3.8.0
huggingface-hub==0.10.1
idna==3.4
jieba3k==0.35.1
Jinja2==3.1.2
joblib==1.2.0
langcodes==3.3.0
lxml==4.9.1
MarkupSafe==2.1.1
murmurhash==1.0.8
newspaper3k==0.2.8
nltk==3.7
numpy==1.22.3
packaging==21.3
pandas==1.4.2
pathy==0.6.2
pep517==0.13.0
Pillow==9.2.0
pip-tools==6.8.0
preshed==3.0.7
psycopg2==2.9.3
pydantic==1.8.2
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.4
PyYAML==6.0
regex==2022.9.13
requests==2.28.1
requests-file==1.5.1
scikit-learn==1.0.2
scipy==1.9.2
sentence-transformers==2.2.0
sentencepiece==0.1.97
sgmllib3k==1.0.0
six==1.16.0
smart-open==5.2.1
soupsieve==2.3.2.post1
spacy==3.2.4
spacy-legacy==3.0.10
spacy-loggers==1.0.3
srsly==2.4.4
thinc==8.0.17
threadpoolctl==3.1.0
tinysegmenter==0.3
tldextract==3.4.0
tokenizers==0.13.1
tomli==2.0.1
torch==1.11.0
torchvision==0.12.0
tqdm==4.64.1
transformers==4.23.1
typer==0.4.2
typing==3.7.4.3
typing_extensions==4.4.0
urllib3==1.26.12
wasabi==0.10.1
youtube-transcript-api==0.4.4
* Link to your project (optional):
* Your `zappa_settings.json`: 
{
    "dev": {
        
        "events": [{
            "function": "main.main_call1",
            "expression": "rate(5 minutes)"
            }],
        "aws_region": "us-east-2",
        "profile_name": "default",
        "project_name": "fangate",
        "runtime": "python3.9",
        "slim_handler": true,
        "use_apigateway": false,
        "timeout_seconds": 300,
        "memory_size": 128,
        "use_precompiled_packages": true,
        "s3_bucket": "zappa-fangate"
    }
}

**Comment by sridhar562345** [comment]
@rajkumarks7 which pip and setuptools version are you using?

**Comment by rajkumarks7** [comment]
i am using 65.4.1 @sridhar562345

**Comment by sridhar562345** [comment]
> @rajkumarks7 which pip and setuptools version are you using?

@rajkumarks7 Also mention the pip version

**Comment by rajkumarks7** [comment]
You can see all my python versions i think it was working well when not using the slim_handler:true.
It is not realted to the python . It is due to the Zappa @sridhar562345

**Comment by monkut** [comment]
Most likely due to a networking issue with pypi.  Make sure you have a network connection when using zappa commands.

**Comment by monkut** [comment]
This error is most likely unrelated to zappa.
Marking as 'invalid' and closing.

**Comment by igalci** [comment]
Any update? I am experiencing same error. Only with slim_handler...
