### ISSUE TITLE
[QA] Curious why not use a Zappa specific logger object

### ISSUE THREAD

**Issue by unext-wendong** [zappa/Zappa#1185]
It seems Zappa is directly operating on the root logger, e.g. setting log levels and outputting logs.

Wouldn't it be better to use a Zappa specific logger, e.g. a logger with name `zappa`?

That would make the app easier to, for example, set different log levels for the logger used by Zappa and the ones by the app, or disable logs from Zappa.

**Comment by monkut** [comment]
Related to:
https://github.com/zappa/Zappa/issues/531

Zappa still uses print extensively throughout the code.
We welcome effort to clean this up.

I'll close this as a duplicate but feel free to add comments to the existing issue or submit a PR.

This PR exists, but it's incomplete, but may be a good starting point.
https://github.com/zappa/Zappa/pull/1162
