### ISSUE TITLE
Events function path gets truncated

### ISSUE THREAD

**Issue by DaBors** [zappa/Zappa#1186]
## Context
If you create an event that you want to execute e.g every hour then if the function path is to long the function name gets truncated and the execution of the event will fail, as the function won't be found

## Expected Behavior
The proper function gets invoked 

## Actual Behavior
The function path gets truncated and fails to find the actual function to invoke in the folder
```
[ERROR] AttributeError: module 'dashboard.setting.auto_action.controller' has no attribute 'auto_actions_based_on_'
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 254, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 389, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 246, in import_module_and_get_function
    app_function = getattr(app_module, function)
```

## Steps to Reproduce

1. Create an event that gets invoked once in a while
2. Change the event function name to a longer string like over 70
3. Invocation will fail since the path will get truncated

## Your Environment

* Zappa version used: 0.54.2
* Python version: Python 3.8
* Your `zappa_settings.json`: 
```
"events": [
    {
        "name": "auto_action_rules",
        "function": "dashboard.setting.auto_action.controller.auto_actions_based_on_rules",
        "expression": "rate(1 hour)"
    }
]

**Comment by monkut** [comment]
AWS has a 64 character limit on the defined function name here, so it cannot be extended beyond the defined 64 character limit.

It would be nice if zappa warns you or throws an error when your configuration is incorrect, but at the moment it doesn't.

As a workaround I suggest shortening your function name where you can.

Example:

```
"events": [
    {
        "name": "auto_action_rules",
        "function": "dashboard.setting.auto_action.controller.run_actions",
        "expression": "rate(1 hour)"
    }
]
```

**Comment by DaBors** [comment]
Thank you for the clarification @monkut! :)
