### ISSUE TITLE
Feature Request: Package boto/botocore optionally

### ISSUE THREAD

**Issue by chris-erickson** [zappa/Zappa#1191]
## Context
From the docs, Zappa excludes boto from the final package because lambda has it already. Unfortunately the AWS version is ancient and tools like `aioboto` rely on functionality of newer versions. It's unclear how one can easily get boto packaged along with app files. Is there a way forward to get boto packaged with deploys, if optionally?

## Expected Behavior
Let me package whatever version of boto I want.

## Actual Behavior
It's excluded [per the docs](https://github.com/zappa/Zappa#how-zappa-makes-packages).

## Possible Fix
Give a config option to skip this, default behavior is to keep current functionality.

## Steps to Reproduce
Attempt to deploy an app with a modern version of aioboto like `aioboto3==10.1.0`. Lambda will fail to start when the aioboto import is reached and it tries to access a method on boto/botocore that doesn't exist on recent versions.

## Your Environment
* Zappa version used: Latest
* Operating System and Python version: Lambda, 3.9

**Comment by monkut** [comment]
Here are the current default excludes:
```
["boto3", "dateutil", "botocore", "s3transfer", "concurrent"]
```
https://github.com/zappa/Zappa/blob/master/zappa/cli.py#L2443

It's unintuitive, but it appears you should be able to optionally include all these by settings `exclude=[]` so that the defaults are not used.

**Comment by monkut** [comment]
an update to exclude handling will be handled in the issue below:
https://github.com/zappa/Zappa/issues/1241

closing this issue.
