### ISSUE TITLE
Remove patron link from README

### ISSUE THREAD

**Issue by monkut** [zappa/Zappa#1200]
Currently the zappa README contains a [Patrons](https://github.com/zappa/Zappa#patrons) section and link maintained by the original author of the package.

Since he has left the project this issue proposes to remove the Patron section in it's entirety.

**Comment by souravjamwal77** [comment]
Hi @monkut 
I support this and we can contact the original author for this. Also, with the donations we can hire devs full time and also set up domains like poetry, numpy, and pandas for better SEO.

**Comment by monkut** [comment]
As an open source project with no formal organization, I think the first step to accepting funds would be to create a software foundation of some kind or join an existing one.

**Comment by monkut** [comment]
Added in 0.57.0 release, published to pypi 5/19, closing.
