### ISSUE TITLE
FileNotFoundError in running_in_docker

### ISSUE THREAD

**Issue by hassa** [zappa/Zappa#1201]
## Context

In `running_in_docker` if there is no `/proc/1/cgroup`, like on OSX for example, a FileNotFoundError is raised and zappa can't be imported.

We do some stuff with SQS and zappa's asynchronous tasks so we import zappa even during dev.

## Expected Behavior

FileNotFoundError should be caught and running_in_docker should return False.

## Actual Behavior

A FileNotFoundError is raised.

## Possible Fix

FileNotFoundError should be caught and running_in_docker should return False.

## Steps to Reproduce

1. Be on OSX
2. import zappa
3.

## Your Environment

* Zappa version used: 0.56.0
* Operating System and Python version: OSX 12.6, Python 3.9 and 3.11.0
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by rogerhoward** [comment]
Having the same issue, but triggered by "zappa init" even; eg:

1. create a virtualenv and activate it
2. install zappa ("pip install zappa")
3. run "zappa init"

**Comment by monkut** [comment]
Thanks for reporting this, we'll get a fix out soon!

**Comment by pkaufhol** [comment]
Same issue on osx!

**Comment by monkut** [comment]
Method was changed, and fixed in the 0.56.1 release, please check.
