### ISSUE TITLE
How to avoid the "Using locally cached manylinux wheel" or how to install dependencies manually.

### ISSUE THREAD

**Issue by zeeshan3945** [zappa/Zappa#1202]
## Context
 - grpcio-tools==1.51.1: Using locally cached manylinux wheel
 - grpcio==1.51.1: Using locally cached manylinux wheel
 - numpy==1.23.5: Using locally cached manylinux wheel
 - torch==1.13.0: Using locally cached manylinux wheel

Whenever I deploy my flask app the above messages are displayed on the terminal. When the deployment is completed, it shows me the "No module error" for those packages. My question is how to avoid it.

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: zappa==0.55.0
* Operating System and Python version: Mac OS, python 3.9
* The output of `pip freeze`: 
anyio==3.6.2
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
Flask==2.2.2
grpcio==1.51.1
grpcio-tools==1.51.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.16.2
httpx==0.23.1
hyperframe==6.0.1
idna==3.4
importlib-metadata==5.1.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
numpy==1.23.5
Pillow==9.3.0
protobuf==4.21.10
pydantic==1.10.2
qdrant-client==0.11.4
requests==2.28.1
rfc3986==1.5.0
sniffio==1.3.0
torch==1.13.0
torchvision==0.14.0
typing_extensions==4.4.0
urllib3==1.26.13
Werkzeug==2.2.2
zipp==3.11.0

* Link to your project (optional):
* Your `zappa_settings.json`: 
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "ap-south-1",
        "profile_name": "default",
        "project_name": "qdrant",
        "runtime": "python3.9",
        "s3_bucket": "zappa-v3gar2wjg",
        "timeout_seconds": 900,
        "slim_handler": true

    }
}

**Comment by monkut** [comment]
Can you share the traceback from the logs?

**Comment by monkut** [comment]
Looks like a module install error, without a traceback and details of the problem package there's not much we can do.

Will close this if no additional information is provided.

**Comment by monkut** [comment]
No additional information provided, closing.
