### ISSUE TITLE
Error: OSError: Pypi lookup failed

### ISSUE THREAD

**Issue by Fazyl03** [zappa/Zappa#1216]
## Context

I tried to deploy model in Amazon Lambda. But there's an error while deploying my model with packages. This is log:
Calling update for stage dev..
Creating zappa-permissions policy on yolov3-gun-detec-dev-ZappaLambdaExecutionRole IAM Role.
C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Downloading and installing dependencies..
 - markupsafe==2.1.2: Using locally cached manylinux wheel
 - pillow==9.4.0: Using locally cached manylinux wheel
 - pyyaml==5.4.1: Using locally cached manylinux wheel
 - charset-normalizer==3.0.1: Using locally cached manylinux wheel
 - numpy==1.24.2: Using locally cached manylinux wheel
 - opencv-python==4.5.2.54: Using locally cached manylinux wheel
Packaging project as gzipped tarball.
ERROR: To modify pip, please run the following command:
C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\Scripts\python.exe -m pip install --quiet --target C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\handler_venv\Lib\site-packages wheel==0.38.4 placebo==0.9.0 boto3==1.26.64 cfn-flip==1.3.0 PyYAML==5.4.1 argcomplete==1.9.3 zappa==0.56.1 click==8.1.3 requests==2.28.2 s3transfer==0.6.0 certifi==2022.12.7 urllib3==1.26.14 toml==0.10.2 jmespath==0.9.3 Werkzeug==2.2.2 tqdm==4.19.1 kappa==0.6.0 Unidecode==1.3.6 idna==3.4 python-slugify==1.2.4 colorama==0.4.4 botocore==1.29.65 pip==23.0 hjson==3.0.1 troposphere==4.3.0 durationpy==0.5 python-dateutil==2.6.1 MarkupSafe==2.1.2 six==1.16.0 charset-normalizer==3.0.1 setuptools
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\cli.py", line 3044, in handle
    sys.exit(cli.handle())
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\cli.py", line 519, in handle
    self.dispatch_command(self.command, stage)
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\cli.py", line 572, in dispatch_command
    self.update(
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\cli.py", line 980, in update
    self.create_package()
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\cli.py", line 2434, in create_package
    venv=self.zappa.create_handler_venv(use_zappa_release=use_zappa_release),
  File "C:\Users\fazyl\Desktop\Yolov3_Gun_Detector\myenv\lib\site-packages\zappa\core.py", line 502, in create_handler_venv
    raise EnvironmentError("Pypi lookup failed")
OSError: Pypi lookup failed

In forums said that it possibly can be problem of versions of pip-tools, but in later versions of zappa it doesn't included.

## Expected Behavior

My Flask app needs to be deployed and packages installed.

## Actual Behavior

It gives error of packages problem.

## Steps to Reproduce

1.
2.
3.

## Your Environment
Zappa version used: 0.56.1
Operating System and Python version: 3.9
The output of  "pip freeze":
argcomplete==1.9.3
aws-configure==2.1.8
awscli==1.27.65
boto3==1.26.64
botocore==1.29.65
certifi==2022.12.7
cfn-flip==1.3.0
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.4
docutils==0.16
durationpy==0.5
Flask==2.2.2
future==0.16.0
hjson==3.0.1
idna==3.4
importlib-metadata==6.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==2.1.2
numpy==1.24.2
opencv-python==4.5.2.54
pep517==0.13.0
Pillow==9.4.0
pip-tools==6.1.0
placebo==0.9.0
pyasn1==0.4.8
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==5.4.1
requests==2.28.2
rsa==4.7.2
s3transfer==0.6.0
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tqdm==4.19.1
troposphere==4.3.0
Unidecode==1.3.6
urllib3==1.26.14
Werkzeug==2.2.2
wsgi-request-logger==0.4.6
zappa==0.56.1
zipp==3.12.1

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by igalci** [comment]
Any update? same error...

**Comment by Plumpsey314** [comment]
I am having the same problem too. One thing I realized is that if I set  "slim_handler" to false or just don't define it in my zappa_settings.json the error goes away, but then there comes a problem of the project being too large, which I do not know how to fix either.

**Comment by monkut** [comment]
Pypi lookup failed is a general error.  This can occur when your dependencies can't be resolved, or pypi is not reachable.

I think we can add more error info, so it's easier to debug the issue.

**Comment by gustavobartho** [comment]
Any solutions yet? Im having the same problem

**Comment by Fazyl03** [comment]
I used python 3.8. It has worked for me somehow.
