### ISSUE TITLE
Zappa won't write to shared S3 bucket with shared KMS key

### ISSUE THREAD

**Issue by brycewade1** [zappa/Zappa#1221]
## Context
When writing to a Shared S3 bucket (i.e. a bucket owned by a separate AWS account) with a shared customer managed KMS key (i.e. the KMS key also belongs to another AWS account) Zappa will not write the lambda zip files to S3 bucket.  The same thing happens if you just try to use the AWS CLI to copy the file to the S3 bucket without specifying the the "--sse" and "--sse-kms-key-id".  Fortunately the AWS CLI has these options to get it to work.  Zappa doesn't.

## Expected Behavior
Zappa should have options similar to "--sse" and "--sse-kms-key-id" that gives boto3 enough of a hint of how to write to the encrypted bucket.

## Actual Behavior
Zappa fails to upload the file and prints "Error: Unable to upload to S3. Quitting."

## Possible Fix
Extend the settings to add flags similar to "--sse" and "--sse-kms-key-id" and pass them along as the the ExtraArgs to the boto.client copy and upload_file functions.

## Steps to Reproduce

1. Create a KMS key in another AWS account (call it Account A) and set up the key policy so it can be used to encrypt and decrypt in another account (call it Account B).
2.Create a S3 bucket in Account A and set up the bucket policy so Account B can write to to the bucket.  Set it up to do aws:kms encryption buy default, and use the KMS key from step 1
3. Set up Zappa to use the S3 bucket and try to deploy a lambda function.  It will fail to deploy.

## Your Environment

* Zappa version used: 0.56.1
* Operating System and Python version: cimg/python:3.8.13 docker container in x86_64 CircCI host
* The output of `pip freeze`:
* anyio==3.6.2
argcomplete==2.0.0
attrs==21.4.0
awscli==1.27.69
backoff==1.11.1
bcrypt==4.0.1
benchling-api-client==2.0.3
benchling-sdk==1.4.1
black==22.6.0
boto==2.49.0
boto3==1.24.55
botocore==1.27.55
certifi==2022.6.15
cffi==1.15.1
cfn-flip==1.3.0
charset-normalizer==2.1.0
click==8.1.3
colorama==0.4.4
coverage==7.1.0
cryptography==39.0.1
dataclasses-json==0.5.7
docutils==0.16
durationpy==0.5
fabric==3.0.0
Flask==2.1.3
h11==0.12.0
hjson==3.1.0
httpcore==0.14.7
httpx==0.22.0
idna==3.3
importlib-metadata==4.12.0
iniconfig==2.0.0
invoke==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
kappa==0.6.0
MarkupSafe==2.1.1
marshmallow==3.19.0
marshmallow-enum==1.5.1
moto==4.0.1
mypy-extensions==1.0.0
packaging==23.0
paramiko==3.0.0
pathspec==0.11.0
placebo==0.9.0
platformdirs==3.0.0
pluggy==1.0.0
prettytable==3.6.0
py==1.11.0
pyasn1==0.4.8
pycparser==2.21
PyNaCl==1.5.0
pytest==7.1.2
pytest-cov==3.0.0
pytest-mock==3.8.2
python-dateutil==2.8.2
python-dotenv==0.21.0
python-slugify==6.1.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.1
responses==0.22.0
rfc3986==1.5.0
rsa==4.7.2
s3transfer==0.6.0
six==1.16.0
sniffio==1.3.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tqdm==4.64.0
troposphere==4.1.0
types-toml==0.10.8.3
typing-inspect==0.8.0
typing_extensions==4.4.0
urllib3==1.26.11
wcwidth==0.2.6
Werkzeug==2.1.2
wsgi-request-logger==0.4.6
xmltodict==0.13.0
zappa @ git+https://github.com/brycewade1/Zappa@e80476a95379163d853a233eb399fe8ed7e651d9
zipp==3.8.1

* Link to your project (optional):
* Your `zappa_settings.json`: 
{
  "sandbox": {
    "app_function": "app.app",
    "aws_environment_variables": {
      "AWS_SECRET_PREFIX": "sandbox"
    },
    "aws_region": "us-west-2",
    "environment_variables": {
      "BENCHLING_TENANT": "ourtest"
    },
    "manage_roles": false,
    "profile_name": "sandbox",
    "project_name": "zappa-forms",
    "role_arn": "arn:aws:iam::012345678910:role/run/sandbox-zappa-forms-us-west-2-execution-role",
    "runtime": "python3.8",
    "s3_bucket": "my-bucket-lambda-us-west-2-012345678910",
    "tags": {
      "Department": "Scientific Computing",
      "Environment": "Sandbox",
      "Project": "Sample Tracking"
    }
  }
}

**Comment by ryansmith940** [comment]
Could someone take a look at this? We could use this feature.
