### ISSUE TITLE
Asynchronous task timeout issue

### ISSUE THREAD

**Issue by hafneem** [zappa/Zappa#1223]
I have deployed a django app on using Zappa and I have an asynchronous task which is executed from admin actions. Sometimes when I does the action I get "endpoint request timeout" error in the browser and the task still gets executed in the background. But sometimes no error is shown and the task executes as expected. 

Please let me know what could be this intermittent issue where timeout error occurs

**Comment by monkut** [comment]
If you are using API Gateway, the API gateway has a 30 second timeout in front of the lambda.

If your lambda process takes longer than 30 seconds, you'll see a timeout from the browser, but the process will continue and not timeout as long as it finishes within the max set lambda execution time.

**Comment by sridhar562345** [comment]
instead of adding @task decorator to the main action function, use it on the inner function you are calling as below.
```
def my_action():
    some_func()

@task
def some_func():
   ...
```

**Comment by monkut** [comment]
If you share a bit more of your code, we may be able to help a bit more.

What is the request being made that results in calling your async function?

**Comment by hafneem** [comment]
def update_video_visibility_task(video_id_list, visibility):
    """
    Zappa async task to execute visibility update function
    :param video_id_list:
    :param visibility:
    :return:
    """
    update_video_visibility(video_id_list, visibility)


@task
def update_video_visibility(video_obj_id_list, visibility_to_update):
    """
    Updates the privacy status of passed video ids in youtube, (private/public/unlisted)
    :param video_obj_id_list:
    :param visibility_to_update:
    :return:
    """
    video_queryset = YoutubeVideo.objects.filter(id__in=video_obj_id_list)
    for video in video_queryset:
        account = video.user
        api_service_name = "youtube"
        api_version = "v3"
        credentials = Credentials(token=account.access_token, refresh_token=account.refresh_token,
                                  client_id=account.client_id, client_secret=account.client_secret,
                                  token_uri=account.token_uri)
        client = build(api_service_name, api_version, credentials=credentials, cache_discovery=False)
        request = client.videos().update(
            part='status',
            body={
                "id": video.video_id,
                "status": {
                    "privacyStatus": visibility_to_update
                }
            }
        )
        request.execute()
        video.visibility = visibility_to_update
        video.save()


    def make_videos_private(modeladmin, request, queryset):
        """
       admin action which calls the function that executes async task
        """
        update_video_visibility_task(list(queryset.values_list('id', flat=True)), YoutubeVideo.PRIVATE)
        messages.info(request, "Videos are being updated in background, please check in few seconds")


This is my code where I'm making youtube api requests within the async task. But even calling the async function results in timeout error but the task gets executed in the background.

**Comment by monkut** [comment]
Ok, you code doesn't look like it should take long.

Is your lambda in a VPC?  If so you will need a NAT to make calls to the internet (youtube).
If you don't these calls will timeout because they can't reach the destination.

**Comment by monkut** [comment]
Not enough information to resolve.  Closing.

It seems like the task requested task is exceeding the max set lambda execution time, causing the timeout.

First configure your lambda to timeout at the max 15 minutes.
If it exceeds this limit, your lambda will and is expected to timeout.

In which case, you need to adjust your code so that it finishes in the max time allotted to lambda.
