### ISSUE TITLE
update the environment variables which are declared in the zappa settings. json file.

### ISSUE THREAD

**Issue by kalyangcp123** [zappa/Zappa#1224]
I have declared  my zappa_settings.json file like this 

{
    "dev": {
        "s3_bucket": "zappa-for-mock",
        "app_function": "mock_server.app",
        "runtime": "python3.9",
        "slim_handler": true,
        "delete_local_zip": true,
        "lambda_description": "aws:states:opt-out",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "mockserver39",
        "aws_environment_variables": {
            "number": "12222121311",
            "order_id": "1000212",
            "status": "status"
        }
    }
}

Now i have run the - "zappa update dev" . Now the environment variables are set in the AWS with the above values.

Now i am trying to overide the variables by using this command - zappa update dev --set number=12222121355.  but the values are not getting overwritten. 

How can i achieve this from the runtime only.

Can someone help me this.

Awaiting your reply.

**Comment by souravjamwal77** [comment]
Hi @kalyangcp123 number is not a variable in Zappa settings.
You may have seperate .env file.

**Comment by kalyangcp123** [comment]
Hi @souravjamwal77 

can you point me to an article on how to do this? I did not find any with
google.

**Comment by souravjamwal77** [comment]
@kalyangcp123 
https://github.com/zappa/Zappa#setting-environment-variables

**Comment by monkut** [comment]
I believe that environment variables set with `aws_environment_variables` will be available in the aws lambda console.
You should be able to update the value directly there.

**Comment by souravjamwal77** [comment]
Hi @monkut I had a call with @kalyangcp123 and his use case is to update env variables regularly. Now, once a lambda environment is invoked it may keep same environment variables during its execution or any async invocation or unless lambda cools down and new environment is commenced again.
He needs to update the values like order Id, number and status regularly and for this use he can use either a DB or S3 remote env or Dynamo DB to update the values regularly. 
Let me know if I'm incorrect.

**Comment by monkut** [comment]
Ok, closing.
