### ISSUE TITLE
Zappa pex support

### ISSUE THREAD

**Issue by mister-rao** [zappa/Zappa#1225]
Thank you for the awesome project.

I am using zappa for deploying my monolith django project on aws lambda.

To move to microservices, I am using pantsbuild [django mono-repo ](https://github.com/pantsbuild/example-django) example project. 
This allows me to build and deploy separate mini django services as pex files.  I can run the pex file on a python-3.8:slim-buster with docker-compose. 

My question is can I use zappa to neatly deploy the service contained in docker-compose on aws lambda? Or is there a way to deploy pex on aws lambda ?

**Comment by monkut** [comment]
I'm not sure how your docker-compose is constructed, but lambda and zappa allow you to create custom docker images.
If you create an image for each desired service as a separate service, you should be able to deploy it as such.

**Comment by mister-rao** [comment]
Thank you for the fast reply.

This is how my docker-compose file looks like:

`version: "3.8"

services:
  
  service_1:
    image: service_1:latest
    container_name: service_1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: "service_1"
        EXEC_PATH: "dist/app._microservices.service_1"
    env_file:
      - ./.env
    ports:
      - 8002:8001
    volumes:
      - static_data:/vol/web
  
  service_2:
    image: service_2:latest
    container_name: service_2
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: "service_2"
        EXEC_PATH: "dist/app._microservices.service_2"
    env_file:
      - ./.env
    ports:
      - 8003:8001
    volumes:
      - static_data:/vol/web

  
  service_3:
    image: service_3:latest
    container_name: service_3
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: "service_3"
        EXEC_PATH: "dist/app._microservices.service_3"
    env_file:
      - ./.env
    ports:
      - 8001:8001
    volumes:
      - static_data:/vol/web

volumes:
  static_data:
`

And my Dockerfile

`FROM python:3.8-slim-buster

ARG SERVICE
ARG EXEC_PATH
ENV SERVICE ${SERVICE}
ENV EXEC_PATH ${EXEC_PATH}

RUN echo "Building ${SERVICE} at ${EXEC_PATH}"

RUN mkdir /app


COPY ${EXEC_PATH}/gunicorn.pex /app/


WORKDIR /app

ENTRYPOINT ["./gunicorn.pex"]
`
