### ISSUE TITLE
How we can set up web acl (WAF) with api gateway stage?

### ISSUE THREAD

**Issue by jitesh-prajapati123** [zappa/Zappa#1232]
How we can set up web acl (WAF) with api gateway stage?

**Comment by sridhar562345** [comment]
WAF configuration is currently not supported by Zappa. You can enable it manually from the console as of now.

**Comment by monkut** [comment]
Yes, you can configure WAF as you would normally in AWS, via the console, or cloudformation.  

Zappa doesn't have any special support to auto-add WAF to your API Gateway.

closing.
