### ISSUE TITLE
How we can set access logs with api gateway stage?

### ISSUE THREAD

**Issue by jitesh-prajapati123** [zappa/Zappa#1233]
How we can set access logs with api gateway stage?

**Comment by sridhar562345** [comment]
@jitesh-prajapati123 

Are you asking about the settings in the below image?
![Screenshot from 2023-04-26 12-11-08](https://user-images.githubusercontent.com/59284206/234490966-aa349db0-016e-4531-90e4-da80e2e61c56.png)

**Comment by monkut** [comment]
I'm going to close this as it's not zappa specific.

For more details on configuring apigateway logging  see:

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html
