### ISSUE TITLE
exclude_glob feature attempts to delete files outside the tmp_file_path

### ISSUE THREAD

**Issue by beon9273** [zappa/Zappa#1240]
## Context

When using the exclude_glob parameter to exclude files from the lambda file, if you set

exclude_glob = [ "/app/static/**"]  (notice the leading forward slasj -- that is the problem )

then Zappa will delete the folder "/app/static" and everything in it. 

## Expected Behavior

Setting exclude_glob should never result in deleting files off of the users machine.  It should only delete files that are inside the tmp_file_path it creates.

## Actual Behavior

Zappa deletes all files of the machine that match the glob pattern, including ones not inside the tmp_file_path directory zappa created.  

## Possible Fix

Currently the process is:
1. Copy the entire app tree to a temporary path
2. Iterate through the glob expressions deleting all files in the tmp directory that match. 

The cause of the bug lies in the nuances of the "os.path.join" function. In particular, the issue is with the leading "/" forward slash in the glob expression. Basically: 

    path = os.path.join("/tmp/file/path", "/home/user/app")
    print(path) 
      path = "/home/user/app" 

Possible fix is to add a check to see if file is inside 

## Steps to Reproduce
1. Set "exclude_glob" to include a valid absolute glob expression. 
2. Run zappa 
3. Notice how all the files matching that absolute url are gone

Note: A similar issue occurs if you set exclude_glob to be a "string" instead of a "list of strings". In that case zappa actually tries to delete your entire filesystem which throws a permission denied error (ask me how I know)

## Your Environment
* Zappa version used: 0.56.1
* Operating System and Python version: Ubuntu with python 3.8.

**Comment by monkut** [comment]
merged and released in 0.58.0

closing.
