### ISSUE TITLE
Option to disable default excludes

### ISSUE THREAD

**Issue by sridhar562345** [zappa/Zappa#1241]
Excluding boto3 and botocore by default is good, but there might be cases when the user has to use a newer version of boto3 that's not available on lambda. Currently, there is a workaround as below.

```py
exclude = self.stage_config.get("exclude", ["boto3", "dateutil", "botocore", "s3transfer", "concurrent"])
```

To use newer version of boto3, specify exclude in zappa_settings.json which will override the default excludes
```json
"exclude": ["file.txt"]
```

https://github.com/zappa/Zappa/pull/1235 will modify this snippet, but we won't be able to use the newer boto3 version at all.

```py
exclude = self.stage_config.get("exclude",
exclude += ["boto3", "dateutil", "botocore", "s3transfer", "concurrent"]
```
So having the option to disable default excludes would be better.

**Comment by monkut** [comment]
After the 3.11 release, let's try to get this in.

**Comment by monkut** [comment]
Just to note, you can currently disable the default excludes by setting, `excludes=[]`.
