### ISSUE TITLE
Outdated manylinux wheels download logic

### ISSUE THREAD

**Issue by sridhar562345** [zappa/Zappa#1249]
Seems like some packages are publishing abi3 manylinux wheels in below format
```
pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
```

Our current regex is not matching this kind of manylinux wheel format.

According to [pypa/manylinux](https://github.com/pypa/manylinux) PEP 600 has been designed to be "future-proof" and does not enforce specific symbols and a specific distro to build. It only states that a wheel tagged manylinux_x_y shall work on any distro based on glibc>=x.y

These are the current glibc versions in lambda runtimes.

Python | glibc
-- | --
python3.7 | 2.17
python3.8 | 2.26
python3.9 | 2.26
python3.10 | 2.26

I verified that 2_24 wheels are not working on the python3.7 runtime.

**Comment by monkut** [comment]
merged, and released in 0.58.0.
closing
