### ISSUE TITLE
Add support for !pattern in exclude_glob

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [zappa/Zappa#1252]
## Context
We've `exclude_glob` feature to ignore specific patterns in the lambda package, here it could be better if we can add support for !pattern so that to exclude specific patterns from ignoring, similar to gitignore.

For example, the below config should exclude all the files/folders with prefix `env_`, except `env_alpha.sh`:
```json
{
  "alpha": {
	...
	...
	...
	"exclude_glob": ["env_*", "!env_alpha.sh"]
	
  }
}
```

**Comment by monkut** [comment]
Have you tried `[!env_alpha.sh]`.

In anycase, I believe the way that exclude functions, is that it will exclude all items matching the given glob strings.
In your case above, you want to combine the results of the two elements, but `env_*` will exclude `env_alpha.sh`.

In this case it's probably better to rename the file you want to be included to something that doesn't match the pattern you are trying to exclude.
