### ISSUE TITLE
Application doesn't run: AttributeError module 'werkzeug.urls' has no attribute 'url_unquote'

### ISSUE THREAD

**Issue by monkut** [zappa/Zappa#1276]
## Context

Zappa project does not run displaying error:

```
AttributeError module 'werkzeug.urls' has no attribute 'url_unquote'
```

Related:
https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls

## Expected Behavior

No error

## Possible Fix

It appears that the Werkzeug API has changed in version >=3.0.0.
Support the change, or update zappa dependencies to "<3.0.0"

## Steps to Reproduce

1. Create a fresh package
    - The latest Werkzeug will be installed
2. deploy and run on lambda

**Comment by sridhar562345** [comment]
@monkut any update on this?
