### ISSUE TITLE
Slack message on deploy?

### ISSUE THREAD

**Issue by jtowe1** [zappa/Zappa#1290]
Maybe I don't know the terms to search for, but, is there an option to post a notification to Slack when a deploy is done?

**Comment by monkut** [comment]
There are callback hooks available that can be used for this.
You will need to get an access key and register your app with slack.  Once that's done you can write a function to post to SLACK via the post callback.


```
"callbacks": { // Call custom functions during the local Zappa deployment/update process
            "settings": "my_app.settings_callback", // After loading the settings
            "zip": "my_app.zip_callback", // After creating the package
            "post": "my_app.post_callback", // After command has executed
        },
```
