### ISSUE TITLE
There's no obvious way to join the Zappa slack

### ISSUE THREAD

**Issue by simsong** [zappa/Zappa#1304]
Zappa's bug output states:

```
Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Zappa/Zappa
And join our Slack channel here: https://zappateam.slack.com
Love!,
 ~ Team Zappa!
```

but there is no obvious way to join the slack channel:

![image](https://github.com/zappa/Zappa/assets/1594284/0da015ae-14f5-4989-999e-bb2be1b4c1b0)

trying to log in, I get:
![image](https://github.com/zappa/Zappa/assets/1594284/ed7a79e8-1760-459a-a0e4-af4476528818)

**Comment by simsong** [comment]
Thank you so much! I joined. I have had a few problems getting by going and have questions. I am a seasoned developer and need this to work, so I am here to help!

**Comment by monkut** [comment]
No problem, feel free to bring discussion there!

**Comment by TeddJohnson** [comment]
the link is down again. can you make another/longer invite link?

**Comment by javulticat** [comment]
@TeddJohnson et. al., here's a new link that should work for the foreseeable future:

https://join.slack.com/t/zappateam/shared_invite/zt-2ej8p6jqu-IdOZgkfj4AjAg8JHIPwwWQ

**Comment by MartijnGevaert** [comment]
Looks like the temporary link is no longer working
