### ISSUE TITLE
Python3.12 is not supported

### ISSUE THREAD

**Issue by Krata4** [zappa/Zappa#1310]
## Context
When I am tring to use Zappa with python3.12 I am getting error:
RuntimeError: This version of Python (3.12) is not supported!
Zappa (and AWS Lambda) support the following versions of Python: ['3.7', '3.8', '3.9', '3.10', '3.11']
## Expected Behavior
based on documentation python3.12 should be supported

## Actual Behavior
python3.12 is not supported

**Comment by javulticat** [comment]
Duplicate of #1291
