### ISSUE TITLE
Python 3.10 not supported in latest package version

### ISSUE THREAD

**Issue by kappa90** [zappa/Zappa#1332]
Installed Zappa 0.59.0, this error is thrown when doing `zappa init`:

```
RuntimeError: This version of Python (3.10) is not supported!
Zappa (and AWS Lambda) support the following versions of Python: ['3.7', '3.8', '3.9']
```

Which doesn't match what's in the `__init__.py` file, where I can clearly see that it supports up to 3.12.

So I'm wondering if there is a problem with the released package.

## Expected Behavior
Python 3.10 should work.

## Actual Behavior
Zappa throws a RuntimeError

## Possible Fix
Maybe an issue with the released package?

## Steps to Reproduce
```
venv python 3.10
pip install zappa
zappa init
```

## Your Environment
* Zappa version used: 0.59.0
* Operating System and Python version: Mac OS, Python 3.10
* The output of `pip freeze`:
```argcomplete==3.3.0
boto3==1.34.93
botocore==1.34.93
certifi==2024.2.2
cfn-flip==1.3.0
charset-normalizer==3.3.2
click==8.1.7
durationpy==0.6
hjson==3.1.0
idna==3.7
jmespath==1.0.1
kappa==0.6.0
MarkupSafe==2.1.5
placebo==0.9.0
python-dateutil==2.9.0.post0
python-slugify==8.0.4
PyYAML==6.0.1
requests==2.31.0
s3transfer==0.10.1
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.66.2
troposphere==4.7.0
urllib3==2.2.1
Werkzeug==3.0.2
zappa==0.59.0
```

**Comment by javulticat** [comment]
Yikes, thanks for catching that!  I'll work on releasing a hotfix for that ASAP.

**Comment by javulticat** [comment]
I'm unable to reproduce with Python 3.10 on MacOS - `zappa init` runs successfully and outputs a `zappa_settings.json` file without issue:

![image](https://github.com/zappa/Zappa/assets/31746850/6a7928c3-c2d5-491f-bf37-69d6d94e057a)

Can you try creating your virtual environment using Python's built-in [`venv` command](https://docs.python.org/3.10/library/venv.html) and see if that makes a difference?

```bash
python3.10 -m venv env
source env/bin/activate
pip install zappa
zappa init
```

**Comment by kappa90** [comment]
I confirm it now works 🤷  Thanks!
