### ISSUE TITLE
`{"message":"Forbidden"}` when using custom domain

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [zappa/Zappa#1338]
Unable to deploy my flask api with custom domain.
## Context
I deployed my basic flask app using `zappa deploy` .
The url I get after this command is working.
When I run `zappa certify` I get no errors.
I don't use Route 53, my domain is in GoDaddy and I already got certificate in ACM.

But this link https://d32unri5k0ytzs.cloudfront.net/ which I found in apigateway -> custom domain is giving `{"message":"Forbidden"}`

## Your Environment
* Your `zappa_settings.json`: 
```
{
    "prod": {
        "app_function": "app.app",
        "exclude": [
            "boto3",
            "dateutil",
            "botocore",
            "s3transfer",
            "concurrent"
        ],
        "aws_region": "ap-south-1",
        "profile_name": null,
        "project_name": "api-dispatcher",
        "runtime": "python3.11",
        "s3_bucket": "api-dispatcher",
        "domain": "api-dispatcher.gameup.app",
        "certificate_arn":"arn:aws:acm:us-east-1:<ACCOUNT-ID>:certificate/<ID>",
        "route53_enabled" : false
    }
}
```

**Comment by pcolmer** [comment]
@ashwanthbalakrishnan5 Have you gone into API Gateway and, under "custom domain names", added an API mapping for the stage "prod"?

**Comment by rafmacalaba** [comment]
> @ashwanthbalakrishnan5 Have you gone into API Gateway and, under "custom domain names", added an API mapping for the stage "prod"?

I already have this setting but it is still 403 Forbidden error. Anything to check what is the root cause?

Also, there is no Cloudfront distribution being created by the app. Is it normal?

**Comment by sridhar562345** [comment]
> > @ashwanthbalakrishnan5 Have you gone into API Gateway and, under "custom domain names", added an API mapping for the stage "prod"?
> 
> I already have this setting but it is still 403 Forbidden error. Anything to check what is the root cause?
> 
> Also, there is no Cloudfront distribution being created by the app. Is it normal?

If you have a custom domain, you should be able to see the AWS internal CloudFront distribution. However, these CloudFront distributions won't be visible in the CloudFront service. See the below image for reference.
![Screenshot from 2024-11-25 10-52-01](https://github.com/user-attachments/assets/f837d51d-1819-4b9c-a0e7-39d8d772d2a9)

**Comment by sridhar562345** [comment]
> > @ashwanthbalakrishnan5 Have you gone into API Gateway and, under "custom domain names", added an API mapping for the stage "prod"?
> 
> I already have this setting but it is still 403 Forbidden error. Anything to check what is the root cause?
> 
> Also, there is no Cloudfront distribution being created by the app. Is it normal?

If you have a custom domain, you should be able to see the AWS internal CloudFront distribution. However, these CloudFront distributions won't be visible in the CloudFront service. See the below image for reference.

![Screenshot from 2024-11-25 10-52-01](https://github.com/user-attachments/assets/82f19a77-bfde-4c6e-bdca-2a4cdbc79093)
