### ISSUE TITLE
Scheduled function truncated at 63 characters and fails to invoke

### ISSUE THREAD

**Issue by eviltwin** [zappa/Zappa#1351]
if I have a scheduled function with a name longer than 63 characters, then the name will be truncated in the CloudWatch event name/ARN:

```
{
    "production": {
       ...
       "events": [{
           "function": "my_module.my_submodule.my_really_long_and_descriptive_function_name",
           "expressions": ["rate(1 day)"]
       }],
       ...
    }
}
```

Event rule: `arn:aws:events:eu-west-2:000000000000:rule/-my_module.my_submodule.my_really_long_and_descriptive_function_`

This results in the following exception when the event is handled by the lambda:

```
AttributeError: module 'my_module.my_submodule' has no attribute 'my_really_long_and_descriptive_function_'
```

## Context

It looks like the `whole_function` value is parsed out of the event ARN here: https://github.com/zappa/Zappa/blob/39f75e76d28c1a08d4de6501e6f794fe988cbc98/zappa/handler.py#L410

Since the ARNs are limited in length, the long module path gets truncated to 63 characters (possibly because of the leading `-` making 64 total). It looks like the full module and function path remains non-truncated in the description of the event rule.

## Expected Behavior
It should invoke the non-truncated function, or should refuse to deploy with handler functions that are too long.

## Actual Behavior
It throws an exception and the scheduled task never executes.

## Possible Fix
Either:
1. Have the handler read the non-truncated `whole_function` value from the event description. This might require an extra AWS API call that existing deployments may or may not have permission to perform.
2. During deployment, a mapping of truncated names to full names could be created and embedded in the deployed app bundle, then referenced when handling events.
3. Raise an error (early) during deployment if a handler function name is too long and would result in truncation. It would be better to explicitly fail during deployment than to have guaranteed failures later on that might go unnoticed.

## Steps to Reproduce
1. Create a scheduled function whose fully qualified handler is longer than 63 characters.
2. Deploy.
3. Observe the error logs for the `AttributeError` above.

## Your Environment

* Zappa version used: 0.56.1
* Operating System and Python version: Amazon Linux (lambda), Python 3.9

**Comment by monkut** [comment]
This is handled in 0.59.0

https://github.com/zappa/Zappa/pull/1205

**Comment by eviltwin** [comment]
I'm embarrassed.

I checked the code on the latest release to see if it would still have the same issue, but I didn't check for any other form of mitigation. My apologies, I should have at minimum updated my zappa version and tried again before filing the bug. Sorry for the noise. :)
