### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by flak153** [zappa/Zappa#3]
Is this repo alive?

**Comment by MerreM** [comment]
Not really.

Please add pull requests at https://github.com/MerreM/Zappa while I work on making a community around this.

Any and all help appreciated!

**Comment by hellno** [comment]
Closing this, as a team of contributors is back to supporting the zappa project here 
https://github.com/zappa/Zappa/commit/701eea448715289456d4647b144157e6d66708da
