### ISSUE TITLE
[Migrated] Keep Warm should Default to 15 Minute Intervals

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#344]
Originally from: https://github.com/Miserlou/Zappa/issues/858 by [mcrowson](https://github.com/mcrowson)

Based on reading this article, it looks like we only need the keep_warm event once every 15 minutes.

Related #851

**Comment by monkut** [comment]
Is there any validity to this... it would be beneficial cost wise.  I think the default now is 4 mins.  Can we extend it and still get a keep-warm effect?

**Comment by souravjamwal77** [comment]
Hi @monkut we can increase the keep_warm time interval to 15 mins. I found some answers (links below) mainly AWS keeps lambdas warm from 5-45 mins  (some say it's 5-15 mins and as per others it's 30-45 mins). So, if we keep the lambdas warm callback function to 15 mins, we would save around 2/3 of the cost of maintaining the lambdas warm. 

Basically, it costs around $7-$10 to keep the lambdas warm with a 4 mins callback if we make the default callback time to 15 mins we would be saving more than 2/3 of the costs.

[Source 1](https://acloudguru.com/blog/engineering/how-to-keep-your-lambda-functions-warm#:~:text=As%20suggested%20on%20Stack%20Overflow,minutes%20to%20keep%20them%20warm.)
[Source 2](https://lumigo.io/blog/this-is-all-you-need-to-know-about-lambda-cold-starts/#:~:text=That%20means%20that%20functions%20are%20kept%20warm%20for%20a%20limited%20amount%20of%20time%20(usually%2030%20%E2%80%93%2045%20minutes)%20after%20executing%2C%20before%20being%20spun%20down%20so%20that%20container%20is%20ready%20for%20any%20new%20function%20to%20be%20invoked.)

**Comment by monkut** [comment]
I have applications that are dependent on the function being 'warm'.

We need to do some testing (across regions?) to confirm response times with/without keep warm at various times.

**Comment by souravjamwal77** [comment]
Hi @monkut 
I will perform the tests across regions and will submit the results here.

**Comment by monkut** [comment]
I have questions about how effective the keep_warm function is, however, this issue is only about changing the existing keep_warm value from the current 4 minutes to a more appropriate value.

If tests show that we can increase the keep_warm value and maintain it's current effectiveness (compareable to 4 minutes) then we should have a PR update the value.
