### ISSUE TITLE
[Migrated] from zappa.concurrent.futures import LambdaPoolExecutor?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#401]
Originally from: https://github.com/Miserlou/Zappa/issues/1024 by [olirice](https://github.com/olirice)

**Feature Proposal**
Implement `LambdaPoolExecutor` with a similar api to
`ThreadPoolExecutor` and `ProcessPoolExecutor`?

i.e.
``` python
from concurrent.futures import as_completed # pip install futures on py2.7
from zappa.concurrent.futures import LambdaPoolExecutor

# Pushes current working directory to Lambda
executor = LambdaPoolExecutor(max_workers=15)

# Function to execute in Lambda function
def do_stuff(x: int) -> int:
    return 1

futures = []
for val in range(100):
    # Submit work to Lambda function
    # Store python future (non-blocking)
    future = executor.submit(do_stuff, val)
    futures.append(future)

# As each task completes
for output in as_completed(futures):
    # Collect result from futures object
    result = output.result()
    
    # do more stuff with result
```

Thoughts:
1. Initialization of the executor would package up the project and ship it to Lambda (if not exists).
2. Submitting work to the executor pickles the variable `x`, copies it up to S3 and notifies a handler in Lambda
3. The handler downloads, unpickles, and passes the variables to the function
4. The client (`LambdaPoolExecutor`) repeatedly checks S3 for a response to see if the work is done
5. When the work is done, copy the pickled response from S3, unpickle, and set the result to the futures object

**But why?**
Zappa for cluster computing!
- Drop in replacement for python concurrency primitives
- Map reduce
- ETL
- Distributed web scraping
- Generally take advantage AWS's CPU our internet connection resources with little effort

**Possible hang ups**
- 5 minute max execution time

All thoughts welcome

If the response is positive, I'll take a swing at implementing it.

**Comment by monkut** [comment]
I believe this can be achieved to some degree with the current asynchronous task execution.

Since this is a older migrated task I will close it.  
If there is still interest in getting something like this implemented open a new issue.
