### ISSUE TITLE
[Migrated] ImportError: No module named ...

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#409]
Originally from: https://github.com/Miserlou/Zappa/issues/1045 by [fartashh](https://github.com/fartashh)

I am using linkedin module for authentication in my app. 
and linkedin module use **requests_oauthlib** to import  **OAuth1**

Everything works perfectly on local env but when I deploy the app **sometimes** I get 

```
  File "/tmp/pip-build-V8UP7E/python-linkedin/linkedin/linkedin.py", line 7, in <module>
ImportError: No module named requests_oauthlib
```
it don't always happen 

## Your Environment

* Zappa version used: 0.42.2
* Operating System and Python version: Ubuntu 16.04,  python2.7
* pip version : 9.0.1

**Comment by monkut** [comment]
not enough info.

closing.
