### ISSUE TITLE
[Migrated] Create AWS Billing Alarm By Default

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#412]
Originally from: https://github.com/Miserlou/Zappa/issues/1053 by [Miserlou](https://github.com/Miserlou)

This is just a ticket for discussion, it might be beyond the scope of Zappa, but during @daheats's DjangoCon talk on Alexa skills, she mentioned creating Billing Alarms as a fail-safe against massive financial fail - as I've seen massive $$$ fail happen a few times in the wild, it might be useful to set a sane default for Zappa to create during deploy. (Especially with applications that have S3 event triggers that re-upload, as you could easily create an infinite loop.)

**Comment by monkut** [comment]
considered stale.

closing.
