### ISSUE TITLE
[Migrated] An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#449]
Originally from: https://github.com/Miserlou/Zappa/issues/1193 by [robomotic](https://github.com/robomotic)

## Context
I have added a function handle to process new S3 objects into my existing flask app process.
The flask app process is working fine.

## Expected Behavior
I will expect no errors when deploying the new function.

## Actual Behavior
I received this error:

Calling tail for stage fileprocess..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 2525, in handle
    sys.exit(cli.handle())
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 484, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 572, in dispatch_command
    force_colorize=self.vargs['force_color'] or None,
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 984, in tail
    filter_pattern=filter_pattern,
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/core.py", line 2506, in fetch_logs
    orderBy='LastEventTime'
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

## Possible Fix

No idea
## Steps to Reproduce
I forked the original example and modified just the event [here](https://github.com/robomotic/Zappa/blob/master/example/zappa_settings.json).

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: OSX, Python 3.6.0
* The output of `pip freeze`:
argcomplete==1.9.2
base58==0.2.4
boto==2.48.0
boto3==1.4.7
botocore==1.7.14
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docutils==0.14
dominate==2.3.1
durationpy==0.5
Flask==0.12.2
Flask-Bootstrap==3.3.7.1
Flask-SQLAlchemy==2.3.2
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
placebo==0.8.1
psycopg2==2.7.3.1
python-dateutil==2.6.1
python-magic==0.4.13
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
SQLAlchemy==1.1.14
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.1
Unidecode==0.4.21
urllib3==1.22
visitor==0.1.3
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3

* Link to your project (optional):
* Your `zappa_settings.py`: see fork.

**Comment by rbagdazian** [comment]
I am also getting the same failure during:
zappa deploy dev

Calling deploy for stage dev..
Downloading and installing dependencies..
 - pyyaml==5.4.1: Downloading
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 637k/637k [00:00<00:00, 29.2MB/s]
 - markupsafe==1.1.1: Downloading
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.5k/27.5k [00:00<00:00, 16.0MB/s]
Packaging project as zip.
Uploading zappapp-dev-1614780956.zip (6.3MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.58M/6.58M [00:00<00:00, 18.0MB/s]
Uploading zappapp-dev-template-1614780964.json (1.5KiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.56k/1.56k [00:00<00:00, 50.6kB/s]
Waiting for stack zappapp-dev to create (this can take a bit)..
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 3/4 [00:12<00:04,  4.15s/res]
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.

---------------------------------------------
here is my zappa_settings.json file:
{
    "dev": {
        "app_function": "myapp.app",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "zappapp",
        "runtime": "python3.7",
        "s3_bucket": "zappa-rwb"
        
        "manage_roles": false,
        "role_arn": "arn:aws:iam::--------------:role/zappa-lambda-role"
        "keep_warm": false
    }
}

---------------------------------------------------------------------------------------
When I attempted to run zappa tail I get:

Calling tail for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/zappa/cli.py", line 2778, in handle
    sys.exit(cli.handle())
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/zappa/cli.py", line 512, in handle
    self.dispatch_command(self.command, stage)
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/zappa/cli.py", line 604, in dispatch_command
    keep_open=not self.vargs['disable_keep_open']
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/zappa/cli.py", line 1093, in tail
    filter_pattern=filter_pattern,
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/zappa/core.py", line 3030, in fetch_logs
    orderBy='LastEventTime'
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/venv/lib64/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
-------------------------------------------------------------------------------------------

I'm at a loss as to what to do next.
