### ISSUE TITLE
[Migrated] AWS permission Zappa execution role in example code

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#450]
Originally from: https://github.com/Miserlou/Zappa/issues/1194 by [robomotic](https://github.com/robomotic)

## Context
Running the examples from the Zappa repository. Aws credentials are configured as full administrator user.

## Expected Behavior
When running the zappa deploy for all the entries: dev_api, dev_event, production no extra configuration is necessary.

## Actual Behavior
When I do zappa deploy dev_event, the following error occurs:

(botocore 1.7.35 (/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages), Requirement.parse('botocore==1.7.14'), {'zappa'})
Calling deploy for stage dev_event..
Creating dev-event-zappa-test-flask-app-dev-event-ZappaLambdaExecutionRole IAM Role..
Error: Failed to manage IAM roles!
You may lack the necessary AWS permissions to automatically manage a Zappa execution role.
To fix this, see here: https://github.com/Miserlou/Zappa#using-custom-aws-iam-roles-and-policies

## Possible Fix
Not sure!

## Steps to Reproduce
Git clone Zappa main branch, cd into examples, configure aws with full permission, run the following:
zappa deploy dev_api
zappa deploy production
zappa deploy dev_event

This is when it fails.

## Your Environment

* Zappa version used: latest from git
* Operating System and Python version: OSX, Python 3.6.0
* The output of `pip freeze`:
argcomplete==1.9.2
awscli==1.11.177
base58==0.2.4
boto==2.48.0
boto3==1.4.7
botocore==1.7.35
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
colorama==0.3.7
docutils==0.14
dominate==2.3.1
durationpy==0.5
Flask==0.12.2
Flask-Bootstrap==3.3.7.1
Flask-SQLAlchemy==2.3.2
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
placebo==0.8.1
psycopg2==2.7.3.1
pyasn1==0.3.7
python-dateutil==2.6.1
python-magic==0.4.13
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.11
six==1.11.0
SQLAlchemy==1.1.14
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.1
Unidecode==0.4.21
urllib3==1.22
visitor==0.1.3
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3

* Link to your project (optional):

* Your `zappa_settings.py`: 
Identical to the repository but with eu-west-2 instead of us-west-2:

{
    "dev_event": {
       "project_name": "dev_event_zappa_test_flask_app",
       "keep_warm": false,
       "debug": true,
       "log_level": "DEBUG",
       "events": [{
         "function": "mymodule.myfunc",
         "expression": "rate(1 minute)"
         }],
       "aws_region": "eu-west-2",
       "s3_bucket": "zappa-ciao-dev-us-west-2",
       "lambda_handler": "app.lambda_handler",
       "use_apigateway": false,
       "http_methods": ["GET"],
       "parameter_depth": 1,
       "timeout_seconds": 300,
       "memory_size": 128,
       "use_precompiled_packages": true
    },
    "dev_api": {
       "project_name": "dev_api_zappa_test_flask_app",
       "keep_warm": false,
       "debug": true,
       "log_level": "DEBUG",
       "aws_region": "eu-west-2",
       "s3_bucket": "zappa-ciao-dev-us-west-2",
       "app_function": "app.app",
       "http_methods": ["GET"],
       "parameter_depth": 1,
       "timeout_seconds": 300,
       "memory_size": 128,
       "use_precompiled_packages": true
    },
    "prod": {
      "project_name": "dev_zappa_test_flask_app",
      "events": [{
        "function": "mymodule.myfunc",
        "expression": "rate(5 minutes)"
        }],
      "authorizer": {
        "function": "authmodule.lambda_handler"
      },
      "aws_region": "eu-west-2",
      "s3_bucket": "zappa-test-bucket",
      "app_function": "app.app",
      "http_methods": ["GET"],
      "parameter_depth": 1,
      "memory_size": 512,
      "use_precompiled_packages": true
    }
}

**Comment by monkut** [comment]
stale closing.
