### ISSUE TITLE
[Migrated] Check config

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#456]
Originally from: https://github.com/Miserlou/Zappa/issues/1215 by [daphee](https://github.com/daphee)

## Description
This adds a new function `verify_settings` to `cli.py` that is called when settings are loaded.
It goes through the settings dict and compares all used keys with a whitelist in `valid_settings.py`. For anything that isn't included in the whitelist a warning is printed including the valid setting with the closest [Levenshtein-Distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

I got the list of config options from [there](https://github.com/daphee/Zappa/tree/check-config#advanced-settings). I also looked through `load_settings` and checked that at least all options that were loaded there were included in the whitelist.

I am not sure how I'd write a test for that. While I guess this isn't very critical or complicated code it did get a little bit more messier than I initially thought.

## GitHub Issues
Suggested in issue #1165.

**Comment by monkut** [comment]
old migrated issue, considered resolved.

if not prs are welcome.

closing.
