### ISSUE TITLE
[Migrated] Feature/passing source ip

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#470]
Originally from: https://github.com/Miserlou/Zappa/issues/1249 by [danielwhatmuff](https://github.com/danielwhatmuff)

## Description
Passing env var for the $context.identity.sourceIp

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference

## GitHub Issues
Fairly small change discussed in slack but let me know if you want an issue for further discussion.

**Comment by monkut** [comment]
I don't see a problem adding the lambda context sourceIP, but currently the client IP should be available in "REMOTE_ADDR".

https://github.com/zappa/Zappa/blob/master/zappa/wsgi.py#L89-L96
