### ISSUE TITLE
[Migrated] Include boto3 or other modules in the Zip

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#475]
Originally from: https://github.com/Miserlou/Zappa/issues/1271 by [ferrangrau](https://github.com/ferrangrau)

## Context
I'm doing a lambda that need boto3 1.4.8 but actually aws lambda works with the 1.4.7 version, I can solve that including boto3 in the zip file but zappa doesn't allow me to do it.

## Possible Fix
At the beginning I try to add boto3 in the "include" parameter of the zappa config file but nothing happens, I modified the function "create_lambda_zip" in core.py to use the "include" param that now is unused and all works well.  The problem is that reading carefully the documentation I see that the objective of the parameter "include" of the config file is not this. 

Do you think its a good option include a parameter like "include" to can modify the default excluded files or modules?

## Your Environment
* Zappa version used: 0.45.1
* Operating System and Python version: ubuntu 17.10 and python 3.6
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`: 
```---
production:
  lambda_handler: run.handler
  apigateway_enabled: false
  keep_warm: false
  aws_region: null
  profile_name: sch-gov
  project_name: reserved-instan
  runtime: python3.6
  s3_bucket: reserved-instances-manager
  delete_local_zip: False
  include:
    - boto3
  events:
    - function: run.handler
      expression: rate(12 hours)
```

**Comment by monkut** [comment]
old migrated issue, considered resolved.

closing.
