### ISSUE TITLE
[Migrated] No deserialize

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#479]
Originally from: https://github.com/Miserlou/Zappa/issues/1281 by [jwkvam](https://github.com/jwkvam)

Before you submit this PR, please make sure that you meet these criteria

* If you made a new function, did you **write a good docstring** for it?
I attempted so, I didn't add anything to the README.

* Did you write a test for your new code?
I have not, I could use some pointers.

* Did you **make sure this code actually works on Lambda**, as well as locally?
Yes, I tested this on Lambda it works as expected.

* Did you test this code with both **Python 2.7** and **Python 3.6**? 
Only 3.6, I can test it out on 2.7.

## Description
This adds another kwarg to async.task `deserialize` which controls what arguments are passed to the user defined function. It follows the design of `capture_response` very closely.

This was simple to implement and try out that I went ahead and did it. Otherwise I would have waited to see how others felt about it in my original ticket.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1270

**Comment by monkut** [comment]
old pr task, pr in this repository isn't linked, closing.
