### ISSUE TITLE
[Migrated] Undeploy Leaves Behind Network Interfaces

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#481]
Originally from: https://github.com/Miserlou/Zappa/issues/1284 by [glassresistor](https://github.com/glassresistor)

Undeploy does not remove the ENI it creates when making a lambda function

## Context
This appears to be for 

## Expected Behavior
Undeploy removes everything it creates.

## Possible Fix
Remove the ENI or add tags to ease removal by other tools.

## Steps to Reproduce
Deploy app with a security group and subnets.  Undeploy and try and delete the security group.

## Your Environment

* Zappa version used: 0.44
* Operating System and Python version: 3.6

**Comment by mathieu-lemay** [comment]
Any updates on this? I'm facing the same issue with Zappa 0.54.1.
