### ISSUE TITLE
[Migrated] zappa deploy/update/package should be more verbose

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#484]
Originally from: https://github.com/Miserlou/Zappa/issues/1287 by [ceefour](https://github.com/ceefour)

Need more progress updates during operations, especially network.

## Context

e.g.

```
(venv) C:\Users\ceefour\git\samara\samaraweb>zappa update prd
Calling update for stage prd..
(then "hangs" for 1 or 2 minutes...)
```

of course this is due to my slow connection, and eventually it finishes. But if Zappa tells me exactly what it is doing, I wouldn't be so anxious.

## Expected Behavior

One message for every network operation, i.e. "Fetching https://something/ ..."

Multiple "quick" network operations can replace the same line.

`npm install (something)` is a good role model IMHO. I think `yum` and `apt` is also good at this.

While a "verbose" option is possible, I don't think it's needed, e.g. `npm install` by its default configuration does not need a "verbose" configuration, although it does have "even more verbose" configuration than default.

It also makes it easier to diagnose issues. For example in https://github.com/Miserlou/Zappa/issues/1286#issuecomment-350545457 , if Zappa tells me when it extracts a .tar.gz file, then I can know if it's extracting the wrong file, i.e. wrongly choosing a win_amd64 archive to extract when it should be a linux archive.

## Actual Behavior

Just long silence.

## Suggestions

1. `core.py > create_lambda_zip()`:

   "Packaging project to C:\Users\ceefour\AppData\Local\Temp\1512959502 ..."

2. `core.py > create_lambda_zip()`:

   Before `copytree()` and `copy_tree()`:

   "Copying A to B ..."

3. `copy.py > get_manylinux_wheel_url()`: Before downloading

   "Fetching https://pypi ..."

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Python 3.6 Windows 10 64 bit
* The output of `pip freeze`: (any)
* Your `zappa_settings.py`: (any)

**Comment by FievelArtist** [comment]
I'm having trouble with this too but it doesn't seem to be hanging, it seems stuck. are there any tips for troubleshooting how to progress past "Calling update for stage ..."?

**Comment by monkut** [comment]
considered stale.

closing.
