### ISSUE TITLE
[Migrated] For Pillow, need to also delete 'PIL'

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#485]
Originally from: https://github.com/Miserlou/Zappa/issues/1289 by [ceefour](https://github.com/ceefour)

Before you submit this PR, please make sure that you meet these criteria:
(yes, trivial change)

## Description

delete 'PIL' if package is Pillow

## GitHub Issues

See https://github.com/Miserlou/Zappa/issues/1286#issuecomment-350545457

**Comment by monkut** [comment]
not enough info.

closing.
