### ISSUE TITLE
[Migrated] Unable to deploy an hello world

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#488]
Originally from: https://github.com/Miserlou/Zappa/issues/1294 by [origliante](https://github.com/origliante)

## Context

I tried many times, ended up following a guide (https://www.cloudshiftstrategies.com/flasklambdalab--lesson1.html) to be extra sure, and trying both 2.7 and 3.6, but:

https://yjidix92nj.execute-api.eu-west-1.amazonaws.com/dev
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"

I have a venv with python36, zappa and flask...pretty straightforward.
Looks like something subtle somewhere. in .aws/config I have the keys and "region=eu-west-1"

## Expected Behavior
zappa to deploy a working app

## Actual Behavior
app not working - not being found.

## Possible Fix
n/a

## Steps to Reproduce
1. just follow the guide https://www.cloudshiftstrategies.com/flasklambdalab--lesson1.html

## Your Environment

* Zappa version used: latest
* Operating System and Python version: OSX python36
* The output of `pip freeze`: appdirs==1.4.3
argcomplete==1.9.2
base58==0.2.4
Beaker==1.8.1
boto3==1.5.0
botocore==1.8.14
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
Flask==0.12.2
future==0.16.0
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
Mako==1.0.7
MarkupSafe==0.23
mercurial==4.4.1
packaging==16.8
pbr==3.0.0
placebo==0.8.1
psycopg2==2.7.3.2
pyparsing==2.2.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
roman==2.0.0
s3transfer==0.1.12
six==1.10.0
stevedore==1.12.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.1.2
Unidecode==0.4.21
urllib3==1.22
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
* Link to your project (optional):
https://yjidix92nj.execute-api.eu-west-1.amazonaws.com/dev
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "app.__init__.app",
        "aws_region": "eu-west-1",
        "profile_name": "default",
        "project_name": "flask-lambda-la",
        "runtime": "python3.6",
        "s3_bucket": "zappa-d04akv1tn"
    }
}

**Comment by monkut** [comment]
old migrated issue.

closing.
