### ISSUE TITLE
[Migrated] Never leave log tailer unattended

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#500]
Originally from: https://github.com/Miserlou/Zappa/issues/1315 by [pkit](https://github.com/pkit)

## Context
Left log tailer running overnight accidentally, got my IP banned from `aws.amazon.com`

## Expected Behavior
Be able to access aws services

## Actual Behavior
No access to ANY aws serivce. I.e. full block for `*.aws.amazon.com` `*.amazonaws.com`
Changing IP address works around the issue (obviously).

## Possible Fix
Probably need either hammer log services less frequently (currently hardcoded as 1req/sec)
Or just stop if running for a long time

## Steps to Reproduce
1. Leave `zappa tail` for 24 hours from residential IP address.

## Your Environment
* Zappa version used: master
* Operating System and Python version: Ubuntu 16.04 py27

**Comment by monkut** [comment]
user error.

closing.
