### ISSUE TITLE
[Migrated] Retries and timeout for dependencies.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#501]
Originally from: https://github.com/Miserlou/Zappa/issues/1316 by [Tipuch](https://github.com/Tipuch)

## Description
Added retries and timeout optional parameters in the cli, a retry scheme when downloading dependencies and a different exception handling when downloading packages.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1235
https://github.com/Miserlou/Zappa/issues/1040

**Comment by monkut** [comment]
not enough info.

closing.
