### ISSUE TITLE
[Migrated] Refactor Django/Flask-specific behaviors into separate modules

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#503]
Originally from: https://github.com/Miserlou/Zappa/issues/1318 by [rgov](https://github.com/rgov)

It's really powerful that Django and Flask apps are automatically detected and adapted to work on AWS out of the box.

The functionality for this is woven throughout `core.py`, `cli.py`, and `utilities.py` which increases complexity for testing, debugging, adding new features, etc.

An improved design would probably involve refactoring the behaviors into separate modules that are less strongly-coupled. With a defined interface for how to tune Zappa for different frameworks, it would be easier to add support for others. Plus, the Zappa core and the framework plugins could be tested separately.

**Comment by monkut** [comment]
PRs welcome
