### ISSUE TITLE
[Migrated] Async: SNS Payload should be a string not bytes

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#507]
Originally from: https://github.com/Miserlou/Zappa/issues/1330 by [michelorengo](https://github.com/michelorengo)

The "SnsAsyncResponse._send" encodes the message in utf-8 and it works fine for Python 2, but in Python 3 the encoding produces bytes and cannot be used for the SNS payload.
## Context
- using the Asynchronous Task Execution with the SNS service 
AND
- Python 3

## Expected Behavior
The payload of the SNS notification should be str.

## Actual Behavior
In Python 3, "json.dumps(message).encode('utf-8')" returns bytes not str. Boto3 will then raise an exception that the parameters are invalid.

## Possible Fix
For Python 3:
"""
payload = json.dumps(message)
"""

**Comment by monkut** [comment]
stale migrated issue, closing
