### ISSUE TITLE
[Migrated] better config documentation and format

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#521]
Originally from: https://github.com/Miserlou/Zappa/issues/1371 by [jamesbeedy](https://github.com/jamesbeedy)

Zappa config documentation could be presented in a more consumable and more manageable  format. The current json bit defined in the readme is not maintainable, easily accessible, legible or testable.

## Context
Possibly we need a json-schema of some sort, and a md generator for Zappa configs?

I really like what the Juju team did [here](https://github.com/juju/layer-index) for the layer registry. 

We could very easily construct something similar to ^ for zappa config, which would bring great lifecycle, maintainability, and protocol to the Zappa configuration and config documentation.

How do others feel about this?

**Comment by monkut** [comment]
duplicate of
https://github.com/zappa/Zappa/issues/1150

closing.
