### ISSUE TITLE
[Migrated] start of config refactor

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#522]
Originally from: https://github.com/Miserlou/Zappa/issues/1372 by [jamesbeedy](https://github.com/jamesbeedy)

## Description

In light of #1371 we may want to better define a single source
of truth for configs alongside increasing the maintainability
and visibility of Zappa configuration.

* create config schema and bring forward a good amount of
https://github.com/juju/layer-index/blob/master/update_readme.py
* create example config `certificate_arn`

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1371

**Comment by monkut** [comment]
not enough info, closing.
