### ISSUE TITLE
[Migrated] An error occurred (IllegalLocationConstraintException) during zappa deploy

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#527]
Originally from: https://github.com/Miserlou/Zappa/issues/1398 by [mcmonster](https://github.com/mcmonster)

See https://github.com/Miserlou/Zappa/issues/569

I also experienced this issue when attempting to deploy following the out-of-the-box README commands. Zappa's deploy procedure is obfuscating the cause of the issue, namely that my bucket name is not unique. It would be nice if Zappa would suggest this as a possible issue source when the deploy command is ran.

**Comment by monkut** [comment]
stale migrated issue, closing.
