### ISSUE TITLE
[Migrated] Make an HTTPS request to endpoint instead of touch after deploy/update

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#534]
Originally from: https://github.com/Miserlou/Zappa/issues/1414 by [mcrowson](https://github.com/mcrowson)

## Context

When a zappa project is updated/deployed, zappa by default will "touch" the lambda to warm it up. This is helpful for speeding up initial requests.

Instead of doing a touch, zappa could make a GET request to some endpoint as specified in the zappa_settings.json (defaults to '/'). This would have the same effect as the touch to warm up the lambda, but the added benefit is that zappa could catch 500 errors right away. These 500 errors are currently one of the most common problems for migrating to zappa and often indicate missing or incompatible packages in the project for the lambda environment.

## Expected Behavior

Zappa informs users when their app returns a 500 error after deployment.

## Actual Behavior

Users must visit their app to initiate any errors. 

## Possible Fix

Instead of the touch functionality, make a request to a "touch_endpoint" setting, defaults to '/'. Zappa would only alert users if a 500 error is returned.

**Comment by Quidge** [comment]
@jneves This is already implemented with commit e7d0f8ec48869b8cadc6d2bae9288f9b640603b7

The issue name mentions `https`, which wouldn't happen by default with the implementation as the touch path/schema is provided by the config (from what I can tell at least this would be the case).

I cannot find coverage for the touch request or the CLI on update or failure. Barring that this issue can be closed I think. I think it would be reasonable to close now.

**Comment by monkut** [comment]
Already implemented, closing.
