### ISSUE TITLE
[Migrated] Endpoint request timed out  -- sometimes django application while calling apis on ios device

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#539]
Originally from: https://github.com/Miserlou/Zappa/issues/1431 by [codalprashant](https://github.com/codalprashant)

## Context
Django application deployed using zappa with production environment. Apis are delivered through django rest framework.
Python 3.6 

## Expected Behavior
When endpoint is called from any device, it should work

## Actual Behavior
Sometimes when the endpoint is called from the ios device, it returns endpoint request timeout.

## Possible Fix
Not sure what to do for this.

## Your Environment
"production": {
        "aws_region": "us-west-2",
        "django_settings": "xxxx.settings",
        "profile_name": "default",
        "s3_bucket": "zappa-xxxxxxxx",
        "runtime": "python3.6",
        "debug": true,
        "delete_local_zip": true,
        "delete_s3_zip": true,
        "exclude": ["*.rar"],
        "keep_warm": true,
        "keep_warm_expression": "rate(4 minutes)",
        "timeout_seconds": 300,
        "manage_roles": false,
        "role_name": "xxxxx-ZappaLambdaExecutionRole",
        "events": [{
            "function": "xxxxxxxx",
            "expression": "rate(7 days)"
        },{
            "function": "xxxxxxxx",
            "expression": "rate(7 days)"
        },{
            "function": "xxxxxxx",
            "expression": "rate(12 hours)"
        }],
        "slim_handler": true
    }

**Comment by monkut** [comment]
depends on your code implementation.

APIGW has a 30 second timeout.
