### ISSUE TITLE
[Migrated] Support AWS SSM Parameter store for Environment Variables

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#540]
Originally from: https://github.com/Miserlou/Zappa/issues/1432 by [OverlordQ](https://github.com/OverlordQ)

SSM Allows the creation of SecureString's which are variables protected by a KMS string which allows you to store sensitive information in a secure manner.[1]

This is the preferred method of storing environment or other data in plaintext as it stays encrypted in-flight.

**Comment by TreyWW** [comment]
Any ETA of this - or if it even be added? If not what would a better alternative be then using plaintext environment variables?
