### ISSUE TITLE
[Migrated] Still packing __pycache__ 

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#541]
Originally from: https://github.com/Miserlou/Zappa/issues/1433 by [Northshoot](https://github.com/Northshoot)

I am using lates zappa and set up environment as described in documentation.  

When examining zip file,  __pychache__ are packed in there.

according to https://github.com/Miserlou/Zappa/blob/cf8d09f7f286048e66c1f4da505876e2ea19c903/zappa/core.py

it should not be happening.

**Comment by monkut** [comment]
old migrated issue, assuming resolved.

closing.
