### ISSUE TITLE
[Migrated] Pipenv (if desired)

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#542]
Originally from: https://github.com/Miserlou/Zappa/issues/1435 by [kennethreitz42](https://github.com/kennethreitz42)

Ran the tests, using only the provided `Pipfile.lock` — they mostly passed, so I assume everything is working as intended.

```
Ran 94 tests in 171.589s

FAILED (errors=2)
```

Please dismiss if this isn't desired.

**Comment by monkut** [comment]
not enough info.

closing.
