### ISSUE TITLE
[Migrated] Zappa update fails with "import pip" command

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#547]
Originally from: https://github.com/Miserlou/Zappa/issues/1446 by [iwitaly](https://github.com/iwitaly)

I use Gitlab CI for updating my Zappa app with the following script.
```
  - export PIPENV_VENV_IN_PROJECT=true
  - pip install pipenv
  - pipenv install
  - export VIRTUAL_ENV=.venv/
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
  - export ENVIRONMENT=dev
  - pipenv run python manage.py migrate --settings=admin_dashboard.settings.dev
  - pipenv run zappa update dev
```
I also use ```lambci/lambda:build-python3.6``` as a base image.

Until today all updates were good, but today I've got this error
![image](https://user-images.githubusercontent.com/2273226/37558391-5e41fc94-2a24-11e8-9fdc-5884445e829a.png)

What could that mean?

**Comment by monkut** [comment]
old migrated issue, considered resolved.

closing.
