### ISSUE TITLE
[Migrated] Undocumented 'parameter_depth' setting in example/zappa_settings.json

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#552]
Originally from: https://github.com/Miserlou/Zappa/issues/1464 by [gmolau](https://github.com/gmolau)

## Context

Looking through the `example/zappa_settings.json` I found a [`"parameter_depth": 1`](https://github.com/Miserlou/Zappa/blob/7d38c157f575ab95c8dd25a9e42c9edaeb9c93a7/example/zappa_settings.json#L16) setting that is not documented in the README.md. Is this setting still relevant, and if so, what does it do?

(The example has also another undocumented setting `"http_methods": ["GET"]`, but I can roughly infer what that does.)

## Expected Behavior

The "Advanced Settings" section in the README has an explanation of this setting or it is removed from the example if it is deprecated.

## Actual Behavior

The Zappa documentation guides me to the example where I find settings that I can't make sense of:(

## Possible Fix

Document these settings or remove them from the example.

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: mac OS 10.13.3/Python 3.6.4

**Comment by monkut** [comment]
doens't appear to be used anywhere... but not a major issue at the moment.

closing.
