### ISSUE TITLE
[Migrated] import routes causing 404 error

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#558]
Originally from: https://github.com/Miserlou/Zappa/issues/1475 by [johnedstone](https://github.com/johnedstone)

What is it about the import statement `from app import routes` in this [example](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) that causes the app to fail (returns 404) when deployed as a lambda package with Zappa?

Later: I just realized that if I changed the `app_function` value in `zappa_settings.json` generated by `zappa init` to `microblog.app` (or `app.app` ) that it would work.  The default: `"app_function": "microblog.__init__.app"`, though it works with `flask run`, doesn't work when deployed with zappa.   You can close this issue.   Thanks again for this awesome project!

**Comment by monkut** [comment]
not enough info.

closing.
