### ISSUE TITLE
[Migrated] Release plan for Zappa

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#561]
Originally from: https://github.com/Miserlou/Zappa/issues/1480 by [efimerdlerkravitz](https://github.com/efimerdlerkravitz)

This is not an actual bug, unfortunately I don't know exactly where to ask it. 
Any release plan for Zappa ? When is the next version suppose to be released ?

**Comment by monkut** [comment]
join the slack.

https://slackautoinviter.herokuapp.com

closing.
