### ISSUE TITLE
[Migrated] Flask 1.0 is out

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#569]
Originally from: https://github.com/Miserlou/Zappa/issues/1493 by [mnp](https://github.com/mnp)

## Context

There's a new 1.0 release of Flask:  https://www.palletsprojects.com/blog/flask-1-0-released/

## Expected Behavior

It offers some new features which might need to be evaluated and integrated.

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by monkut** [comment]
thanks for the announcement.
Not a specific feature request or bug.

closing.
