### ISSUE TITLE
[Migrated] How to know when a lambda fails because timeout and also when it is out of memory

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#570]
Originally from: https://github.com/Miserlou/Zappa/issues/1494 by [alexanderfanz](https://github.com/alexanderfanz)

I have a process that feed a lambda and some times it is over fed (bug that I cannot prevent :( ), this causes the lambda sometimes run out of memory and others it just keep running until it dies without finish the job.
I would like to know if there is a way to know when one this things happens.

Thanks in advance

[The question in StackOverFlow](https://stackoverflow.com/q/50181524/4855401)

**Comment by monkut** [comment]
Check your cloudwatch logs.

closing.
