### ISSUE TITLE
[Migrated] static files has 403 () errors in the console

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#575]
Originally from: https://github.com/Miserlou/Zappa/issues/1503 by [izzy23-6](https://github.com/izzy23-6)

## Context
I am trying to deploy a Django backend/VueJs frontend website.  It is a very basic website that uses a postgresql database. When I run my invoke url(xxxxxxx.execute-api.us-east-1.amazonaws.com/dev) in the browser, the result is a blank page, and in the console, I have these errors - GET https://xxxxxx.execute-api.us-east-1.amazonaws.com/static/static/css/app.b161c75d6c5fa852dc6268b6285777e6.css 403 (),
GET https://xxxxxx.execute-api.us-east-1.amazonaws.com/static/static/js/app.441ac05ed149e4bc4061.js 403 (), GET https://xxxxxx.execute-api.us-east-1.amazonaws.com/static/static/css/app.b161c75d6c5fa852dc6268b6285777e6.css 403 (), GET https://xxxxxx.execute-api.us-east-1.amazonaws.com/favicon.ico 403 ()

## Expected Behavior
I expect the page to load with static files.

## Actual Behavior

Blank page with .js, .css 403 () errors.

## Possible Fix
Not sure!

## Your Environment
argcomplete==1.9.2
astroid==1.6.3
autopep8==1.3.5
awscli==1.15.16
base58==0.2.4
boto3==1.7.16
botocore==1.10.16
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
colorama==0.3.7
coverage==4.5.1
Django==2.0.5
django-cors-headers==2.2.0
django-storages==1.6.6
django-webpack-loader==0.5.0
djangorestframework==3.8.2
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
isort==4.3.4
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
lazy-object-proxy==1.3.1
mccabe==0.6.1
Pillow==5.1.0
placebo==0.8.1
psycopg2==2.7.4
pyasn1==0.4.2
pycodestyle==2.4.0
PyJWT==1.6.1
pylint==1.8.4
PySocks==1.6.8
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.1
twilio==6.13.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wrapt==1.10.11
wsgi-request-logger==0.4.6
zappa==0.45.1
zappa-django-utils==0.3.1

## zappa_settings.json
{
    "dev": {
        "aws_region": "us-east-1",
        "django_settings": "project.settings",
        "profile_name": "default",
        "project_name": "portfolio-website",
        "runtime": "python3.6",
        "s3_bucket": "zappa-izzy2323",
        "api_key_required": false,
          "vpc_config": {
            "SubnetIds": ["subnet-81xxxxx", "subnet-axxxxx"],
            "SecurityGroupIds": ["sg-7xxxxxx"]
},
        "certificate_arn":
            "arn:aws:acm:us-east-1:953xxxxx7561:certificate/95xx7x04-e733-4xx3-8e0e-a9bxxxxxx",
            "domain": "israeldclark.com",
        "exclude": [
            ".vscode",
            "build",
            "config",            
            "cypress",
            "node_modules",
            "src"

        ]
    }
}

**Comment by monkut** [comment]
I assume that your apigateway prefix is not properly defined in your endpoint configuration.

Closing.
