### ISSUE TITLE
[Migrated] How to pass kwargs to scheduled function?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#578]
Originally from: https://github.com/Miserlou/Zappa/issues/1511 by [trickidicki](https://github.com/trickidicki)

I tried following the docs:

```
def myfun(event, context):
  try:
    args = event.get('kwargs')
    # do stuff
    return true
  except Exception, error:
    logging.error("myfun error: %s" % str(error))
    return false
```
 with unit test:
```
class MyTest(unittest.TestCase):
    def test_fun(self):
        event={}
        event['kwargs']={
            "arg1": "abc",
            "arg2": "123"
        }
        assert( myfn(event, context={}) )

```

But when I upload with Zappa I'm getting the following error message:
`>>zappa tail`

`myfun error: 'NoneType' object has no attribute '__getitem__'`

What's the correct way to pass kwargs? Thanks for your help.

**Comment by jolo-dev** [comment]
Hi @jneves,

I think what you are looking for is [here](https://github.com/zappa/Zappa#executing-in-response-to-aws-events) (at the `kwargs`- section.

**Comment by monkut** [comment]
As mentioned in the above comment, this is supported to some degree.
If something else is desired raise a new issue.

closing.
