### ISSUE TITLE
[Migrated] pipenv install zappa fails

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#585]
Originally from: https://github.com/Miserlou/Zappa/issues/1528 by [dins](https://github.com/dins)

Installing zappa with pipenv fails because of futures==3.2.0 dependency cannot not be met.

## Context
Installing zappa on new pipenv virtualenv.

## Expected Behavior
Should install zappa with dependencies.

## Actual Behavior
```
Could not find a version that satisfies the requirement futures==3.2.0 (from -r /var/folders/zx/zw2xhqr13nv4t_p386tlwnlr0000gn/T/pipenv-04ld0l04-requirements/pipenv-wgujth9u-requirement.txt (line 1)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
```

## Steps to Reproduce
```
pipenv --three # Using python 3.6.5 on OSX
pipenv install zappa
```

## Your Environment
* Zappa version used: 0.46.0
* Operating System and Python version: OSX High Sierra, python 3.6.5
* Pipenv version: 2018.05.18

**Comment by monkut** [comment]
old migrated issue, considered resolved.

closing.
