### ISSUE TITLE
[Migrated] Encoding of cyrillic GET parameters (regression in 0.46)

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#588]
Originally from: https://github.com/Miserlou/Zappa/issues/1532 by [lampslave](https://github.com/lampslave)

Python 2.7, trouble appears only for real lambda (not for docker container).

I use Django application with simple search form. If I type 'тест' ('test') and submit form, url becomes `/?q=тест` for both <0.46 and 0.46, but for 0.46 value in form becomes `ÑÐµÑÑ` instead of 'тест' and search results will not be found.

**Comment by monkut** [comment]
python 2.7 no longer supported.

closing.
