### ISSUE TITLE
[Migrated] A GET request to '/' yielded a 502 response code

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#590]
Originally from: https://github.com/Miserlou/Zappa/issues/1536 by [sourabhsriom](https://github.com/sourabhsriom)

I am trying to deploy the first example app with Flask-Ask, It looks like everything works good but after the Deploying API statement I get the following error : 

Error: Warning! Status check on the deployed lambda failed. A GET request to '/'
 yielded a 502 response code.

## Context
Here is the code I am executing with minor changes to the sample app

from flask import Flask
from flask_ask import Ask, question, statement, session
import pyodbc

app = Flask(__name__)
ask = Ask(app, '/')

@ask.intent('HelloIntent')
def hello(firstname):
    speech_text = "Hello %s" % firstname
    return statement(speech_text).simple_card('Hello', speech_text)

@ask.intent('ByeIntent')
def bye():
    return statement("Ok, goodBye!")

@ask.intent('FarziIntent')
def farzi():
    return statement("This is just a random fact!")

if __name__ == '__main__':
    app.run()

Python 3.6 is the version I am running
## Expected Behavior
Ideally it should give me a link I can use to configure as an endpoint

## Actual Behavior
Error: Warning! Status check on the deployed lambda failed. A GET request to '/'
 yielded a 502 response code.

## Your Environment

* Zappa version used: 0.46.1
* Operating System and Python version: Windows 7, Python 3.6
* The output of `pip freeze`: 

aniso8601==1.2.0
argcomplete==1.9.3
asn1crypto==0.24.0
awscli==1.15.39
base58==1.0.0
boto3==1.7.39
botocore==1.10.39
certifi==2018.4.16
cffi==1.11.5
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
colorama==0.3.9
cryptography==2.2.2
docutils==0.14
durationpy==0.5
Flask==0.12.1
Flask-Ask==0.9.8
future==0.16.0
hjson==3.0.1
idna==2.7
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.0
placebo==0.8.1
pyasn1==0.4.3
pycparser==2.18
pyOpenSSL==17.0.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.19.1
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.3.0
Unidecode==1.0.22
urllib3==1.23
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.46.1
* Link to your project (optional):
* Your `zappa_settings.py`: 

{
    "testdev": {
        "app_function": "app.app",
        "profile_name": null,
        "project_name": "basic",
        "runtime": "python3.6",
        "s3_bucket": "zappa-vb8m8hwzy",
		"aws_region": "us-east-1",
		"api_key_required": false,
		"api_key":"MY_KEY"
    }
}

Could someone please help me out here?

**Comment by monkut** [comment]
common issue.

closing.
