### ISSUE TITLE
[Migrated] Allow Configuration of Lambda Name

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#605]
Originally from: https://github.com/Miserlou/Zappa/issues/1556 by [TimOrme](https://github.com/TimOrme)

## Context
We'd ideally like to be able to configure the name of the lambda that zappa creates/uses. Right now, this is hardcoded to <project_name>-<api_stage>.

We'd like to be able to override this default behavior with a lambda name of our choosing.  This would also potentially allow us to create the lambda outside of zappa and then only allow zappa access to update functions rather than create them, though Im not sure of the other implications of that approach.  Either way, this seems like it would be a nice feature to have.

## Expected Behavior
We could add an optional lambda_name function to the configuration file, which would be used in place of the default.

## Possible Fix
I think this should be relatively straightforward to implement.

https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L1989

Could be changed to:

```python
self.lambda_name = self.stage_config.get('lambda_name', slugify.slugify(self.project_name + '-' + self.api_stage))
```

**Comment by deanq** [comment]
Bump

**Comment by monkut** [comment]
Lambda function is defined as: <project_name>-<api_stage>

you can define your project_name and stage_name.
You are free to create the lamba function outside of zappa and only use the packaging done by zappa.
If there are issues with that please create a new issue.

closing.
