### ISSUE TITLE
[Migrated] Lambdat tagging

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#621]
Originally from: https://github.com/Miserlou/Zappa/issues/1584 by [kukui](https://github.com/kukui)

This PR adds tagging of lambda functions when using zappa deploy and update
zappa deploy --lambda-tags '{"alpha":"beta"}'
zappa update --lambda-tags '{"hash":"commithash"}'

Relevant tickets
https://github.com/Miserlou/Zappa/issues/1583
https://github.com/Miserlou/Zappa/issues/860
https://github.com/Miserlou/Zappa/issues/700

**Comment by monkut** [comment]
duplicate

closing
