### ISSUE TITLE
[Migrated] Specify unit divisor for tqdm

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#624]
Originally from: https://github.com/Miserlou/Zappa/issues/1587 by [gaul](https://github.com/gaul)

Previously, Zappa formatted in both SI and binary:

```
Uploading githubwatch-dev-1534354789.zip (14.8MiB)..
100%|###########################| 15.5M/15.5M [00:03<00:00, 4.54MiB/s]
```

**Comment by monkut** [comment]
not enough info 

clsoing.
