### ISSUE TITLE
[Migrated] Organize Zappa community governance structure?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#636]
Originally from: https://github.com/Miserlou/Zappa/issues/1610 by [brylie](https://github.com/brylie)

As an open source project matures, and in order to promote the longevity of the project, it is oftentimes useful to define a community governance structure.

Currently, Zappa has a single primary maintainer/contributor, and the [contributions seem to be dwindling a bit](https://github.com/Miserlou/Zappa/graphs/contributors).

With gratitude, and no disrespect, to @Miserlou, may we discuss what a community governance structure for Zappa would look like?

**Comment by monkut** [comment]
forked and community driven... still needs work.

closing.
