### ISSUE TITLE
[Migrated] Temporary S3 Bucket is not deleted

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#647]
Originally from: https://github.com/Miserlou/Zappa/issues/1643 by [chiqunz](https://github.com/chiqunz)

## Context

In my `zappa_setting.yml`, I set `slim_handler=false` and `bucket_name=None`. And it turns out that after several months, my S3 reaches bucket limit(200). It turns out that most of those buckets are created by Zappa and are empty.
## Expected Behavior

With `slim_handler=false` and `bucket_name=None`, there should not be any s3 bucket created /left after deployment succeed.
## Actual Behavior

Zappa will create a temporary empty s3 bucket and leave it there. One work around is prescribing the `bucket_name` in `zappa_setting.yml` but it would be better to automatically delete the temp bucket in S3.
## Possible Fix

change this code to delete bucket with boto3 https://github.com/Miserlou/Zappa/blob/361578322f082f927ae50782bfdf1e9717376515/zappa/core.py#L1011
## Steps to Reproduce

1. Set `slim_handler=false` and `bucket_name=None` in zappa_setting.yml
2. Deploy lambda function
3. Check s3 if there is an empty zappa bucket

## Your Environment

* Zappa version used: 0.46.1
* Operating System and Python version: linux, python 3.6
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by monkut** [comment]
source code for zappa is stored in a bucket, if you have 200 functions with seperate bucket names, you will have 200 buckets.

closing.
