### ISSUE TITLE
[Migrated] module 'pip' has no attribute 'get_installed_distributions'

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#655]
Originally from: https://github.com/Miserlou/Zappa/issues/1658 by [nabaz](https://github.com/nabaz)

## module 'pip' has no attribute 'get_installed_distributions' no matter what you do you get this error, so frustrating, makes you not use zappa anymore it's unfortunate 

3.6
## Expected Behavior

module 'pip' has no attribute 'get_installed_distributions'
## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by monkut** [comment]
not enough info

closing.
