### ISSUE TITLE
[Migrated] In the CLI, validate the user-provided S3 bucket name

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#665]
Originally from: https://github.com/Miserlou/Zappa/issues/1688 by [agussman](https://github.com/agussman)

I think it would be helpful to confirm that the S3 bucket names meets the naming requirements.

I created a feature branch that addresses this: https://github.com/agussman/Zappa/tree/feature/validate_s3_bucket_name

Can I submit it as a PR?

**Comment by monkut** [comment]
yes you can submit a pr.

old migrated issue.
closing.
