### ISSUE TITLE
[Migrated] invoke function launches new lambdas after ~300 seconds

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#667]
Originally from: https://github.com/Miserlou/Zappa/issues/1691 by [kylegibson](https://github.com/kylegibson)

## Context

I have a zappa environment configured for a timeout of 900 seconds. I used `zappa invoke <stage> function` to invoke a lambda instance running a particular function, one that takes over 400 seconds to complete. I was tailing the logs during the process.

## Expected Behavior

Only 1 lambda instance should be launched.

## Actual Behavior

After about 300 seconds, another lambda instance was launched. The logs clearly have "Zappa Event: {'command': '...'}" twice, even though I only ran `invoke` once. 

## Possible Fix

https://github.com/boto/boto3/issues/1104

## Your Environment
* Zappa version used: 0.47
* Operating System and Python version: ubuntu 16.04, pytohn 3.6.5

**Comment by monkut** [comment]
If your function fails lambda will retry.

closing.
