### ISSUE TITLE
[Migrated] Is it Possible to handle sessions using zappa in AWS Lambda

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#676]
Originally from: https://github.com/Miserlou/Zappa/issues/1728 by [saikumar-neelam](https://github.com/saikumar-neelam)

Hi,
I have created a web application and deployed on AWS using zappa. I was unable to handle the sessions. Is it possible to handle sessions using zappa on AWS? If possible, How?

Thanks & Regards,

N Sai Kumar

**Comment by monkut** [comment]
old migrated issue, not enough info.

closing.
