### ISSUE TITLE
[Migrated] Add a command for setting environment variables.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#678]
Originally from: https://github.com/Miserlou/Zappa/issues/1731 by [youcandanch](https://github.com/youcandanch)

## TODO
- [ ] Add tests around new command.
- [ ] Solicit feedback on naming.

## Description
This is a little bit of a divergence from what was brought up in #837, but I think it's another avenue for how to solve the problem as described in that issue. This PR introduces a new command: `zappa set-environment-variable`. I'm a little concerned that the name is over-verbose, but figured I'd err on the side of being as explicit as possible.

For our particular use case, this would be valuable in CI for updating variables we expect in each environment (things like the SHA associated with the release, the time of deployment, etc.), but I can imagine it'd be helpful for a few different reasons.

The command takes three arguments:
`--key`: the key of the environment variable to set
`--value`: the value to set the environment variable to
`--overwrite`: a boolean indicating that, if an environment variable _already exists_ with the provided key, it should be overwritten. In the absence of this flag, a `KeyError` will be raised. (I'm not that thrilled with using `KeyError`, but couldn't think of anything better.

Tested as working in 2.7 and 3.6 (and 3.7, with a quick `__init__.py` tweak, since 3.7 support is coming down the pipeline).

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/837

**Comment by monkut** [comment]
It may be helpful to have a utility command, but I think at the moment it's out of scope.

I've created a gist that does what you are looking for though... really I think the AWS cli should make it easier to set envars for lambda though.

https://gist.github.com/monkut/cd16a8c532694bac4383d53978a47373
