### ISSUE TITLE
[Migrated] Error: Zappa requires an active virtual environment with dockerfiles

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#684]
Originally from: https://github.com/Miserlou/Zappa/issues/1744 by [thenetimp](https://github.com/thenetimp)

I use dockerfile for all our development.  Seems like an unneeded step for me to have a virtual environment inside our docker containers.  There should really be an option for us to turn this off.

**Comment by vedmant** [comment]
I have the same issue, is this package even maintaned?

**Comment by hcuk94** [comment]
+1. I am just using the Zappa package command in a CI workflow. Using a venv seems unnecessary
