### ISSUE TITLE
[Migrated] fix: Decoding issue for windows in zappa init

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#685]
Originally from: https://github.com/Miserlou/Zappa/issues/1746 by [penguindustin](https://github.com/penguindustin)

## Description

Some windows machines can't decode the title text from `zappa init` causing it to fail. This change should allow for a safe alternative text to be displayed in those cases.

## GitHub Issues
[#825](https://github.com/Miserlou/Zappa/issues/825)

**Comment by monkut** [comment]
not enough info

closing.
