### ISSUE TITLE
[Migrated] Add lambda layers support

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#688]
Originally from: https://github.com/Miserlou/Zappa/issues/1752 by [piotrdrazikowski](https://github.com/piotrdrazikowski)

## Description
Lambda layers support
Added `layers` keyword in zappa_settings.json, put a list of ARN's there and zappa will add them to your function.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1716

**Comment by MartijnGevaert** [comment]
This could be really cool in combination with this project created in 2019 (one year after start of this ticket):
https://github.com/keithrozario/Klayers

**Comment by eivaremir** [comment]
Hi Guys, any updates regarding this?
