### ISSUE TITLE
[Migrated] Document (implement?) way to use Zappa with Flask app factories

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#693]
Originally from: https://github.com/Miserlou/Zappa/issues/1771 by [gmolau](https://github.com/gmolau)

[App factories](http://flask.pocoo.org/docs/1.0/patterns/appfactories/) are the recommended way to structure Flask applications, but the Zappa docs (the README) make not mention of them and setting the `app_function` to the factory does not work. I'm sure it must be possible to get this to work somehow, but it would be nice if it could be more clearly stated.

## Context

Zappa + Flask

## Expected Behavior

Ideally the init script should pick up the factory function automatically and do the right thing, but at least the docs should give a hint on how to do it manually. 

## Actual Behavior

`zappa init` claims it has found an `<project>.__init__.app` object, even though no such object exists, only a `create_app` function that would return an app object.

## Steps to Reproduce

1. Setup a Flask app with the app factory pattern
2. Run `zappa init` and `zappa deploy` with all the default settings
3. Calling the endpoint results in an exception

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: macOS 10.14, Python 3.6.4
* The output of `pip freeze`: Only Flask and Zappa
* Link to your project (optional):
* Your `zappa_settings.py`: Default settings created by zappa init

**Comment by Ecalzo** [comment]
@jneves the workaround for this that I have come across is some `run.py` file that looks like the following:

```
# run.py
from name_of_my_app import create_app

app = create_app()

if __name__ == "__main__":
    app.run()
```

and update the settings:
```
# zappa_settings.json
{
    "dev": {
        "app_function": "run.app",
        ...
    }
}
```

This at least got me up and running with minimal change to my app structure. Curious if there is another more direct method.

**Comment by monkut** [comment]
appears to be resolved.

for flask you need to specify the app as mentioned above.
