### ISSUE TITLE
[Migrated] Flask-like app factory support

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#695]
Originally from: https://github.com/Miserlou/Zappa/issues/1775 by [fcicc](https://github.com/fcicc)

# Description 

How to use application factories in Zappa:

* app.py
`def create_app():`
&nbsp;&nbsp;&nbsp;&nbsp;`app = Flask()`
&nbsp;&nbsp;&nbsp;&nbsp;`#define settings, db, routes, ...`
&nbsp;&nbsp;&nbsp;&nbsp;`return app`

* zappa_settings.json
`{`
&nbsp;&nbsp;&nbsp;&nbsp;`"app_function": "app.create_app"`
`}`

# GitHub Issue

#1771

**Comment by monkut** [comment]
not enough info

closing.
