### ISSUE TITLE
[Migrated] Just a notice.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#697]
Originally from: https://github.com/Miserlou/Zappa/issues/1778 by [laimonassutkus](https://github.com/laimonassutkus)

I think you have updated the source code to not use one "mega" cookie, so you should update the documentation where it says:

~~~Packing and Base58 encoding multiple cookies into a single cookie because we can only map one kind.~~~

**Comment by monkut** [comment]
not enough info

closing.
