### ISSUE TITLE
[Migrated] Testing Zappa apps

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#701]
Originally from: https://github.com/Miserlou/Zappa/issues/1787 by [fbidu](https://github.com/fbidu)

## Context
Hello,

Today I got myself almost banging my head against the wall because I've misconfigured `app_function` in `zappa_settings.json`. The errors I was getting were cryptic. A simple "NoneType is not callable". Not an import error of some sorts, just that.

I'm a little familiar with that sort of error in Flask applications - my case - so I set out looking for places were I might have been exposing invalid variables and so on. Turns out that instead of pointing to a Flask app I was pointing to the module where my app resides.

Dumb mistake, totally my fault but this is so preventable. Zappa could do something like checking if the string set as `app_function` is indeed something it can use. It could be done by default before every update or just exposed as some command like `zappa test` or something.

I took a look around the issues and docs but didn't find anything regarding this kind of behaviour. All in all, I'd be happy to help!

## Expected Behavior

Zappa could provide something that checks against errors in the settings or some facilities to allow testing.
## Actual Behavior

It does not :(

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: 3.6.7
* The output of `pip freeze`: 

appdirs==1.4.3
argcomplete==1.9.3
astroid==2.2.0.dev1
atomicwrites==1.3.0
attrs==18.2.0
black==18.9b0
boto3==1.9.102
botocore==1.12.102
cachetools==3.1.0
certifi==2018.11.29
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
docutils==0.14
durationpy==0.5
Flask==1.0.2
future==0.16.0
google-api-core==1.8.0
google-auth==1.6.3
google-cloud-bigquery==1.9.0
google-cloud-core==0.29.1
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0b9
hjson==3.0.1
idna==2.8
isort==4.3.9
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==6.0.0
placebo==0.9.0
pluggy==0.9.0
protobuf==3.7.0rc3
py==1.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pylint==2.3.0.dev2
pymongo==3.7.2
pytest==4.3.0
pytest-mock==1.10.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.9
PyYAML==3.13
requests==2.21.0
rsa==4.0
s3transfer==0.2.0
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.5
typed-ast==1.2.0
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.11.1
wsgi-request-logger==0.4.6
zappa==0.47.1

* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by monkut** [comment]
make sure you app runs as expected prior to deploy.

closing.
