### ISSUE TITLE
[Migrated]  - mysqlclient==1.4.2.post1: Warning! Using precompiled lambda package version 1.3.12 instead!

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#702]
Originally from: https://github.com/Miserlou/Zappa/issues/1788 by [Vadorequest](https://github.com/Vadorequest)

I have the following package in requirements.txt:

    mysqlclient==1.4.2.post1

When I run a `zappa update` it displays the following

```bash
Downloading and installing dependencies..
 - mysqlclient==1.4.2.post1: Warning! Using precompiled lambda package version 1.3.12 instead!
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.

```

I just wonder why, is it an issue?

**Comment by monkut** [comment]
old lambda_packages issue.

closing.
