### ISSUE TITLE
[Migrated] [Feature] Use lambda-warmer-py decorator to keep more than one lambda instance warm.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#703]
Originally from: https://github.com/Miserlou/Zappa/issues/1790 by [M0dM](https://github.com/M0dM)

Hi,

## Context
I am using python3.6 and I want 100 lambda to be warm at all time.

## Expected Behavior
Keep 100 lambda warm to serve 100 requests concurrently without cold-start.

## Actual Behavior
Current keep warm implementation  is only keeping warm a single lambda instance using lambdawrapper could make this a lot more customizable.

## Possible Fix
Wrap lambda function using this project ?
https://github.com/robhowley/lambda-warmer-py

**Comment by Yaronn44** [comment]
This issue seems duplicated with #343. Can we close one to keep the discussion in one place only ?

I wanted to know if someone found a solution to this because I'm really interested about this feature.
AWS Provisionned Concurrency seems to be THE solution but it's not really cheap...
