### ISSUE TITLE
[Migrated] Opening UTF-8 files on Windows machines

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#710]
Originally from: https://github.com/Miserlou/Zappa/issues/1801 by [drummonds](https://github.com/drummonds)

If you try and do local install eg via pip / pipenv on a Windows machine you get a UnicodeDecodeError (see end).
## Context
Using Python3.6.  Although correctly using io.open, encoding is not specified eg like this:

```python
with open('README.md', encoding='utf-8') as readme_file:
    long_description = readme_file.read()
```

## Expected Behavior
Should install

## Actual Behavior
UnicodeDecodeError

## Possible Fix
https://github.com/drummonds/Zappa/commit/244b1e1471a14607101b3fb9e1e6079907c314f8

I have tested on travis and all tests pass.  I haven't extended the test coverage.

I am working on this.

## Steps to Reproduce
`pip install C:/Users/HumphreyDrummond/ForkedProjects/zappa`

where version is pre patch

## Your Environment
- Windows 10
- Python 3.6
- Version 0.47.1

# Sample Error Message
Processing c:\users\humphreydrummond\forkedprojects\zappa
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HUMPHR~1\AppData\Local\Temp\pip-req-build-qe6qv2o3\setup.py", line 8, in <module>
        long_description = readme_file.read()
      File "c:\users\humphreydrummond\.virtualenvs\bytestone.co.uk-6mzjitax\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 70907: character maps to <undefined>

**Comment by monkut** [comment]
old migrated issue, considered resolved.

closing.
