### ISSUE TITLE
[Migrated] Update asynchronous invocation payload limit to 256k

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#712]
Originally from: https://github.com/Miserlou/Zappa/issues/1806 by [mojimi](https://github.com/mojimi)

As per here : https://docs.aws.amazon.com/lambda/latest/dg/limits.html

New limit is now 256kb

zappa\async.py line 179 is barring it at 128kb

**Comment by monkut** [comment]
Already supported
> LAMBDA_ASYNC_PAYLOAD_LIMIT = 256000

closing.
