### ISSUE TITLE
[Migrated] Unable to upload large FileField objects using Django admin.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#720]
Originally from: https://github.com/Miserlou/Zappa/issues/1826 by [rmarshall31](https://github.com/rmarshall31)

When uploading a [FileField](https://docs.djangoproject.com/en/2.1/ref/models/fields/#filefield) object using the Django admin site, the upload fails if the file is larger than a couple MB.

## Context
The error received is `{"message": "Request Too Long"}` if the file is ~5-10MB. Files above 10MB fail with `HTTP content length exceeded 10485760 bytes.` Smaller files (less than ~2MB) work fine.

I'm using [django-s3-storage](https://github.com/etianen/django-s3-storage) for static and media file storage.

## Expected Behavior
The upload should succeed.

## Actual Behavior
The upload fails.

## Possible Fix
I believe this is a limitation of API gateway. The solution seems to be to upload files directly to S3, but I haven't found an elegant way to accomplish this using the Django admin site.

I tried [zappa_file_widget](https://github.com/anush0247/zappa-file-widget), but it's out of date and doesn't work with the latest version of Django. I have to believe that I'm not the only person that has run into this and there's a better solution, otherwise I will dig into this project.

## Steps to Reproduce
I have a fairly basic project at this point, the model includes a FileField. I'm using django-s3-storage. I believe the issue could be recreated using any basic project with a FileField in the model. I followed the [Edgar Roman walkthrough](https://edgarroman.github.io/zappa-django-guide/) to arrive at my current configuration.

## Your Environment
I'm deploying using python 3.6 [lambci docker container](https://hub.docker.com/r/lambci/lambda/).
```bash
> pip freeze
argcomplete==1.9.3
boto3==1.9.116
botocore==1.12.116
certifi==2019.3.9
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
defusedxml==0.5.0
Django==2.1.7
django-cleanup==3.2.0
django-s3-storage==0.12.4
django-storages==1.6.6
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.8
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
mysqlclient==1.4.2.post1
oauthlib==3.0.1
placebo==0.9.0
PyJWT==1.7.1
python-dateutil==2.7.3
python-slugify==1.2.4
python3-openid==3.1.0
pytz==2018.9
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
s3transfer==0.2.0
six==1.11.0
social-auth-app-django==3.1.0
social-auth-core==3.1.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.5
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.15.0
wsgi-request-logger==0.4.6
zappa==0.47.1
zappa-django-utils==0.4.0
```

**Comment by monkut** [comment]
APIGW has a 10MB or so payload limit.

Take a look at the following project for uploading files directly to s3.
https://github.com/bradleyg/django-s3direct
