### ISSUE TITLE
[Migrated] Zappa deployment throwing 404 error

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#730]
Originally from: https://github.com/Miserlou/Zappa/issues/1847 by [ctippur](https://github.com/ctippur)

## Context
I am using connexion for my Flask application. I am getting a 404 error \ while accessing teh endpoint. I have tried to dummy down the issue I am facing at https://github.com/ctippur/zappa-connexion-sample

I have had success deploying applications using connexion and zappa. I am trying to use newer versions of the libraries to deploy code. Looks like the app gets initialized but I get a 404 error on any endpoint.
I am able to test locally without any issues.
I also downloaded the lambda code and was able to run the application locally as well.

My python version is 3.6.3
Zappa version - 0.48.2
## Expected Behavior

The '/' endpoint should return the current time.

## Actual Behavior

I get a 404 error.
## Steps to Reproduce

https://github.com/ctippur/zappa-connexion-sample/blob/master/README.md

## Your Environment

* Zappa version used: 0.48.2
* Operating System and Python version: MacOS High Sierra 10.13.2
* The output of `pip freeze`:https://github.com/ctippur/zappa-connexion-sample/blob/master/requirements.txt
* Link to your project (optional): https://github.com/ctippur/zappa-connexion-sample
* Your `zappa_settings.py`:  https://github.com/ctippur/zappa-connexion-sample/blob/master/zappa_settings.json

**Comment by monkut** [comment]
make sure stage is included in the request.

not enough info.

closing.
