### ISSUE TITLE
[Migrated] "keep_warm":"true" settings does`nt work

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#735]
Originally from: https://github.com/Miserlou/Zappa/issues/1854 by [navenchary](https://github.com/navenchary)

## I have written an API using django rest framework. I have deployed it using aws zappa. It takes at least 7 to 10 seconds to respond if I leave the API without using for 15 minutes.

I am usnig django 2.1.3 and djangorestframework 3.9.0. I am running into the cold start issue. I have  tried "keep_warm" settings in zappa_settings.json file. But it does not solve my problem. I can see the lambda call back function is called every 5 minutes but still my API is taking minimum 8  seconds to respond for the first time. I am unable to solve this. 

Please help.

## Your Environment

* Zappa version used: 0.48.2
* Operating System and Python version: fedora linux python3.6
* Your `zappa_settings.py`: 
{
    "dev": {
        "aws_region": "ap-south-1",
        "django_settings": "trubloqapi.settings",
        "profile_name": "default",
        "project_name": "xxxxxxx-xxx",
        "runtime": "python3.6",
        "s3_bucket": "xxxxx-xxx",
        "slim_handler": true,
        "vpc_config" : {
            "SubnetIds": [ "subnet-000000e86b94b75c3" ], // use the private subnet
            "SecurityGroupIds": [ "sg-87yt5644c413a2b00","sg-4rt56yd75b14cda33"]
        },
        "memory_size": 1024, // Lambda function memory in MB. Default 512.
        "log_level": "DEBUG", // Set the Zappa log level. Can be one of CRITICAL, ERROR, WARNING, INFO and DEBUG. Default: DEBUG
        "keep_warm": true, // Create CloudWatch events to keep the server warm. Default true. To remove, set to false and then `unschedule`.
        "keep_warm_expression": "rate(4 minutes)", // How often to execute the keep-warm, in cron and rate format. Default 4 minutes.
        "lambda_description": "Test Description", // However you want to describe your project for the AWS console. Default "Zappa Deployment".
		"extra_permissions": [{ // Attach any extra permissions to this policy. Default None
            "Effect": "Allow",
            "Action": "lambda:InvokeFunction", 
            "Resource": ["arn:aws:lambda:ap-south-1:9877678916:function:trubloq-xxxx4-dev"],// AWS Service ARN
        }],
    }
}

**Comment by iyobm** [comment]
Did you solve this?

**Comment by souravjamwal77** [comment]
Hi @iyobm , this issue was migrated from the previous/old repo, so it's not much relevant. Can you please post your `zappa_settings.json` file. Also, please remove any credentials/account info like ARNs or account IDs.

**Comment by iyobm** [comment]
{
    "common": {
        "aws_region": "eu-west-1",
        "django_settings": "***",
        "runtime": "python3.8",
        "project_name": "***",
        "s3_bucket": "zappa-****",
        "keep_warm": true,
        "route53_enabled": false,
        "memory_size": 1024,
        "slim_handler": true
    },

The rest of the zappa_settings extends this and adds regions (global Edge) and the domain

Using zappa 0.55.0

I can see that it is sending scheduled requests every 5 minutes however it still takes over 11 seconds to load from cold start

**Comment by souravjamwal77** [comment]
Hi @iyobm I think this could be related to one of the libraries you're using. Like if a library depends upon some GPU or more RAM/CPU. Can you post your `requirements.txt` file?(sorry, I should have asked for this earlier)

**Comment by iyobm** [comment]
@souravjamwal77 
```
argcomplete==2.0.0
asgiref==3.4.1
autopep8==1.6.0
backports.zoneinfo==0.2.1
black==22.3.0
blinker==1.5
boto3==1.20.25
botocore==1.23.25
certifi==2021.10.8
cfgv==3.3.1
cfn-flip==1.3.0
charset-normalizer==2.0.9
click==8.0.3
distlib==0.3.4
Django==4.0
django-auto-prefetch==1.3.0
django-cors-headers==3.10.1
django-debug-toolbar==3.2.4
django-ses==2.3.1
django-storages==1.12.3
djangorestframework==3.13.1
durationpy==0.5
filelock==3.7.1
flake8==4.0.1
future==0.18.2
gunicorn==20.1.0
hjson==3.0.2
identify==2.5.1
idna==3.3
jmespath==0.10.0
kappa==0.6.0
mccabe==0.6.1
mypy-extensions==0.4.3
nodeenv==1.6.0
nplusone==1.0.0
pathspec==0.9.0
pep517==0.12.0
Pillow==8.4.0
pip-tools==6.4.0
placebo==0.9.0
platformdirs==2.5.2
pre-commit==2.19.0
psycopg2-binary==2.9.3
pycodestyle==2.8.0
pyflakes==2.4.0
python-dateutil==2.8.2
python-slugify==5.0.2
pytz==2021.3
PyYAML==6.0
requests==2.26.0
s3transfer==0.5.0
six==1.16.0
sqlparse==0.4.2
stripe==2.66.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.0
tqdm==4.62.3
troposphere==3.2.2
typing_extensions==4.2.0
urllib3==1.26.7
virtualenv==20.14.1
Werkzeug==2.0.2
wsgi-request-logger==0.4.6
zappa==0.55.0
```

**Comment by souravjamwal77** [comment]
Let me try to replicate this.
