### ISSUE TITLE
[Migrated] Getting 'AttributeError' Exception Thrown

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#740]
Originally from: https://github.com/Miserlou/Zappa/issues/1864 by [canada4663](https://github.com/canada4663)

I am getting uncaught AttributeError thrown at the line below:

https://github.com/Miserlou/Zappa/blob/3ccf7490a8d8b8fa74a61ee39bf44234f3567739/zappa/handler.py#L309

It seems that the code is designed to catch exceptions where the 'command' key doesn't exist, however, if the message doesn't included an object with the get method and is only a 'str' then this fails.

**Comment by monkut** [comment]
not enough info.

closing.
