### ISSUE TITLE
[Migrated] unable to delete AWS Certificate after undeploying

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#747]
Originally from: https://github.com/Miserlou/Zappa/issues/1874 by [kurtgn](https://github.com/kurtgn)

This is probably related to AWS internals as much as to Zappa, but maybe someone using Zappa has encountered this.

My AWS account has limited amount of allowed certificates, so I need to delete the unused ones to create new ones. However, after undeployment of an app, I am unable to delete AWS certificate used to certify the app.

This is what the console tells me:
<img width="651" alt="Снимок экрана 2019-05-16 в 18 44 48" src="https://user-images.githubusercontent.com/7825762/57867948-b8fb6500-780a-11e9-9f7c-75a9f3d121fa.png">

However I am not able to find this cloudfront distribution in my Cloudfront distributions list. Quick search through Stackoverflow reveals that Cloudfront distributions created for API Gateway are not displayed in the admin console.

However, I do need to delete this distribution. 

So the question is , what does zappa do to create and delete the distribution? How can I assist the deletion from the AWS Console?

P.S. I deleted the Route 53 DNS zone - it did not help.

I tried listing this distribution using the cli - it didn't show up:

```
aws cloudfront get-distribution --id E1884EQQC5R1BK

An error occurred (NoSuchDistribution) when calling the GetDistribution operation: The specified distribution does not exist.
```

**Comment by mister-rao** [comment]
any update on this ?
