### ISSUE TITLE
[Migrated] Deployment fails on API Gateway: Invalid API Key identifier specified

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#749]
Originally from: https://github.com/Miserlou/Zappa/issues/1876 by [mxlei01](https://github.com/mxlei01)

## Context
Zappa deploy fails with an exception:

`botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the UpdateApiKey operation: Invalid API Key identifier specified`

Is there anyway to debug this?

## Your Environment
Zappa Version: zappa==0.48.2
The configuration file is as follows:

> {
>     "prod": {
>         "app_function": "main.app",
>         "profile_name": "default",
>         "project_name": "some-project-name",
>         "runtime": "python3.7",
>         "s3_bucket": "some-bucket-name",
>         "aws_region": "us-east-1",
>         "apigateway_enabled": true,
>         "api_key_required": true,
>         "api_key": "some-api-key"
>     }
> }

**Comment by h-rub** [comment]
@jneves can you fix it??
