### ISSUE TITLE
[Migrated] Issue #1879 remove deprecated field on Cognito update Pool

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#755]
Originally from: https://github.com/Miserlou/Zappa/issues/1887 by [vincentalvo](https://github.com/vincentalvo)

Trivial code, tested on Python 3.

## Description
AWS deprecated a field and that broke the cognito event setting.
This is an implementation of the solution suggested by @Yaronn44.
It follows the boto3 documentation (specifically the Note for deprecation): https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.update_user_pool 

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1879

**Comment by Yaronn44** [comment]
This issue can be close as a solution has been merged in the 0.50.0 release : https://github.com/Miserlou/Zappa/pull/2027
