### ISSUE TITLE
[Migrated] Not able to figure out how to pass path in environment variable

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#767]
Originally from: https://github.com/Miserlou/Zappa/issues/1906 by [phoenikx](https://github.com/phoenikx)

My zappa_settings.json file looks like this-
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "ap-south-1",
        "profile_name": "default",
        "project_name": "zappa-test",
        "runtime": "python3.6",
        "s3_bucket": "sample-zappa",
        "manage_roles": false,
        "environment_variables": {
            "API_CONFIG": "configs/config-dev.yml"
        }
    }
}

I wish to pass a path as an environment variable. I am passing relative path here since I don't know how it will be deployed on Lambda. But my code doesn't work with this path, it probably needs full path to the config file. Can someone help here?

**Comment by monkut** [comment]
old migrated issue, closing.
