### ISSUE TITLE
[Migrated] Zappa not able to install shap

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#769]
Originally from: https://github.com/Miserlou/Zappa/issues/1909 by [Tavishagg](https://github.com/Tavishagg)

I have installed shap package for model interpretability. But when I am trying to deploy the zappa solution I am getting error module not found.

I am using zappa using Python 3.7

## Steps to Reproduce

1. Create zappa solution
2. Install shap package (pip install shap)
3. Deploy the solution

**Comment by monkut** [comment]
old migrated issue, closing.
