### ISSUE TITLE
[Migrated] multiple update with one source code.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#772]
Originally from: https://github.com/Miserlou/Zappa/issues/1913 by [lamiru](https://github.com/lamiru)

## Context

I am running several django servers on AWS lambda. When I need to upgrade them, I run `zappa update server1 && zappa update server2 && zappa update server3`, but this command compresses a zip file and uploads it to S3 three times.

Are there any ways to save time and resources?

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by monkut** [comment]
You appear to be running 3 projects.  It may be best to separate the projects entirely and then you can write a script to run update of all 3 at the same time.

closing.
