### ISSUE TITLE
[Migrated] Package Error: python-dateutil

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#782]
Originally from: https://github.com/Miserlou/Zappa/issues/1927 by [weasteam](https://github.com/weasteam)

Would you please support the newest version of python-dateutil?

```
ERROR: zappa 0.48.2 has requirement python-dateutil<2.7.0,>=2.6.1, but you'll have python-dateutil 2.8.0 which is incompatible.
```

**Comment by monkut** [comment]
dateutil is no longer pegged by zappa, a fresh install should resolve this issue.

Closing.
