### ISSUE TITLE
[Migrated] manage command does not handle arguments with spaces properly

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#788]
Originally from: https://github.com/Miserlou/Zappa/issues/1936 by [luser](https://github.com/luser)

## Context

Attempting to invoke a Django management command where one of the arguments contains spaces, like `zappa manage prod mycommand '\"a b c\"'` results in the argument with spaces being split.

## Expected Behavior

Arguments that are quoted should be preserved, in this case `mycommand` should be called with the argument `a b c`.

## Actual Behavior

In this case `mycommand` is called with the arguments `"a`, `b`, `c"`.

## Possible Fix

[The handler code](https://github.com/Miserlou/Zappa/blob/60fbb55fffa762a85e79e756f2a1373832d78320/zappa/handler.py#L413) is currently calling `*event['manage'].split(' ')`, but it should probably be using `*shlex.split(event['manage'])` which will do the right thing here:

```
>>> import shlex
>>> s = 'a b "c d"'
>>> s.split(' ')
['a', 'b', '"c', 'd"']
>>> shlex.split(s)
['a', 'b', 'c d']
```

## Steps to Reproduce

Run a django management command, pass an argument containing spaces, such as `zappa manage prod mycommand '\"a b c\"'`

## Your Environment
* Zappa version used: `0.48.2`

**Comment by gvisalli** [comment]
What is the current status or work around for commands with parameters that container spaces?

**Comment by souravjamwal77** [comment]
Hi @gvisalli, what is the exact command you're trying to run?
