### ISSUE TITLE
[Migrated] Enable configuration of logging API requests to Cloudwatch.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#795]
Originally from: https://github.com/Miserlou/Zappa/issues/1948 by [ebridges](https://github.com/ebridges)

## Description
This adds a new configuration parameter named `cloudwatch_log_role_arn` that enables setting the ARN of a role which grants permissions to the API Gateway to write to Cloudwatch.

## GitHub Issues
#1946

**Comment by monkut** [comment]
missing pr, old migrated issue

closing.
