### ISSUE TITLE
[Migrated] Fix issue when handler fails initialization

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#797]
Originally from: https://github.com/Miserlou/Zappa/issues/1950 by [ryansmith940](https://github.com/ryansmith940)

If the LambdaHandler fails to initialize, the lambda stays in the
failed state until AWS stops it. This change causes the initializer
to continue to attempt to initialize the LambdaHandler until it
is successful.

See https://github.com/Miserlou/Zappa/issues/1949

**Comment by monkut** [comment]
old migrated issue, closing.
