### ISSUE TITLE
[Migrated] Zappa requires "future" package under Python 3.x

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#808]
Originally from: https://github.com/Miserlou/Zappa/issues/1966 by [rudyryk](https://github.com/rudyryk)

Trying to minify uploaded installation ZIP. Noticed that future package is more than 1.5Mb size, this is far larger than many. But it should not be necessary under Python 3.

## Expected Behavior
Don't install and don't require "future" package for Python 3.

## Actual Behavior
Zappa CLI can't ZIP package without "future" installed.

## Steps to Reproduce
1. Initialize Zappa project
2. Uninstall "future" with `pip uninstall future`
3. Run `zappa --help` and get error

## Your Environment
* Zappa version used: 0.48.2
* Operating System and Python version: Python 3.7.4, macOS 10.13.6
* `pip freeze` result

```bash
argcomplete==1.9.3
boto3==1.10.25
botocore==1.13.25
certifi==2019.9.11
cfn-flip==1.2.2
chardet==3.0.4
Click==7.0
docutils==0.15.2
durationpy==0.5
Flask==1.1.1
future==0.16.0
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
peewee==3.11.2
placebo==0.9.0
psycopg2-binary==2.8.4
PyJWT==1.7.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==5.1.2
requests==2.22.0
s3transfer==0.2.1
sentry-sdk==0.13.2
signa==0.2.1
six==1.13.0
structlog==19.2.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.5.2
Unidecode==1.1.1
urllib3==1.25.7
Werkzeug==0.16.0
wsgi-request-logger==0.4.6
zappa==0.48.2
```

**Comment by monkut** [comment]
released, closing
