### ISSUE TITLE
[Migrated] Zappa Installation: UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2347

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#816]
Originally from: https://github.com/Miserlou/Zappa/issues/1986 by [qy2205](https://github.com/qy2205)

## Context

I tried `pip install zappa`, but get the following error

    ERROR: Command errored out with exit status 1:
     command: 'X:\Anaconda3\envs\py36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\quany\\AppData\\Local\\Temp\\pip-install-gxsvadov\\kappa\\setup.py'"'"'; __file__='"'"'C:\\Users\\quany\\AppData\\Local\\Temp\\pip-install-gxsvadov\\kappa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\pip-egg-info'
         cwd: C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\setup.py", line 54, in <module>
        run_setup()
      File "C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\setup.py", line 22, in run_setup
        long_description=open_file('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2347: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Your Environment

* Zappa version used: lastest
* Operating System and Python version: Python3.6 & Python3.7
* The output of `pip freeze`: 
certifi==2019.11.28
wincertstore==0.2

**Comment by monkut** [comment]
old migrated issue, assuming resolved in latest zappa

closing

**Comment by harry0805** [comment]
I just got the same error today, it seems the issue came from one of the dependencies `kappa`, the solution was to change your system locale to English, see https://github.com/garnaat/kappa/issues/127
