### ISSUE TITLE
[Migrated] Incompatible with newly released Werkzeug 1.0.0

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#818]
Originally from: https://github.com/Miserlou/Zappa/issues/2036 by [rudyryk](https://github.com/rudyryk)

## Context
After a new today's deployment app didn't work.

## Expected Behavior
Work.

## Actual Behavior
Getting exception after deployment:

```
[ERROR] ImportError: cannot import name 'secure_filename' from 'werkzeug' (/var/task/werkzeug/__init__.py)
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 139, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

## Possible Fix
As a workaround here suggested to use older Werkzeug:
https://github.com/puckel/docker-airflow/issues/499

```werkzeug==0.16.1```

## Steps to Reproduce
Try to deploy a new app from a clean environment.

Contents of a `requirements.txt`:

```
zappa
flask
```

## Your Environment

* Zappa version used: ``zappa==0.50.0``
* Operating System and Python version: ``Python 3.7.4`` 
* The output of `pip freeze`:

```
boto3==1.12.4
botocore==1.15.4
certifi==2019.11.28
cfn-flip==1.2.2
chardet==3.0.4
Click==7.0
Flask==1.1.1
Werkzeug==1.0.0
WTForms==2.2.1
zappa==0.50.0
...
```

* Your `zappa_settings.json`: 

```yaml
prod:
  project_name: app-admin
  app_function: app_admin.main.app
  aws_region: eu-central-1
  exclude:
  - .env*
  - boto3*
  - botocore*
  keep_warm: true
  s3_bucket: my-bucket
```

**Comment by monkut** [comment]
resolved in lastest zappa.

closing
