### ISSUE TITLE
[Migrated] Add S3 upload arguments

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#827]
Originally from: https://github.com/Miserlou/Zappa/issues/2068 by [StevePorter92](https://github.com/StevePorter92)

## Description
 
This allows the use of upload arguments to be passed through to the S3
client.

This will enable server-side encryption on S3 buckets.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.S3Transfer.ALLOWED_UPLOAD_ARGS

For https://github.com/Miserlou/Zappa/issues/1792

## GitHub Issues

#1792

**Comment by monkut** [comment]
Not enough info.

closing.
