### ISSUE TITLE
[Migrated] Allow file exclusion using pathspec

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#829]
Originally from: https://github.com/Miserlou/Zappa/issues/2070 by [suriya](https://github.com/suriya)

## Description

This commit introduces `.gitignore` style patterns to customize what files can be excluded from a project's package.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1359

**Comment by stryker-sk** [comment]
This is an issue when trying to use Sentry: `ModuleNotFoundError: No module named 'sentry_sdk.integrations.boto3'`
