### ISSUE TITLE
[Migrated] What is the correct solution for uploading images asynchronously?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#835]
Originally from: https://github.com/Miserlou/Zappa/issues/2076 by [xncbf](https://github.com/xncbf)

# The flow what i envisioned is as next

1. User append images by website(input file html) and submit.
2. zappa lambda receive  the images and toss to s3 upload function asyncly.
3. website waiting uploaded image and show image url.

# Two ways to upload images

1. save image to local (sync) -> read image (async) upload(saved_img)
2. encode to byte -> stream as byte

# problem

1. In the case of the Async function, the / tmp folder seems to point to a different physical location. Save is possible, but cannot be recalled.
2. There is a limit to the number of characters in sns when streaming in bytes. Long files such as images cannot be put in arg.

Is there any other good way to upload images to Async?

**Comment by monkut** [comment]
This is not directly related to zappa.

Lambda is ephemeral, and does not maintain permanent storage.  You need to implement your code in a way to save to something like s3.

Closing.
