### ISSUE TITLE
[Migrated] Fix binary_support handling

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#839]
Originally from: https://github.com/Miserlou/Zappa/issues/2081 by [martinv13](https://github.com/martinv13)

## Description
 
Fix the logic behind binary_support handling in `handler.py` to allow compressed text response at application level, partially reverting #2029 

## GitHub Issues

#2080 #2087

**Comment by monkut** [comment]
duplicate

https://github.com/zappa/Zappa/issues/908
