### ISSUE TITLE
[Migrated] An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#844]
Originally from: https://github.com/Miserlou/Zappa/issues/2088 by [gloriamacia](https://github.com/gloriamacia)

I am using zappa with a conda virtual environment. I could manage to deploy other apps before this one using conda environments by doing first export VIRTUAL_ENV=/path/to/conda/env/

This app contains a deep learning model that is itself (101M) so not surprised at all if the zip itself exceeds the allowed 250M. Is there a way to get around it? If so, which command should I run? 

My goal is to use Zappa to deploy severless deep learning applications.

**Comment by monkut** [comment]
At the moment, beside trying `slim_handler`, you can now try to prepare a docker image.

closing.
