### ISSUE TITLE
[Migrated] TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#845]
Originally from: https://github.com/Miserlou/Zappa/issues/2089 by [alphahacker](https://github.com/alphahacker)

## Context

First time installation of zappa and django

## Expected Behavior

Expected behavior is to show me basic django page.

## Actual Behavior

when I accessed the page(https://y60g2h2ae6.execute-api.ap-northeast-2.amazonaws.com/dev/), the messages as below came up. 

"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 540, in handler\\n    with Response.from_app(self.wsgi_app, environ) as response:\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 287, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 1119, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"

## Steps to Reproduce

1. virtualenv venv
2. source venv/bin/activate
3. pip install django
4. django-admin startproject testproject . 
5. pip install zappa
6. zappa init
7. zappa deploy dev

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: mac os mojave 10.14.6, python 3.8.1
* The output of `pip freeze`:
argcomplete==1.11.1
asgiref==3.2.7
boto3==1.12.46
botocore==1.15.46
certifi==2020.4.5.1
cfn-flip==1.2.3
chardet==3.0.4
click==7.1.1
Django==3.0.5
docutils==0.15.2
durationpy==0.5
future==0.18.2
hjson==3.0.1
idna==2.9
jmespath==0.9.5
kappa==0.6.0
pip-tools==5.0.0
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==4.0.0
pytz==2019.3
PyYAML==5.3.1
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
sqlparse==0.3.1
text-unidecode==1.3
toml==0.10.0
tqdm==4.45.0
troposphere==2.6.0
urllib3==1.25.9
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.51.0
* Link to your project (optional):
* Your `zappa_settings.json`: 
{
    "dev": {
        "aws_region": "ap-northeast-2",
        "django_settings": "testproject.settings",
        "profile_name": "default",
        "project_name": "test-zappa-14",
        "runtime": "python3.8",
        "s3_bucket": "zappa-iba0235d3"
    }
}

**Comment by monkut** [comment]
This is a common error when your  app isn't running properly.

closing.
