### ISSUE TITLE
[Migrated] Add support for REQUEST type Lambda Authorizers

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#847]
Originally from: https://github.com/Miserlou/Zappa/issues/2093 by [tommie-lie](https://github.com/tommie-lie)

## Description
Support for REQUEST authorizers was almost there, as the `type` authorizer property was mostly passed through to the CloudFormation templates. This PR extends the handler middleware to also treat events of type REQUEST as authorization events. It also extends the template creation to treat TOKEN and REQUEST type authorizers equal (defaulting to TOKEN just as before).
The most significant change is in the logic how the authoriz*ation* type for API routes is derived from the authoriz*er* type: Instead of assuming CUSTOM if the type is not specified, the authorizer type correctly defaults to TOKEN. The authorization type is then mapped to CUSTOM for both, TOKEN and REQUEST authorizers.

Added unit tests and tested on live environments on AWS.

## GitHub Issues
Fixes #1159

**Comment by tsebastiani** [comment]
is there any update regarding this PR? Would be super helpful to have this feature merged.
