### ISSUE TITLE
[Migrated] How to update app without downtime?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#855]
Originally from: https://github.com/Miserlou/Zappa/issues/2103 by [xncbf](https://github.com/xncbf)

In the case of AWS Beanstalk, can be deployment without downtime through environment replication and url swap. Is it possible to perform a similar practice on Zappa?

**Comment by sabyasachi** [comment]
Did anybody figure out a way to deploy without downtime? During "lambda updation", the application waits and times out.
