### ISSUE TITLE
[Migrated] Add a support for a default AWS event handler

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#865]
Originally from: https://github.com/Miserlou/Zappa/issues/2115 by [jiaaro](https://github.com/jiaaro)

Ticket: #2112 

This PR adds a way for users to define a default handler for AWS events. This allows for handling events for sources that don't exist at the time of deployment (like temporary SQS queues) as well as resources managed by systems like terraform whose ARNs are not yet known at the time the Zappa package is built.

Finally, it allows users to handle events from new AWS systems that Zappa has not specifically integrated yet.

**Comment by monkut** [comment]
As this is an old migrated issue, I'm going to close it.
If someone is still interested in this, please create a new issue.
