### ISSUE TITLE
[Migrated] botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#876]
Originally from: https://github.com/Miserlou/Zappa/issues/2131 by [arshyasharifian](https://github.com/arshyasharifian)

This is the error code:
##[error]Process completed with exit code 255.

I am trying to run a CI/CD pipline through git actions.

workflow starts here:
`
 name: CI
      
 on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 jobs:
   build:
     runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        profile_name: default
        project_name: test-dep
        runtime: python3.7
        s3_bucket: arysb
    - name: Run a multi-line script
      run: |
         echo "::add-path::/investbot/.aws"
         #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         #aws configure --profile arshyasharifian
         python -m pip install --upgrade pip 
         pip install -r requirements.txt
         zappa deploy dev`

Ideally, this would deploy the updated application in the AWS Lambda serverless instance.

requirements.txt:
`argcomplete==1.11.1
boto3==1.14.13
botocore==1.17.13
certifi==2020.6.20
cfn-flip==1.2.3
chardet==3.0.4
click==7.1.2
docutils==0.15.2
durationpy==0.5
Flask==1.0
future==0.18.2
hjson==3.0.1
idna==2.10
importlib-metadata==1.7.0
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
kappa==0.6.0
MarkupSafe==1.1.1
pip-tools==5.2.1
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==4.0.0
PyYAML==5.3.1
requests==2.24.0
s3transfer==0.3.3
six==1.15.0
text-unidecode==1.3
toml==0.10.1
tqdm==4.47.0
troposphere==2.6.1
urllib3==1.25.9
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.51.0
zipp==3.1.0
`

my zappa_settings.json, but I am not sure if the workflow sees this or not:
`{
    "dev": {
        "app_function": "main.app",
        "aws_region": "us-east-1",
	"profile_name": "default",
        "project_name": "test-dep",
        "runtime": "python3.7",
        "s3_bucket": "arysb"
    }
}`

**Comment by joelwebb** [comment]
Updating the creds with aws configure didn't solve it for me. Then I realized that since I was using AWS profiles set up in ~/.aws/config and ~/.aws/credentials, your zappa setting for "profile" must match the AWS profile name in the config file, now what you have set in your local env. If your error is pointing at the default profile, it is checking for aws profiles ( https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html ) which might help solve the issue. This is also a solution for when [Zappa does not recognize a deployed project after changing the AWS secret keys. ](https://github.com/Miserlou/Zappa/issues/1663)

**Comment by hayd** [comment]
I get the same error when trying to `update` an already deployed zappa application with codebuild.

```
Warning! Couldn't get function projectname-dev in us-east-1 - have you deployed yet?
```

The suggestion of `aws configure` errors, presumably because it's using a role not an access key.

```
[Container] 2023/02/27 23:07:14 Running command aws configure
--
220 | AWS Access Key ID [None]:
221 | EOF when reading a line
```
so, I'm not really sure how to proceed.

**Comment by joelwebb** [comment]
@hayd - have you tried deleting your ~/.aws/credentials file and then re-running `aws configure` ?

**Comment by hayd** [comment]
I will try an `rm ~/.aws/credentials`, but I am confused why this would help!

I am trying to use an AWS Codebuild ci machine to do the `zappa update` (whereas the initial deploy was on my local machine), so it's using an IAM role rather than an Access Key ID in credentials?

**Comment by sridhar562345** [comment]
When you are running zappa in codebuild don't use `profile_name` key in zappa_settings.json at all.

Remove `profile_name` setting and zappa automatically uses the codebuild role.
