### ISSUE TITLE
[Migrated] Zappa Slack appears to be closed by default.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#877]
Originally from: https://github.com/Miserlou/Zappa/issues/2132 by [jonatkinson](https://github.com/jonatkinson)

## Context
I'm interested in Zappa development, so I followed the Slack link. The Slack appears to be closed by default and requires an invite from an administrator.

## Expected Behavior
I would like to join the Zappa Slack.

## Actual Behavior
I cannot join the Zappa Slack.

## Possible Fix
Adjust the Slack permissions.

**Comment by techdragon** [comment]
Possible alternative solutions. 
- Switch to GitHub Discussions ? 
  - Is that feature enabled for this repo? 
- Use an open by default chat tool like Discord.

**Comment by monkut** [comment]
You can join here.
https://slackautoinviter.herokuapp.com

will be added to the readme.

closing.
