### ISSUE TITLE
[Migrated] Can we deploy all/some api endpoints to separate functions?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#878]
Originally from: https://github.com/Miserlou/Zappa/issues/2133 by [singhravi1](https://github.com/singhravi1)

## Context
There are cases when few API endpoints need multiple resources for example memory to execute than others. 
So, if we'll be able to separate those API endpoints, we can use more memory just for those selected tasks and not have to use more than required memory for all the other functions.

**Comment by monkut** [comment]
At the moment a single zappa project relates to a single lambda function, and has a single configuration.
You may consider using multiple `zappa_settings.json` to create separate functions.

closing.
