### ISSUE TITLE
[Migrated] werkzeug==0.16.1 needs to be updated | Cannot set SameSite=None on session cookie

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#881]
Originally from: https://github.com/Miserlou/Zappa/issues/2136 by [wobeng](https://github.com/wobeng)

@Miserlou Long time :) 

Please update werkzeug in requirement.txt to the latest. It has a fix for https://github.com/pallets/flask/issues/3469

**Comment by paul-ri** [comment]
Updating Werkzeug would also resolve the version dependency incompatibility with Flask 2.0: https://github.com/pallets/flask/releases/tag/2.0.0

Flask 2.0 needs [Werkzeug >= 2.0](https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0) and Zappa states [werkzeug==0.16.1](https://github.com/zappa/Zappa/blob/master/requirements.txt#L83). Pip isn't making our life easy with this unfortunately.

Thanks!
