### ISSUE TITLE
[Migrated] exception handler doesn't seem to work

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#888]
Originally from: https://github.com/Miserlou/Zappa/issues/2144 by [akobig](https://github.com/akobig)

I created the unhandled_exceptions function exactly as in the manual, and configured the zappa_settings.json.

this is the function:
def unhandled_exceptions(e, event, context):
    send_email(to=[developer_email], subject="unhandled exception in app", text="test")
    print("exception test")
    return True

I don't get any email (this function 100% working) when there is an exception nor seeing the print output in log.
the exception is clearly printed in the log, as usual.

I really want this to work since it is the only easy way to send the exception  in email.
tnx

**Comment by monkut** [comment]
old migrated issue, may not be relevant or details unclear.

closing.
