### ISSUE TITLE
[Migrated] Can I use DON'T PANIC traceback in logs?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#904]
Originally from: https://github.com/Miserlou/Zappa/issues/2166 by [rafagan](https://github.com/rafagan)

Setting "FLASK_DEBUG": "true" in my environment_variables enable detailed traceback from errors, but how can I return the DON'T PANIC traceback HTML?

**Comment by monkut** [comment]
old migrated issue, potentially no long relevant or not enough details.

closing.
