### ISSUE TITLE
[Migrated] Zappa: command not found

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#905]
Originally from: https://github.com/Miserlou/Zappa/issues/2167 by [andhim](https://github.com/andhim)

Hi, I am trying to deploy my web through zappa on my virtual env and my terminal keeps saying "command not found: zappa."
I have installed it using pip3 install zappa both on my local desktop as well as on my virtual env. 
Can someone tell me how to fix this issue please?

**Comment by monkut** [comment]
configuration/setup error assumed.
Not enough detail to support.

closing.
