### ISSUE TITLE
[Migrated] Invoke lambda_handler with event argument

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#911]
Originally from: https://github.com/Miserlou/Zappa/issues/2176 by [manycoding](https://github.com/manycoding)

## Context
There's no way to call lambda_handler in the same manner as AWS Lambda test for non-wsgi apps.
Related to https://github.com/Miserlou/Zappa/issues/2146 https://github.com/Miserlou/Zappa/pull/983

## Expected Behavior
I wanna get an output from the specified lambda_handler function with specified `event` argument.
```
zappa invoke dev {"address":"5760 Teredo St., Sechelt, BC, Canada, VON 3A"}

{
  "parsed_address": {
    "street_address": "5760, Teredo St.",
    "city": "Sechelt",
    "state": "BC",
    "postcode": "VON 3A0",
    "country": "Canada"
  }
}
```
## Actual Behavior
Nothing. In fact I cannot get any output even for raw commands:
`zappa invoke dev 'print("hey")' --raw`

Executing a test event from Lambda UI works as expected.

## Possible Fix
Allow to 

## Steps to Reproduce
1. Create a lambda_handler function with event and context
2. Specify it in zappa_settings
3. Zappa invoke from cli

## Your Environment
* Zappa version used:
0.52.0
* Operating System and Python version:
3.7, Mac OS, Pipenv
* Your `zappa_settings.json`: 
```
dev:
    lambda_handler: api.lambda_handler
```

**Comment by jdahlin** [comment]
Try 
`zappa invoke --raw dev 'self.run_function(self.import_module_and_get_function("api.lambda_handler"), {"address":"5760 Teredo St., Sechelt, BC, Canada, VON 3A"}, context)'`

**Comment by monkut** [comment]
You should use `zappa invoke STAGE COMMAND --raw`.

Confirmed that the output is given from command, `zappa invoke prod 'print("hey")' --raw`.

```
[DEBUG] 2022-08-18T12:15:24.738Z 6b7b09f6-1f37-4839-830d-f16162b4354a Zappa Event: {'raw_command': 'print("hey")'}
hey
[END] RequestId: 6b7b09f6-1f37-4839-830d-f16162b4354a

```
Upgrade to the latest version of zappa and try again.

closing
