### ISSUE TITLE
Becoming a member of the new Zappa organisation

### ISSUE THREAD

**Issue by willgdjones** [zappa/Zappa#948]
Hello! I'm a heavy user of Zappa, and I'd like to contribute to Zappa's development.

Do let me know if there's a process to follow in order to become a member of the organisation.

Thanks, and I'm looking forward to developing the project further in the near future!

**Comment by techdragon** [comment]
I've been looking to contribute to this project for ages but the lack of clarity about the maintenance situation was really killing any enthusiasm. Now this is in its own repo, I've forked it and I'm already checking out the migrated issues to see how I can roll up my sleeves and get my hands dirty helping!

I think it may need to be a matter of priority to clear up the remaining readme information and "stand on our own feet". Fix the slack channel or switch to something else (as mentioend in #877 )

**Comment by Yaronn44** [comment]
I already helped once or twice and I'm using Zappa daily . I would be glad to give some help from time to time depending on my main tasks at work (I already offer my support in the discussion #954) and having something to communicate easily would be good !

**Comment by tommie-lie** [comment]
I, too, want to help with this project as we currently build our new software on top of Zappa and the lack of maintenance is a huge uncertainty for us. I understand that maintenance is hard and other things and real life may come in the way of doing open source work. But there are many people willing to help and relying on a single person that is not very active is really not ideal for advancing this aweseome project.
For us, the amount of quirks and gotchas and the sometimes-not-quite-understandable-documentation has often made us wish we'd fork Zappa just to have our stuff maintained.

@jneves Please provide *some* hints on how you want to continue maintaining this project. It doesn't have to be an elaborate plan, even just a heads up that things are getting better. Or please consider adding more maintainers to the project.

**Comment by JohnLockwood** [comment]
Hi folks,

This is an interesting thread.  I ran into several issues right away so I share your wish to have a well maintained tool to work with, otherwise I'd be inclined to build a one-off based on some of the techniques used for a project I'm working on.  I'm less enthusiastic about the serverless framework however, but that's just me.  If it didn't detract from the core effort of a good standalone tool, it might work.  

Has a consensus been reached around a new official fork?  In other words, if we're taking our marbles and going home, do we know to whose house we can go to bring our marbles going forward?

**Comment by CaseGuide** [comment]
Yes I too would like to attend the marbles event where we submit code to improve Zappa and avoid using the AWS SAM CLI. 

> Hi folks, if we're taking our marbles and going home, do we know to whose house we can go to bring our marbles going forward?

**Comment by Quidge** [comment]
I would also like working in the codebase. We rely on Zappa heavily at work and I've enjoyed working in the Zappa codebase for the fork we've been maintaining (uses some changes from this PR: https://github.com/zappa/Zappa/pull/971).

I like writing test coverage and so it would be really neat to contribute coverage to a library that I rely on for work.

**Comment by hellno** [comment]
Hey everyone 👋🏼 
Super excited to see many people wanting to get involved.
A small group of contributors jumped in and we just brought zappa back to life (after brief period of deprecation status).

We're planning to publish a new release soon and then maintain and expand the project for the long-term.

If you want to jump into the discussion and help contribute, we're chatting on Slack to organize ourselves, 
while main work is of course happening here in issues and PRs.
To join the slack you can use the invite here: https://github.com/zappa/Zappa/issues/1043#issuecomment-924201667

I'm closing this to keep the issues organized
