### ISSUE TITLE
[PROPOSAL] Support multiple Cognito user pools

### ISSUE THREAD

**Issue by wagmiwiz** [zappa/Zappa#958]
Current Zappa implementation assumes that only one user pool exists (see [here](https://github.com/zappa/Zappa/blob/93804a1b3157f0189bf062e01baab2bd4f09400d/test_settings.json#L52)). 

However, a lot of projects have multiple user pools as this allows them to separate things like SAML connectors / password requirements per customer / tenant (common practice in B2B SaaS). This is also what AWS themselves recommend [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-based-multi-tenancy.html).

Proposal here is to change Zappa Cognito code to support more than one user pool. 

Perhaps this is just as simple as having the setting support arrays for `user_pool` to remain backward compatible. This would assume you still only have a single set of Lambda triggers no matter the pool, but given that the payload also includes pool id then people can differentiate between them in the app code (such as doing a db lookup to find which tenant / customer etc).

Thoughts welcome.

**Comment by Yaronn44** [comment]
Could be included in my discussion about a refacto of the zappa_settings events trigger as the Cognitos triggers are managed into it : #954

I think it's a good point I actually I have this problem and I'm using a separate lambda to redirect the triggers to my main API...
