### ISSUE TITLE
Please use Github Repo Releases so that users can 'watch' Releases only

### ISSUE THREAD

**Issue by dfuentes77** [zappa/Zappa#964]
Would love it if releases were updated as Github Releases so that I can just watch (get notifcations for) the repo's `Releases` of the repo and not `All Activity`.  I don't need to see all changes happening, but I do want to keep up to date when a new release is available.

Thanks!

**Comment by monkut** [comment]
The release procedure is not fully documented, but we will try to include updating the release moving forward.

closing.
