### ISSUE TITLE
Please how we can use Zappa WSGI interface independently and deploy our app manually using aws console, CLI or other IaC.

### ISSUE THREAD

**Issue by DataHighlands** [zappa/Zappa#966]
Please how we can use Zappa WSGI interface independently and deploy our app manually using aws console, CLI or other IaC

**Comment by gaurav386i** [comment]
As far as I understand you means to say that , deploy zappa enabled application with out using zappa cli commands like "zappa deploy development or zappa update development ". If this is the case then, you can use  following steps to deploy independently : 
1. run "zappa package <stage_name>" command to create the application package which is a zip file .
2. Create api-gateway,  lambda function and other required configuration using a IaC tool e.g terraform.
3. Upload zip file create in first step to S3 , from s3 deploy it to aws lambda function.

**Comment by monkut** [comment]
Yes, use the `zappa package <stage_name>` command to create the package for lambda deployment, and prepare your required infrastructure.

Closing.
