### ISSUE TITLE
Promoting Zappa To the Next Generation of Developers

### ISSUE THREAD

**Issue by mslinn** [zappa/Zappa#968]
I recently published a [blog post on Zappa](https://www.mslinn.com/blog/2021/04/14/serverless-ecommerce.html#zappa). Feedback / corrections and suggestions are invited. The main points I am attempting to make are:

 1. Zappa is a seminal project that has inspired other well-known projects.
 2. Zappa is still very useful; in fact, its best days lie ahead.
 3. Zappa needs new contributors (a "new generation") to help work through the backlog and hone the messaging.

I would like to update the blog post (and the follow-on posts that are in progress) with more information about the old-time developers and recent additions, and tell the world the skills necessary for new contributors to be most effective in addressing the backlog. Please respond publicly here or in private to me at mslinn@mslinn.com.

Has anyone communicated with @jezdez at [JazzBand](https://jazzband.co) about discussing the possibility of having Zappa join JazzBand?

**Comment by tommie-lie** [comment]
Thanks for your research! I'm interested to know what other projects you are talking about here and in your blog post. The technology of Zappa seems to be quite unique, at least to my knowledge. While you list other frameworks in your blog post that solve different serverless computing problems, Zappa seems to be quite unique as being an easy way to run regular WSGI apps in a serverless environment.

Regarding your comment on @JazzBand: I doubt anyone has done that, yet, and even if someone does it, without the maintainer of this project, nothing can be done to transfer Zappa to JazzBand. So this is a kind of chicken and egg problem: without mainteiner, there is no maintenance, and if we had an active maintainer, we wouldn't be in need of one in the first place.
Besides, judging from [some](https://github.com/jazzband/help/issues/196) [issues](https://github.com/jazzband/help/issues/184) [there](https://github.com/jazzband/help/issues/195), they are suffering a similar problem.
And on a personal note: I don't think Zappa is currently in a state where a losely-coupled community of maintainers will do any good. It needs people with a strong vision and passion about what the project should look like in the future.

**Comment by mslinn** [comment]
I am going to reach out to @jezdez, and then I will respond here :) after speaking with him.

**Comment by wrboyce** [comment]
Closing as, ironically enough, this issue seems to have been abandoned now.
