### ISSUE TITLE
Unknown parameter in input: "Layers" 

### ISSUE THREAD

**Issue by virajweerasinghe-zincat** [zappa/Zappa#969]
I am getting below error while I'm to trying to deploy zappa project into aws.

I have tried with `pip3 list`

`Package         Version`
`--------------- -------`
`aws             0.2.5`
`bcrypt          3.2.0`
`boto            2.49.0`
`boto3           1.17.59`
`botocore        1.20.59`
`cffi            1.14.5`
`cryptography    3.4.7`
`fabric          2.6.0`
`invoke          1.5.0`
`jmespath        0.10.0`
`paramiko        2.7.2`
`pathlib2        2.3.5`
`pip             21.0.1`
`prettytable     2.1.0`
`pycparser       2.20`
`PyNaCl          1.4.0`
`python-dateutil 2.8.1`
`s3transfer      0.4.2`
`setuptools      56.0.0`
`six             1.15.0`
`urllib3         1.26.4`
`wcwidth         0.2.5`
`wheel           0.36.2`

This is my zappa-settings.json

`{
    "dev": {
        "app_function": "main.app",
        "aws_region": "ap-southeast-1",
        "profile_name": "default",
        "project_name": "hh-data-backup",
        "runtime": "python3.8",
        "s3_bucket": "hh-bucket",
        "events": [{
           "function": "main.handler"
        }]
    },
    "apigateway_enabled": false,
    "keep_warm": false
}`

this is my full error 

`Unknown parameter in input: "Layers", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig, Environment, Runtime, DeadLetterConfig, KMSKeyArn, TracingC
onfig, RevisionId`

Can you help me with this ?

**Comment by loscil06** [comment]
Do you have the full traceback or this is what it returns?

**Comment by virajweerasinghe-zincat** [comment]
Hi @loscil06 , I have fixed issue with this https://github.com/Miserlou/Zappa/blob/master/requirements.txt

**Comment by loscil06** [comment]
@virajweerasinghe-zincat I'm guessing it was something to do with broken dependencies. Do you mind if you close the issue if this problem has been resolved?
