### ISSUE TITLE
Error loading psycopg2 module: No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by viktor-idenfy** [zappa/Zappa#974]
Python 3.8
I installed:
psycopg2==2.8.6
psycopg2-binary==2.8.6

The database uses:
'ENGINE': 'django.db.backends.postgresql_psycopg2',

After deploying zappa I keep getting this error with zappa tail dev

**Comment by deschantkn** [comment]
Hello, how did end up solving this please?

**Comment by sridhar562345** [comment]
@deschantkn 
Installing psycopg2-binary only might solve this issue, but this is not recommended for production servers.

Have a look at [psycopg2 lambda layer](https://github.com/jkehler/awslambda-psycopg2) that will fix your problem.
