### ISSUE TITLE
How to use custom lambda handler?

### ISSUE THREAD

**Issue by viktor-idenfy** [zappa/Zappa#975]
I did not understand the documentation fully. Can you provide an example of how can I use a custom lambda handler?
I defined it like this, but keep getting the error: Unable to import module 'documents.lambda.py': No module named 'py'

My current setup:
zappa_settings.json:
**"lambda_handler": "documents.lambda.py.lambda_handler"**

Documents is my module and lambda.py is python file with following structure:

`def lambda_handler(event=None, context=None):
    """ This lambda triggers other supporting functions """
    print("this is event"+event)
    return "This lambda handler triggers other functions "`

**Comment by Yaronn44** [comment]
You just should not provide the `.py`  : "lambda_handler": "documents.lambda.lambda_handler"

**Comment by monkut** [comment]
This is the way:
"lambda_handler": "documents.lambda.lambda_handler"

stale, closing.
