### ISSUE TITLE
Admin site timeout on submit and /static/* returns 403

### ISSUE THREAD

**Issue by mrichman** [zappa/Zappa#987]
I created my app using postgresql. Admin site works locally. I deployed using zappa. I can hit my API GW endpoint, and I'm prompted for my admin credentials. Form is unstyled because everything under `/static` is 403 (why?).

Submitting the form times out. In the logs I see 

`amazonaws found in host`

 and 

`Using selector: EpollSelector`

 but then it times out in 30s. What am I doing wrong?

**Comment by monkut** [comment]
Assuming a configuration error.

Make sure you're hitting the correct endpoint. (when using apigateway your endpoint is prefixed by the {STAGE}, in your example, it's likely that your endpoint is `/{STAGE}/static`.)

Closing.
