### ISSUE TITLE
Maybe it would be more productive to make joint efforts with serverless framework and move Zappa features into plugins for it?

### ISSUE THREAD

**Issue by ArtikUA** [zappa/Zappa#994]
There are plugin and using it it's possible to achieve 90% of the Zappa functionality:
https://github.com/logandk/serverless-wsgi (it's based on Zappa btw)

Docker containers with auto build - deploy to ecr - are supported for several months
A lot of third-party-plugins

Zappa missing some critical features like websockets, parallel warmups, etc

On the other side - serverless missing something simple to use like @task decorator

**Comment by Yaronn44** [comment]
The problem with Zappa is that nobody really knows what the owners want to do or how they want to maintain it...
Some peoples (me included) already propose their help but we didn't received any response : #948 
There is still some merges and commits done on the master branch though...

Apart from that it could be a good idea !

**Comment by JohnLockwood** [comment]
I would have preferred to see it remain a standalone tool, so in a way that's a downvote on this issue, but a well maintained one (so an upvote on #948).

**Comment by monkut** [comment]
At the moment we're working to cleanup and restart development for users who are still using zappa.
Closing for now as there are no plans at the moment to integrate with serverless.
