### ISSUE TITLE
Unable to pass custom handler in zappa_settings.json

### ISSUE THREAD

**Issue by khixer** [zappa/Zappa#997]
Hi, 
I'm pretty new to Zappa. I'm facing a configuration issue, a basic one I'm assuming. 

**Problem:** 
I want to run my API endpoint as a cronjob using Zappa. I'm trying to pass custom_handler in `zappa_settings.json` but getting a weird error of `startswith` upon `zappa update staging` 

**Attempt:**
```
{
  "staging": {
    "aws_region": "us-west-2",
    "django_settings": "my_project.settings.staging",
    "log_level": "DEBUG",
    "events": [{
      "expression": "rate(7 days)"
    }],
    "environment_variables": {
        "DOMAINS_URL": "https://my_project-xyz.us-west-2.elasticbeanstalk.com",
    },
    "profile_name": "default",
    "project_name": "my_project",
    "runtime": "python3.7",
    "s3_bucket": "abc",
    "debug": true,
    "keep_warm": false,
    "slim_handler": true,
    "custom_handler": "cron.task_to_run" // I fear this is causing a problem.
  }
}
```
`cron.task_to_run`: cron is a file and task_to_run is a function It will further call the necessary API. 

**Contents of cron.py**
```
def task_to_run(event, _context):
    return {}
```

**Error:**
```
  File "/home/khizar/.pyenv/versions/3.7.2/lib/python3.7/site-packages/zappa/cli.py", line 2652, in collision_warning
    if item.startswith(namespace_collision):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
I've seen the contents of cli.py. My handler doesn't start with the below-mentioned list 
```
namespace_collisions = [
            "zappa.", "wsgi.", "middleware.", "handler.", "util.", "letsencrypt.", "cli."
        ]
```
Kindly point me in the right direction. 

Thanks!

**Comment by ian-whitestone** [comment]
I don't believe `custom_handler` is a supported setting. I only see `lambda_handler` - is that what you are looking for?

**Comment by ian-whitestone** [comment]
Additionally, if you just want to invoke a function on a schedule, you should look at the Scheduling section of the docs: https://github.com/zappa/Zappa#scheduling

However, I don't believe this will pass in the `event` and `context` metadata that the lambda handlers normally receive (although I'm not sure why you'd even need those for a scheduled function)

**Comment by khixer** [comment]
I want to run my API endpoint deployed on EB with the help of event handler. I've tried `lambda_hander` as well. My instance is in default VPC and I'm new to AWS :( I don't want to touch/configure lambda access within VPC right now. I was wondering if there's way to invoke API without specifying VPC config and other permissions.
