### ISSUE TITLE
Error when deploying AWS Lambda with Zappa package

### ISSUE THREAD

**Issue by litalyair** [zappa/Zappa#998]
<html>
<body>

The Error:

Traceback (most recent call last):
--
286 | File "/codebuild/output/src541499700/src/.python/bin/zappa", line 5, in <module>
287 | from zappa.cli import handle
288 | File "/codebuild/output/src541499700/src/.python/lib/python3.8/site-packages/zappa/cli.py", line 44, in <module>
289 | from .core import Zappa, logger, API_GATEWAY_REGIONS
290 | File "/codebuild/output/src541499700/src/.python/lib/python3.8/site-packages/zappa/core.py", line 33, in <module>
291 | import troposphere
292 | File "/codebuild/output/src541499700/src/.python/lib/python3.8/site-packages/troposphere/__init__.py", line 11, in <module>
293 | import cfn_flip
294 | ModuleNotFoundError: No module named 'cfn_flip'

</body>
</html>

## Context

When running the command: zappa package dev -o /tmp/lambda-package.zip
we've got the error above without changing anything in our code

## Your Environment

* Zappa version used: 0.52.0
* Operating System and Python version: python 3.8, ubuntu

**Comment by alonraiz** [comment]
adding `cfn_flip` to my project requirements resolved the issue, but I am not sure what dependency caused this change.

**Comment by povesma** [comment]
I seems that https://pypi.org/project/troposphere/ causes the problem: release `3.0.0` does not install `cfn-flip`. If you return manually to `troposphere==2.7.1` - if works.

**Comment by fptiangco** [comment]
Did the same version downgrade for troposphere as @povesma and can confirm that it fixes the issue.

**Comment by litalyair** [comment]
Thanks for investigating it.
We did the same as well and it resolved it but it is not supposed to be a permanent solution.

**Comment by fptiangco** [comment]
Agreed @litalyair, hopefully @povesma's mention of an ongoing [bug report](https://github.com/cloudtools/troposphere/issues/1926) can help permanently address it.

**Comment by povesma** [comment]
BTW, this is not the only issue with `troposphere==3.0.0`: if you install `cfn-flip` manually and use `troposphere==3.0.0` you'll get

```
  File "./project/venv/lib/python3.8/site-packages/zappa/cli.py", line 1135, in update
    self.zappa.create_stack_template(
  File "./project/venv/lib/python3.8/site-packages/zappa/core.py", line 2375, in create_stack_template
    self.cf_template.add_description("Automatically generated with Zappa")
AttributeError: 'Template' object has no attribute 'add_description'
```

**Comment by markpeek** [comment]
cfn_flip issue is fixed in troposphere 3.0.1. The "add_description" had been deprecated in 2.x and removed in 3.x. Easy fix from the 3.0.0 release notes:
```
* Remove previously deprecated Template methods.
  To update to currently supported methods, substitute:
    add_description() => set_description()
    add_metadata() => set_metadata()
    add_transform() => set_transform()
    add_version() => set_version()
```

**Comment by litalyair** [comment]
Thanks for the fix, it works fine

**Comment by armando-herastang** [comment]
Hopefully this is addressed and released sooner rather than later. Having to manually force downgrade `troposphere` is not a really nice solution in order to `zappa deploy`

Watching #999
